### ISSUE TITLE
Enable line numbering by default for code [Feature Request]

### ISSUE THREAD

**Issue by calexil** [linuxmint/xed#103]
It would make sense for files detected as code (python,css,html,perl,c#,etc) would have line numbers enabled by default.

A radio box for "always show line numbers for code" should be implemented

**Comment by JosephMcc** [comment]
Not sure I really see the point in adding an option for this. You're basically saying everything except plain text files.

**Comment by calexil** [comment]
generally xed is used for two things

test docs... and code.

would it not make sense for it to default to lines showing for code... and not for text
