### ISSUE TITLE
Open link to the webpage in xed?

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/xed#104]
![image](https://cloud.githubusercontent.com/assets/23406555/24345930/920d786a-12d2-11e7-8036-d6a90ad356c9.png)

**Comment by theel0ja** [comment]
I would suggest gnome-terminal like menu for opening links.
![image](https://cloud.githubusercontent.com/assets/5832930/24579154/612da592-16f8-11e7-856f-156a9eb6cd6e.png)
