### ISSUE TITLE
xed save file as needs work

### ISSUE THREAD

**Issue by Bogwon** [linuxmint/xed#113]
xed version 1.2.2, but I think my browser (Chrome) and most other programs use the same save file dialog.

The file name is highlighted even when it is not active. Do something like change directory and it stays highlighted. Press control-V to paste a new name and nothing happens. Press the tab key until you get to the file name box and now control-V works. But now press Enter to save the file and nothing happens, which might be okay, but pressing the tab key does nothing either, so you cannot get to the Save button without using the mouse.

The worst part is the highlighting when the item is not active.

Linux Mint 10.1 Serena

**Comment by JosephMcc** [comment]
This has nothing to do with xed. That dialog is provided by Gtk and we have no control over that behavior.
