### ISSUE TITLE
add support for mouses with back/forward buttons

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/xed#115]
in many text-editors (sublime/notepad++)

using back/forward (horizontal scroll wheel tile on some models)
does shift to next/previous tab
could this be added?

**Comment by brkeh** [comment]
It might be useful to provide information about the signals the buttons send. `xev` might be useful for that.

**Comment by cmrdt** [comment]
`xev` seems to only react to keyboard presses, not mouse..

**Comment by brkeh** [comment]
`xev` opens a window called event tester for me. When I click in that `xev` prints information about the click.

**Comment by cmrdt** [comment]
scroll-wheel tilt-left or (history-back)
```
ButtonPress event, serial 37, synthetic NO, window 0x7200001,
    root 0xd5, subw 0x0, time 329243715, (167,111), root:(2948,566),
    state 0x10, button 8, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x7200001,
    root 0xd5, subw 0x0, time 329243895, (167,111), root:(2948,566),
    state 0x10, button 8, same_screen YES
```
scroll-wheel tilt-right or (history-forward)
```
ButtonPress event, serial 37, synthetic NO, window 0x7200001,
    root 0xd5, subw 0x0, time 329244552, (168,110), root:(2949,565),
    state 0x10, button 9, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x7200001,
    root 0xd5, subw 0x0, time 329244734, (168,110), root:(2949,565),
    state 0x10, button 9, same_screen YES
```

**Comment by JosephMcc** [comment]
Scroll wheel tilt right/left already works if the pointer is over the tab area.

**Comment by cmrdt** [comment]
not for my setup

**Comment by JosephMcc** [comment]
It only works if your are running xed >= 1.4. I'll look at adding support for mouse forward and back but it will be for the next release.

**Comment by cmrdt** [comment]
yes, using xed 1.2.2

**Comment by calexil** [comment]
@cmrdt  get this ppa 

sudo add-apt-repository ppa:gwendal-lebihan-dev/cinnamon-nightly

sudo apt-get update

install all the updates once. then go to software sources and disable the ppa(unless you want to be bombarded with daily updates)

update intermittently to stay on the edge of x-apps development

**Comment by JosephMcc** [comment]
I don't recommend that. The best way to get xed 1.4 is with Mint18.2.

**Comment by calexil** [comment]
I mean... if he wants it now
