### ISSUE TITLE
Xed should save text file with windows' end of line and *.txt file extension by default

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/xed#118]
Maybe Xed should save text file with windows' end of line and *.txt file extension by default because a lot of new users may not know this and have 'surprise'.
In my opinion save file with windows' end of line is important.

What do you think about it.

**Comment by JosephMcc** [comment]
In the end this is linux and I don't want xed saving my  files in a different way than other Linux text editors.

**Comment by brianally** [comment]
Please, no. Perhaps either option could be flagged in the preferences.

**Comment by francotgs** [comment]
I'm new in Linux Mint, how can I create a .txt file using Xed?
