### ISSUE TITLE
Save without trailing spaces should also act on trailing newlines

### ISSUE THREAD

**Issue by haarp** [linuxmint/xed#119]
Most "trailsave" plugins over the years also stripped trailing newlines from files to be saved, leaving only the single implied newline at the end.

Could the trailsave plugin be tweaked for this? Thanks!

**Comment by gavinhoward** [comment]
I have opened a pull request (#135) to fix this.

**Comment by haarp** [comment]
Thanks for that PR and having merged it. However it still leaves one newline too many at the end of a file, as of xed 1.6.0. One has to manually remove the last newline in the editor.

**Comment by icarter09** [comment]
@haarp are you still experiencing this issue?

**Comment by haarp** [comment]
> @haarp are you still experiencing this issue?

Yes, trailsave still leaves one line too many near the end which needs to be deleted manually.
