### ISSUE TITLE
Scrolling on document tabs doesn't work

### ISSUE THREAD

**Issue by haarp** [linuxmint/xed#120]
I am testing 1.4.1 and notice that scrolling on document tabs, implemented by PR #68, doesn't work for me. Neither horizontal or vertical scrolling on these tabs has any effect.

However, if xed was started with GTK_IM_MODULE=xim and the current document has no scroll bars, using the scroll wheel while the pointer is on top of the main document view switches documents (but scrolls normally if the document has scroll bars). This is very confusing.

In either case, scrolling while the pointer is on top of the tabs or the sidebar tabs does not switch tabs.

**Comment by JosephMcc** [comment]
Works as expected here. Only scrolls the tabs if the mouse wheel is within the "tab" area, not inside the document.

**Comment by haarp** [comment]
This is weird. I did some further testing on my machine.

Cursor on top of a tab: Scrolling does nothing
Cursor on top of empty space in tabbar: Scrolling switches tabs
GTK_IM_MODULE='', Cursor on top of document: Scrolling does nothing
GTK_IM_MODULE='xim', Cursor on top of document: Scrolling switches tabs (?!)
GTK_IM_MODULE='xim', Cursor on top of document, document has scrollbars: Scrolling does nothing

**Comment by icarter09** [comment]
@haarp are you still experiencing this issue?

**Comment by haarp** [comment]
> @haarp are you still experiencing this issue?

Yes. Cursor on top of a tab: Scrolling does nothing, cursor on top of empty space in tabbar: Scrolling switches tabs. xed 2.4.2

**Comment by collinss** [comment]
I can reproduce this. The icon, label and close or the container they're in seem to be 'eating' the scroll event. I'll see if I can track it down.
