### ISSUE TITLE
Syntax highlighting error

### ISSUE THREAD

**Issue by ThrivingRhino** [linuxmint/xed#123]
I discovered template literals today. I also discovered xed's javascript syntax highlight hasn't.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

version 1.2.2

![syntax](https://cloud.githubusercontent.com/assets/28644218/26099140/b7b22f60-39de-11e7-95fb-921c410436e1.png)

**Comment by JosephMcc** [comment]
Xed relies on GtkSourceView internally for syntax highlighting. If support for something is missing it should be filed upstream.

**Comment by ThrivingRhino** [comment]
https://bugzilla.gnome.org/show_bug.cgi

This has been fixed upstream.

**Comment by JosephMcc** [comment]
You're link doesn't seem to go anywhere.

**Comment by tobias47n9e** [comment]
Upstream doing upstream stuff :)

https://bugzilla.gnome.org/show_bug.cgi?id=782734

**Comment by JamesTheAwesomeDude** [comment]
This bug was never properly killed

I've re-opened it on their new website: https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/153

**Comment by JamesTheAwesomeDude** [comment]
@JosephMcc—please re-open this.

JavaScript's incomplete syntax highlighting support is fixed in upsteam (see above issue)

> Indeed. We're definitely not backporting all the JavaScript redesign to the 3.x series branch because that is in deep freeze. Applications such as `xed` have had ample time to move to GtkSourceView 4.x at this point (especially since it's mostly just a pkg-config name change with only a couple of ABI changes).
> 
> \[–chergert, gtksourceview Maintainer]
