### ISSUE TITLE
ugly white border (gtk 3.20>)

### ISSUE THREAD

**Issue by memoryleakx** [linuxmint/xed#124]
Hi,

I have a ugly white border around the Text Box.

Screenshot:
![alt text](http://imgur.com/e2XiGb0l.png "ugly white border (gtk 3.20>)")

System: Arch Linux
GTK Version: 3.22
Desktop Environment: xfce4
Theme:  Arc-Darker

**Comment by JosephMcc** [comment]
Do you see it on other themes such as Adwaita if you set xed to use the dark variation? I can't test under newer gtk versions at the moment but I'll try to set it up.

**Comment by memoryleakx** [comment]
if I set the dark variation the border is black.
But I think this borders are a general GTK 3.20> issue
https://github.com/numixproject/numix-gtk-theme/issues/659

**Comment by JosephMcc** [comment]
Checked with another of our devs that runs arch with Arc. What theme are you using in Edit->Preferences->Fonts and Colors? It seems some of these are actually the cause of the problem.

**Comment by memoryleakx** [comment]
My Settings:
Edit->Preferences->Fonts and Colors:
![alt text](http://imgur.com/wSHKj3jl.png "Edit->Preferences->Fonts and Colors")
All Dark Color Themes have the white Border

**Comment by memoryleakx** [comment]
this could be a solution:
https://askubuntu.com/questions/221291/remove-ugly-fat-bazel-from-gnome-terminal-with-multiple-tabs

put this properties into the related css class:
padding: 0;
border-width: 0;

**Comment by memoryleakx** [comment]
in Pluma it is fixed:
https://github.com/mate-desktop/pluma/blob/eee4c1d2a7c2673ecfff58daa01fc3a0ecf5d39a/pluma/pluma-status-combo-box.c

#if !GTK_CHECK_VERSION (3, 20, 0)
		"	-GtkWidget-focus-line-width: 0;\n"
		"	-GtkWidget-focus-padding: 0;\n"
#endif
		"	padding: 0;\n"
"}";

**Comment by JosephMcc** [comment]
Fixed in master.
