### ISSUE TITLE
launcher indistinguishable from gedit

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/xed#126]
Since the launcher uses ``Name=Text Editor`` exactly like **gedit** (and possible others), when you have both of them installed you have no way of knowing which one your are launching or opening a file with.
Even ``Comment=Edit text files`` is identical so not even a tooltip available in some places doesn't help.
Please make this more descriptive or unique.

**Comment by JosephMcc** [comment]
Trust me, I feel your pain :) This has been discussed internally though and I don't think you're going to see it change.

**Comment by oberon2007** [comment]
😝 😉
