### ISSUE TITLE
Feature request: Reload currently opened file

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xed#127]
Would be nice to have this from file-menu and with a shortcut (preferably F5).

**Comment by JosephMcc** [comment]
In most cases, when a file changes on disk from some other source, you get an info bar asking you if you want to reload. Occasionally for some reason this doesn't trigger though. I get this sometimes when I have my .xsession-errors open. So I would find this useful as well and I'll look to see how hard it is to implement.
