### ISSUE TITLE
[FEATURE REQUEST] Code Preview Scrollbar [Minimap]

### ISSUE THREAD

**Issue by memoryleakx** [linuxmint/xed#129]
It would be nice if you could add a Code Preview Scrollbar (Minimap).
Like in the Atom editor: https://atom.io/packages/minimap

**Comment by JosephMcc** [comment]
I was planning to add this at some point. It's a feature that is part of GtkSourceView in newer versions. Once we can newer versions of the libs, I'll look at adding it.
