### ISSUE TITLE
Opening new file doesn't always re-use existing instance

### ISSUE THREAD

**Issue by kiplingw** [linuxmint/xed#130]
Sometimes when I open a file from the shell or terminal without any command line options when I already have an Xed instance open, another new instance is created instead of re-using the existing one and merely appending a new tab. I am using Xed 1.2.2.

**Comment by JosephMcc** [comment]
Please try this again when you get the chance on Xed 1.4. A lot of the internals have changed that would affect this behavior.

**Comment by kiplingw** [comment]
Hey Joseph. I'm sorry, I hadn't realized mainline had been updated. I should have thought to check before posting. I've just pulled 1.4.2 and the issue appears to be resolved. Thank you.

**Comment by JosephMcc** [comment]
Thanks for following up.
