### ISSUE TITLE
Support for GEdit plugins

### ISSUE THREAD

**Issue by kiplingw** [linuxmint/xed#131]
It would be nice if one could install gedit 3 plugin packages on their favourite distro and have them work out of the box with Xed. One great example is the gedit-source-code-browser-plugin. If we assume they were API compatible (which they probably are not), one could pull the plugin packages of their choice if they had Xed installed. This could happen if the xed package provided a gedit alias so users could install Xed and GEdit plugins without having to install GEdit itself. Not that it should be a problem if users wanted to install both editors.

**Comment by JosephMcc** [comment]
This isn't really possible. Even though many of the internals are the same, we don't track as close to upstream as Gedit which could cause issues. Many plugins also require adding things like menu items or new sidebars. The UI differences make this nearly impossible.

That being said, if there are particular plugins that are popular with users, I'm not against investing time into porting some of them.

**Comment by kiplingw** [comment]
I understand. Probably the most important plugin I benefit from is a class browser.

**Comment by gavinhoward** [comment]
I am currently trying to port the gedit drawspaces plugin (among others) to xed. However, I am having trouble getting autotools to generate a correct Makefile.in for the plugin. I have never used the system before, but with a few pointers, I would be willing to put in some effort to port quite a few gedit plugins.

**Comment by JosephMcc** [comment]
@gavinhoward is it hosted on github somewhere?

**Comment by JosephMcc** [comment]
Keep in mind when we move to newer versions of GtkSourceView (likely in 1.6) the ability to draw spaces is built in to the library and a plugin will probably no longer be needed.

**Comment by JosephMcc** [comment]
I'm closing this since using Gedit plugins directly in xed just isn't going to be possible.

**Comment by kiplingw** [comment]
Joseph, since gedit-source-code-browser-plugin is out of the question, do you have a recommendation for another class browser plugin that is compatible with Xed for anyone else who stumbles across this thread with the same need?
