### ISSUE TITLE
The text area can't be scrolled to the bottom

### ISSUE THREAD

**Issue by magiclen** [linuxmint/xed#138]
![shot-04](https://user-images.githubusercontent.com/5851348/27083888-a03e0232-507c-11e7-8f7f-7d49b51d5284.png)

Please see the screen shot above. The vertical scrollbar at the right side reaches the bottom but the text area doesn't. This bug happens when I open a file **directly**(not open the xed application and choose a file to open).

OS: Linux Mint 18.2 beta
xed version: 1.4.2

**Comment by icarter09** [comment]
Linux Mint 19.2
xed v2.2.3

I'm not able to reproduce this.
