### ISSUE TITLE
Open File Dialog: Mounted devices show huge icons

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xed#141]
![auswahl_063](https://user-images.githubusercontent.com/6096063/27385280-59e78cd8-5692-11e7-8aa8-43ed83b1e9e5.jpg)

xed 1.4.3 
LM18.2 
Cinnamon 3.4.1

**Comment by JosephMcc** [comment]
This has nothing to do with xed. It actually looks like an issue in Mint-X icon theme.
