### ISSUE TITLE
UI: undo/redo history

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/xed#144]
currently if edited - file (from orginal) , it shows asterisk to show [modified],
but no indication if (both if @ undo-past state  or future-state look the same)
also does not show e.g. how many commits before/after save 
(relative position of 
  - current state
  - save state
in relation to undo/redo-buffer)

also undo/redo menu does not show how many items in queue/list

**Comment by JosephMcc** [comment]
We don't currently have plans to include this sort of functionality.
