### ISSUE TITLE
UI: find/replace scroll bar

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/xed#145]
if implement [zoomed-out highlight-view in scroll-bar](https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/)
![example](https://addons.cdn.mozilla.net/user-media/previews/full/116/116848.png?modified=1485521459)

**Comment by JosephMcc** [comment]
I do want to add a minimap which already has a feature request here: https://github.com/linuxmint/xed/issues/129
This should fill this need for the most part.
