### ISSUE TITLE
"make" does not work on LMDE Betsy

### ISSUE THREAD

**Issue by Fred-Barclay** [linuxmint/xed#15]
I get an error message each time I run "make" when compiling from source.
`fred@aussie ~/Downloads/xed-master $ sudo make`
`make: *** No targets specified and no makefile found.  Stop.`

The entire steps up to this step are listed here: https://gist.github.com/Fred-Barclay/3df2d56f2d5da71e96497b522b7cfea8

Thanks!

EDIT: This is on LMDE Betsy MATE 64-bit.

**Comment by JosephMcc** [comment]
Look at the last line of the output from running autogen.sh. It looks like you are missing a dependency.

**Comment by KDB2** [comment]
apt install enchant?

**Comment by Fred-Barclay** [comment]
Enchant might have been it. I followed @JosephMcc's instructions [here](https://forums.linuxmint.com/viewtopic.php?f=242&t=221719&p=1165181#p1165111) and after installing lots of dependencies, "make" is working.

Thanks! :+1:
