### ISSUE TITLE
Feature request: Change Case, put it in Edit menu

### ISSUE THREAD

**Issue by slavko-milanovic** [linuxmint/xed#153]
When Change Case function got built-in to main program (previously being a plug-in) it was placed in context menu (previously being in Edit menu). It made some confusion. I found it accidentally, I didn't expected it to be in context menu. So, my suggestion is to put it in Edit menu.

```
 * Xed version (1.4.6)

**Comment by icarter09** [comment]
Unable to find "Change Case" in any menu option for xed.
