### ISSUE TITLE
Feature Request: Recent documents list has size org.x.editor.max-recents

### ISSUE THREAD

**Issue by kiplingw** [linuxmint/xed#155]
```
 * Xed 1.4.6 (via PPA)
 * Distribution - (Xubuntu 17.04 / amd64)
```

Right now Xed shows a maximum of five recent documents in the File menu. There is a field in dconf that appears to be associated with this, org.x.editor.max-recents. It would be great if the File menu's recent document list size reflected this variable.

**Comment by brianally** [comment]
I just came here to try to figure out why I do not see _any_ recent files, ever. I don't mean to hijack but I'd appreciate any insight.

* Xed 1.2.2
* LinuxMint 18.1

Upgrade via PPA?

**Comment by JosephMcc** [comment]
If you are using Cinnamon, be sure to enable "Remember recently accessed files" in System settings->Privacy. I'm not sure if other desktops have similar settings.

**Comment by brianally** [comment]
It hadn't occurred to me that it could be s system setting. That worked. Thanks very much.

**Comment by JosephMcc** [comment]
@kiplingw it seems to work fine here.

**Comment by kiplingw** [comment]
Still doesn't work for me. My Xed (daily PPA snapshot) as of today shows only 5 files in the recent list, but org.x.editor.max-recents is set to 15.

**Comment by JosephMcc** [comment]
I tested this under xed 1.6.3. Setting the value of org.x.editor.preferences.ui.max-recents to 15 works fine here.

**Comment by kiplingw** [comment]
Thanks JosephMcc. The schema key has moved around, but otherwise I confirm that it works.

**Comment by JosephMcc** [comment]
If it works for you now I'm going to go ahead and close this.
