### ISSUE TITLE
Can't organize files in open file dialog box by file extension

### ISSUE THREAD

**Issue by MysticLord** [linuxmint/xed#156]
```
 * Xed 1.4.6
 * LMDE Mate 64-bit
```

**Issue**

Can't organize files in open file dialog box by file extension.

http://i.imgur.com/1tgLJOB.png
http://i.imgur.com/QZtHkXt.png

**Steps to reproduce**

File -> Open -> navigate to any directory with files of multiple types.

**Expected behaviour**

I expect there to be more options for organizing files than name, size, and modification date.  In other distros you can right click and select from a number of options for organizing files.

**Comment by JosephMcc** [comment]
Sorry but we don't control that. That dialog is provided by Gtk.
