### ISSUE TITLE
Caja bookmarks aren't organized by order in which they were made

### ISSUE THREAD

**Issue by MysticLord** [linuxmint/xed#157]
```
 * Xed 1.4.6
 * LMDE Mate 64-bit
```

**Issue**

Caja bookmarks aren't organized by order in which they were made.

http://i.imgur.com/1tgLJOB.png
http://i.imgur.com/QZtHkXt.png

**Steps to reproduce**

File -> Open -> navigate to any directory with files of multiple types.

**Expected behaviour**

I expect that Caja bookmarks to be listed in order that they were made.

**Other information**

Ideal for a config file.  Caja bookmarks organized by order in which they were made, most recently used, or alphabetical.

**Comment by JosephMcc** [comment]
That dialog is provided by gtk and how it displays those items isn't controlled by xed.
