### ISSUE TITLE
Feature Request: Keyboard shortcuts for tab navigation

### ISSUE THREAD

**Issue by MysticLord** [linuxmint/xed#158]
```
 * Xed 1.4.6
 * LMDE Mate 64-bit
```

**Issue**

It takes a second or two to move my hand away from the keyboard and click a new tab, especially on a laptop.  It would be handy to do this via a keyboard shortcut, and if that shortcut and others could be configured.

**Comment by rainynights** [comment]
Works for me. ALT + 1 for first tab, ALT + 2 for second tab, etc. I assume you mean tabs for files opened in the program.

Xed 1.4.6  
Mint 18.2 Cinnamon 64-bit

**Comment by MysticLord** [comment]
Navigating to a specific tab isn't the same as navigating to the next or previous tab.  When I'm typing on a laptop in a dark room I press 1 as often as I press F1 or F2.

The point is convenience, otherwise why use this text editor for editing source code?

**Comment by rainynights** [comment]
CTRL + ALT + PageDown will take you to the next tab. CTRL + ALT + PageUp doesn't work for me though, even though it should move to the previous tab. I'll post an issue for it.

**Comment by JosephMcc** [comment]
As pointed out by @ghost there are already shortcuts for changing to next/previous tab.
