### ISSUE TITLE
Keyboard shortcut not working.

### ISSUE THREAD

**Issue by rainynights** [linuxmint/xed#159]
```
 * Xed version 1.4.6
 * Distribution - (Mint 18.2 Cinnamon 64-bit)
```
**Issue**
The keyboard shortcut for moving to the previous tab doesn't work. In fact, it does nothing at all!

**Steps to reproduce**
Open 2 or more files and press CTRL + ALT + PageUp.

**Expected behaviour**
Should move focus to the previous tab.

**Other information**
CTRL + ALT + PageDown works fine (moves focus to the next tab).

**Comment by rainynights** [comment]
Sorry about this, turns out it's my keyboard that's the problem. Not sure how to delete the issue.

**Comment by JosephMcc** [comment]
No problem. It can just be closed.
