### ISSUE TITLE
xed crashes with language 'Defaults'

### ISSUE THREAD

**Issue by gkatev** [linuxmint/xed#160]
```
 * Xed version 1.4.6
 * Distribution - Mint 18.2 'Sonya'
```

**Issue**
xed crashes when working with files using the language Defaults(def). 
The console output is

**
GtkSourceView:ERROR:gtksourcecontextengine.c:5446:update_syntax: assertion failed: (state->context != NULL)
Aborted

**Steps to reproduce**
Open any file and set the language to 'Defaults'. Type a letter and xed will crash.
1. Open any file
2. Set the language to 'Defaults'
(3.) Type anything and xed will crash

**Comment by jp-sauve** [comment]
I'm affected by this too. Now I can't stop it from crashing, even if I open from the terminal and change highlighting to something else, save the file, and try and reopen.
