### ISSUE TITLE
RAM not released after huge file closed

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/xed#161]
```
 * xed - Version 1.4.6
 * Mint 18.2
```

xed doesn't release the RAM taken by a file after closing it. By opening and closing a 477,4 MB file the editor has reached 13GB RAM usage.

I downloaded a VMware Workstation Pro trial and I tried to open it from the Firefox download manager and xed got the honors of opening it. It took a very long time for anything to show up in the editor but before it fully opened I hit the cancel button in the editor, in order to stop it from loading up.

I expected xed to release the RAM, but it didn't happen. So I saved my existing work in xed and I closed it, which fixed the RAM issue.

**Comment by Vahan86** [comment]
@kneekoo, is this still an issue in Cinnamon 4.2 (xed 2.2.3)?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by kneekoo** [comment]
I'll add some feedback once I get my hands on my 32GB RAM PC, with the latest Cinnamon and xed, but if nothing has been done in this regard, I suspect the issue will persist.
