### ISSUE TITLE
Crash With Large Files

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/xed#163]
```
 * Xed version (xed --1.4.6)
 * Distribution - (Mint 18.2)
```

**Issue**
crashes and/or slow with large files 180 kB and larger

**Steps to reproduce**
force quit
load large file

**Expected behaviour**
no crash or slowness

**Other information**
n/a

**Comment by JosephMcc** [comment]
Do you have an example file that causes a crash?

**Comment by caltrop-3** [comment]
It is not so much a crash as I suspected but information overload.Large files mess up xed.
Attached is a file that locks up xed.
An XML file from a Garmin nuvi.

**Comment by JosephMcc** [comment]
You didn't attach the file. During load maybe try setting the highlighting to plain text and see if that helps.

**Comment by caltrop-3** [comment]
shows as attached

here it is again...?

**Comment by JosephMcc** [comment]
Not sure how you are replying but your attached test files aren't showing up.
