### ISSUE TITLE
Flickering when mouse cursor is on the tab title

### ISSUE THREAD

**Issue by riksoft** [linuxmint/xed#164]
```
 * Xed version 1.2.2
 * Distribution - Mint 18.2 Mate edition 64b
```

**Issue**
When the Window of the editor is maximized and I put the mouse cursor on the tab title it starts to flicker instead of showing the yellow popup with the file info.

**Steps to reproduce**
Maximize the editor window or simply move the window to the top left of the screen (or no more than few pixels from the top and no more than 100px from the left) and put your mouse cursor on the tab title.

**Expected behaviour**
Showing the popup as usual.

**Other information**
It's for sure tied to not using compositing.
I'm using the window manager Marco without compositing. Enabling compositing make it works properly.

**Comment by JosephMcc** [comment]
I can reproduce this but under Cinnamon it's different. If I fullscreen the xed window the tooltip for the first tab just refuses to show up.

**Comment by JosephMcc** [comment]
I don't see this as really being a Xed issue but something with the window manager.

**Comment by riksoft** [comment]
I still have the problem with a new Mint 18.3.
Who do you suggest to tell about this problem to see it fixed?

**Comment by riksoft** [comment]
I'm on Mint 18.3 and the problem seems to be solved. Xed or Mate/Marco has been modified and without compositor there is no more any yellow popup to trigger the loop.

**Comment by dodona2** [comment]
I can't confirm that for Fedora 28 (cinnamon 3.6.6/xed 1.6.2): no flickering when the editor is maximized and the mouse cursor is on the tab title. Therefore a Mint 18.2 Mate edition problem!

**Comment by riksoft** [comment]
> I'm on Mint 18.3 and the problem seems to be solved.
