### ISSUE TITLE
Xed crashes when right clicking (button-press-event) in TextView/Gutter

### ISSUE THREAD

**Issue by rebelwocause** [linuxmint/xed#165]
```
 * Xed version (xed 1.4.6)
 * Distribution - (Mint 18.2)
```

**Issue**
Xed crashes when right clicking (button-press-event) in TextView/Gutter

**Steps to reproduce**
With line numbering on right click just to the right of a line number in margin/gutter.
With line numbering off right click just to left of first character of text in small
margin/gutter area

**Expected behaviour**
No crash!

**Other information**
In GEdit with line numbering on and right clicking just to the right of a line number a 'Display line numbers' context menu is shown - no crash
In Gedit with line numbering off there seems to be no margin to right click in!

Xed appears to use GtkSourceView/GtkTextView so was wondering if this had to do with left hand gutter/margin and not calling 'gtk_text_view_get_window_type' in 'button-press-event' handler or something like this...

**Comment by JosephMcc** [comment]
Thanks for reporting. Found the problem.
