### ISSUE TITLE
Up/down arrow keys don't stay in same character column when using a font like 'Inconsolata' (a monospace font)

### ISSUE THREAD

**Issue by digimeas** [linuxmint/xed#168]
```
 * Xed version (xed --version) = 1.4.6
 * Distribution = Cinnamon 3.4.4 (Gtk 2.24.30) dm: mdm Distro: Linux Mint 18.2 Sonya
```

**Issue**
Up/down arrow keys don't stay in same character column when using a font like  'Inconsolata' (a monospace font).  Works as expected when "Use system fixed-width font" is ticked.  E.g.  in the following lines
```
K_LOOP:                                          //  200+ lines of awesomeness!!!
  while(k < areas.length) {                      //  length might change
```
both '//'s start in col 50, but if the cursor is at col 50 on the 1st line and I press the down arrow, the cursor ends up at col 48 on the 2nd line, and conversely uppitywise.

As highlighted as javascript, both 'while' and 'length' are bolded which causes the columns to appear staggered, but ...

**Expected behaviour**
I would expect that the arrow keys to stay in the same column.

**Other information**
I like xed!

**Comment by JosephMcc** [comment]
> I like xed!

Thanks :)

This isn't an issue with Xed. We use GtkSourceView and GtkTextView internally which handles all of this.
