### ISSUE TITLE
UI Bug: All "view" fonts resize commands make them smaller.

### ISSUE THREAD

**Issue by jordaorodolfo** [linuxmint/xed#172]
```
 * xed - Version 1.4.6
 * Manjaro
```

**Issue**
Clicking on the view commands "Smaller", "Larger" and even "Normal" text all make the font smaller, instead of doing their respective correct commands.

**Steps to reproduce**
Just open a new file, type something and try to resize the font either by the mouse wheel, either by clicking the menu commands, all these will shrink the text.

**Expected behaviour**
The mouse wheel, as well as the commands in the submenus should correctly change the text size.

**Other information**
I'm not an expert programmer by any means, but I think I can handle myself most of the time. Browsing through xed's code, I did not find in the "commands".h any that match this expanding or shrinking commands, not even looking at view-command.c; so I'm guessing that they were not implemented yet? Still, I have no idea why the shrinking happens if nothing was implemented.

Best regards,
Rodolfo

**Comment by JosephMcc** [comment]
I can't reproduce this issue on Mint. It works as expected. Wondering if this is being caused by newer Gtk or GtkSourceView versions in Manjaro.

**Comment by jordaorodolfo** [comment]
Well, could be! I'm sorry I have no expertise to pinpoint it. My repositories lists my GTK3 as version  3.22.21-1. If that helps in anything. Would it be better if I posted a gif or some pics of the issue on my setup?

**Comment by jordaorodolfo** [comment]
Worst of it is that I did have access today to a mint box (major version 18, don't know the minor, sorry!) and the xed version in there was 1.0.6, which did not have the same menu structure, and consequently did not have the "view zoom" commands. Is there any test I can do in my personal manjaro box to try out some fixes?

**Comment by JosephMcc** [comment]
Ok, so I tested this under Ubuntu17.10 with xed 1.6.3 and everything works expect making the text larger with Ctrl+=

**Comment by JosephMcc** [comment]
This report is against a much older version of Xed. I've never been able to reproduce it. If someone can reproduce under the current version, open a new issue.

**Comment by jordaorodolfo** [comment]
Right on it, @JosephMcc. I'm not using it much anymore (don't worry, not because of this old bug!), so I cannot test much myself anymore. I think it is fair to assume that the bug has gone away with newer releases.
