### ISSUE TITLE
Feature Request: Comment/Uncomment multiple lines at a time

### ISSUE THREAD

**Issue by chillywings** [linuxmint/xed#173]
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**
I can't figure out how to do it. If there's already a shortcut or plugin please let me know. This can be done in Notepad++ via ctrl+q, or in gedit (after installing the gedit-plugin package and enabling the code comment option) via ctrl+m/ctrl+shift+m.

**Steps to reproduce**
N/A

**Expected behaviour**
Insert # symbol at the beginning of selected lines

**Other information**

**Comment by MishraShivendra** [comment]
@clefebvre 
Hi,
I've been planing to do code changes for this feature. Not sure if someone already working on this. Also, Is  there any doc available about code organisation to get started?

Shivendra

**Comment by JosephMcc** [comment]
There is no one working on it that I know of.

**Comment by dodona2** [comment]
good idea!

**Comment by domdog** [comment]
I would love this too.  It is so nice to comment out a block of code.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/xed/pull/290
