### ISSUE TITLE
Opening binary files results in a livelock

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xed#174]
```
 * Xed version (xed --version) 1.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) LM18.2
```

**Issue**
Accidentally opening a binary file with xed results in a livelock.

**Steps to reproduce**
Open a binary file from any file manager using xed, or open a binary file in a running xed instance.

**Expected behavior**
Two possibilities:
1) Xed should say: This is a binary file. I cannot open it.
2) Xed could have a binary editor (plugin) to show binary files. Maybe this is out of scope for Xed, which is supposed to be a simple text editor.

**Other information**
Untested: Maybe the same problem occurs with a text file containing unknown characters or with a strange encoding.

**Comment by haarp** [comment]
> Xed should say: This is a binary file. I cannot open it.

No! This has been a major annoyance with older gedit versions. As soon as it encountered a char that couldn't be rendered with any charset, it just gave up, closed anything rendered so far and bailed out. Let's not return to these dark ages.

**Comment by JosephMcc** [comment]
@Piiit Could you provide a file that shows the issue?

**Comment by Piiit** [comment]
@JosephMcc Just take any PDF or image file.

**Comment by JosephMcc** [comment]
@Piiit this is what I get when I open a png here. It's about what I expect. Not sure what "livelock" means but xed is still working fine.

![screenshot from 2017-11-14 11-40-42](https://user-images.githubusercontent.com/2231759/32801108-f69b083c-c930-11e7-887c-9fcb8925cc93.png)

**Comment by Piiit** [comment]
@JosephMcc I tested now with different binary files of various sizes. It seems that it does not lock up, but just take really long to open the file. I see a progress bar on top of the text view with a cancel button, but the whole GUI is not responsible if the file is several MB big. The CPU goes up and the fan is constantly spinning. I think it just takes a long time to open the file and highlight the text. However, the cancel button is not responsible. I have to kill xed manually or wait a long time till everything is loaded, or the click action triggered. So this is not a livelock, but a event handling issue(?), I guess. Should I close the issue therefore?

**Comment by JosephMcc** [comment]
File loading is handled by the GtkSource API's. I think upstream knows that this is an area that could be improved. Testing a 2MB video file in xed and gedit, the results are very similar. In Fact xed seems to handle it a bit better.

I'm going to close this since it isn't really on our side.
