### ISSUE TITLE
Filterable Highlighting Language Menu

### ISSUE THREAD

**Issue by wesinator** [linuxmint/xed#176]
```
 * Xed version 1.4.6
 * Distribution - Mint 18.2
```

**Issue**
The highlighting language menu should be filterable so that users don't have to scroll all the way down to find a language.

**Steps to reproduce**
Open the syntax highlighting language selection menu.

User has to scroll through the list to find a language that isn't at the top.

**Expected behaviour**
There should be a text search filter for quickly finding a language. Gedit has this functionality:
![gedit_syntax_filter](https://user-images.githubusercontent.com/5124946/30968697-1ec475fa-a42e-11e7-9fee-6f7a7a228606.png)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. It would be nice to do something like this at some point but I'm not sure we find the use of a GtkPopover like gedit uses suitable.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
