### ISSUE TITLE
Find Issue & Large Files

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/xed#177]
```
 * Xed version (xed 1.4.6)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**
again... xed has issues with LARGE files
find does not center on items off screen in large files

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/xed/issues/70
