### ISSUE TITLE
support for Python3. configure syntax

### ISSUE THREAD

**Issue by cronolio** [linuxmint/xed#18]
i'm get error when run ./autogen.sh manually. version: xed-1.0.5 os: gentoo
full output [xed.txt](https://github.com/linuxmint/xed/files/307852/xed.txt)

checking for python version... 3.4
checking for python platform... linux
checking for python script directory... ${prefix}/lib64/python3.4/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python3.4/site-packages
checking for headers required to compile python extensions...   File "<string>", line 1
    import sys; print sys.prefix
                        ^
SyntaxError: invalid syntax
  File "<string>", line 1
    import sys; print sys.exec_prefix
                        ^
SyntaxError: invalid syntax
not found
configure: WARNING: Python not found, disabling python support

**Comment by nstommel** [comment]
Yes, when Python 3 is set as default, this happens. It does however work with Python 2.7. This is a critical bug

**Comment by kronolio** [comment]
yes. one guy say me how it work and with gentoo ebuild i set python2.7 version, when build. with python2.7 it work.

**Comment by JosephMcc** [comment]
We no longer check for python in git master so this is should no longer be an issue.
