### ISSUE TITLE
Can not open file from name in clipboard

### ISSUE THREAD

**Issue by jorivaa** [linuxmint/xed#180]
```
 * Xed version 1.4.4
 * Distribution Mint 18.2
```

**Issue**
No obvious way to open file from filename in clipboard.

**Steps to reproduce**
Nowhere to paste the file name!

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
You can do it from the file->open dialog. You have to use control+L to switch from the breadcrumbs to an entry in the dialog. I know this in non-obvious but it's also out of our control since that is the dialog provided by Gtk.
