### ISSUE TITLE
bug: schema not installed

### ISSUE THREAD

**Issue by pebbe** [linuxmint/xed#183]
```
 * xed - Version 1.6.0
 * Distribution - Debian GNU/Linux 9
```

**Issue**

xed aborts immediately with error message: 
```
(xed:13431): GLib-GIO-ERROR **: Settings schema 'org.x.editor.preferences.editor' is not installed
```

**Steps to reproduce**

```
xed
```

**Expected behaviour**

An open edit window?

**Other information**

**Comment by JosephMcc** [comment]
I can't reproduce this issue building and installing in Mint18.2 or Ubuntu17.10.
