### ISSUE TITLE
xed frequently fails to render underscores properly

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/xed#184]
Hi,

I'm running xed 1.4.6 on openSUSE Tumbleweed. It frequently fails to render underscores properly, showing them as spaces. Later after typing something else in the editor or playing around with the selection of text, the underscore appears again.

This is on a Thinkpad T530 laptop with Intel graphics and no other graphical glitches. Tumbleweed currently has libgtk-3-0 at version 3.22.

Thanks for the help.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/xed/issues/39
