### ISSUE TITLE
Scroll in the edit area with a middle mouse button but change the tab.

### ISSUE THREAD

**Issue by magiclen** [linuxmint/xed#186]
```
 * Xed version 1.4.6
 * Distribution - Mint 18.2
```

**Issue**

Scroll in the editor with a middle mouse button but change the tab.

**Steps to reproduce**

> 1. Open mutiple text files in different tabs.
> 2. Choose a tab which content is not long enouch to have a vertical scrollbar.
> 3. Scroll the edit area with a middle mouse button.
> 4. The tab changes.

**Expected behaviour**

> 1. Open mutiple text files in different tabs.
> 2. Choose a tab which content is not long enouch to have a vertical scrollbar.
> 3. Scroll the edit area with a middle mouse button.
> 4. Nothing should be scrolled.

**Comment by JosephMcc** [comment]
I'm unable to reproduce this on Xed 1.6 and nothing should have really changed to effect it. You can disable that option in the preferences under the "Editor" tab.

**Comment by magiclen** [comment]
I disabled that option in the preferences and this issue didn't happen again. But for sure, I can't scroll the tabs when I move my mouse onto the tab bar and roll the middle button after the option is disabled. I will try 1.6 later.

**Comment by magiclen** [comment]
This issue also happens on Xed 1.6.3. (Linux Mint 18.3)

**Comment by JosephMcc** [comment]
Hmm, I don't know what I was doing differently last time I tried this but I can reproduce it now.

**Comment by RecNes** [comment]
I can reproduce the bug with Xed 1.4.6 on Linux Mint with Mate desktop environment.
If text area not long enough to window, so scroll bar is not enabled. And if that tab is in between with other tabs, scrolling up the mouse scroll moving tab focus to previous, scrolling down with  mouse is moving focus to next tab.

**Comment by JosephMcc** [comment]
Just realized this was a duplicate. Lets keep it in one place: https://github.com/linuxmint/xed/issues/120
