### ISSUE TITLE
See dialogue with concerned user, appears to be that scripts that assume gedit installed will fail

### ISSUE THREAD

**Issue by brownsr** [linuxmint/xed#19]
Very_Agreeable1 xed invalidates all gedit-based online prescriptions, owing to the lack of a symlink of some kind. just let that sink in.
SimonB if you want gedit then just install it from the software manager
Very_Agreeable1 no, i mean that 18 hasn't aliased 'xed' to 'gedit'
Very_Agreeable1 and 'gedit' is a standard part of any such linux prescription available online.
SimonB so just install gedit if that causes a problem, surely ?
Very_Agreeable1 im saying that, if 18 is released without aliasing xed to gedit, it will break a lot of online help and advice, SimonB.
_marx_ is that a current default Very_Agreeable1 
Very_Agreeable1 for 18 xed replaces gedit
Very_Agreeable1 and all very laudable
Very_Agreeable1 but
_marx_ ah i c
Very_Agreeable1 if a simple aliasing of 'xed' to 'gedit' doesnt happen....
Very_Agreeable1 boom.
Very_Agreeable1 broken help pages.
_marx_ i see there as well
Very_Agreeable1 broken CLI prescriptions.
Sum1lson18 Very_Agreeable1: blog.linuxmint.com has a Mint18 Beta comments section
Very_Agreeable1 true
_marx_ well a cli that depends on gedit...
Very_Agreeable1 but i pose it here to the great and the good
SimonB Very_Agreeable1: can you give an example of something specific that you think will break ?  
Very_Agreeable1 no _marx)
Very_Agreeable1 no _marx_
_marx_ web pages, forum posts etc Very_Agreeable1 
Very_Agreeable1 no CLI would depend upon gedit, it's misguided or disingenuous to suggest it would
Very_Agreeable1 i'm saying
Very_Agreeable1 in the context of an important release
_marx_ web pages, forum posts etc Very_Agreeable1 that refer to gedit
Very_Agreeable1 of a loved and wanted distribution..
Very_Agreeable1 zzzz
SimonB it would be helpful if you could give a specific website, page etc. that you think will fail, or know does, so that it can be checked out
Very_Agreeable1 SimonB: any currently online advice to use bash on mint will fail in 18 where it includes references to 'gedit' over the newer 'xed', as of this beta.

**Comment by clefebvre** [comment]
He has a point. But I don't think we should take action. I think we should accept the fact that this isn't ideal but that it's for tutorials to adapt, not the other way around.

If people want to use gedit going forward, they shouldn't have a xed override getting in their way.

His point is valid but these issues were already there with tutorials not mentioning kate in KDE, pluma in MATE, leafpad in Xfce (in other distros) etc etc..

Our job is to give xed as much momentum as we can, to make it as awesome as we can, to make it work in as many places, environments and distros as we can, and to adapt our own documentation.
