### ISSUE TITLE
Risky Software Manager in 18.3 Cinnamon

### ISSUE THREAD

**Issue by happyniko** [linuxmint/xed#194]
With the release of Mint 18.3 Cinnamon there is a risky bug in the new Software Manager!

First at all, when you want to remove packages in the Software Manager the **window is to small to see the dependencies!** You have to expand the dialogue view manually each time! For removing packages this is really bad, because you don't see the dependencies and especially the ones you should not remove! **In the Software Manager 18.2 and earlier the system based dependencies were marked red. In Mint 18.3 you can't differ between them which can be removed and them which destroy your system when removed.** This is quite concerning!

Default view of the dialogue
![software manager window default](https://user-images.githubusercontent.com/34000003/33240490-6df5c5bc-d2ae-11e7-988a-cbece2372e58.png)

Expanded view of the dialogue - system based packages aren't marked!!!
![software manager window expanded](https://user-images.githubusercontent.com/34000003/33240491-7271b858-d2ae-11e7-99c3-bf1900ff339b.png)

AND PLEASE: **Bring back the short description for each package. This is no use for first-time users, when you have to click each time to get information about the package.**

**Comment by JosephMcc** [comment]
This is definitely not an issue with the xed text editor. It's an issue with mintinstall.
