### ISSUE TITLE
Add Devhelp plugin

### ISSUE THREAD

**Issue by kiplingw** [linuxmint/xed#197]
```
 * Xed version 1.6.3
 * Distribution - Ubuntu 17.10 (amd64)
```

It would be great if Xed had the Devhelp plugin for GEdit ported over. The plugin is already written, but I don't know how difficult it is to port to Xed.

https://wiki.gnome.org/Apps/Devhelp

**Comment by JosephMcc** [comment]
This one might be interesting.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
