### ISSUE TITLE
Error loading plugin 'spell'

### ISSUE THREAD

**Issue by R-a-l-f** [linuxmint/xed#198]
If I try to load the Spell Checker plugin after building xed 1.6.3 against enchant 2.1.2-2 from the Arch Linux extra repository and libpeas 1.22.0-1 from the Arch Linux extra repository I get

(xed:14082): libpeas-WARNING **: Failed to load module 'spell': /usr/lib/xed/plugins/libspell.so: undefined symbol: enchant_dict_add_to_pwl

(xed:14082): libpeas-WARNING **: Error loading plugin 'spell'

**Comment by JosephMcc** [comment]
When filing bugs please use the issue template. I don't have an Arch install but I'll see if I can look into this.

**Comment by gottcode** [comment]
The function ```enchant_dict_add_to_pwl()``` appears to have been replaced by ```enchant_dict_add()``` in enchant 2.0.0 (specifically, commit 744a1a19c1d0a5c3e1359fa994cf60a4d98ee12e). A quick patch to my copy of Xed to use ```enchant_dict_add()``` fixed the error loading 'spell', and spell checking works again.

**Comment by JosephMcc** [comment]
Cool. Thanks for the info.

**Comment by R-a-l-f** [comment]
Confirmed, it works for 2.2.3. My apologies for the late reply, but while all settings are correct, I don't receive notifications from github anymore and there are even no mails in the providers web-interface   spam folder, let alone my MUAs' spam folders.
