### ISSUE TITLE
Xed won't open new documents in existing editor window

### ISSUE THREAD

**Issue by deadpixi** [linuxmint/xed#200]
```
 * Xed version 1.6.3
 * Distribution - Ubuntu 16.04
```

**Issue**

Calling "xed FILENAME" or "xdg-open FILENAME" or click on a file in the file manager (with the default handler for text files being xed) does not open the FILENAME in a new tab in the existing xed window, but rather opens a new window.

The new window is not a separate instance, but is part of the other (original) xed instance. This seems like a bug for two reasons: (a) I swear it was opening files in a new tab in an existing window before and (b) I've glanced at the source for xed and it sure looks like it wants to open a file in a new tab.

(I verified that the window is part of the existing xed instance by examining the _WM_NET_PID property of both windows.)

**Steps to reproduce**

1. Open xed
2. From the command line run "xed file" or "xdg-open file" or click on "file" in the file manager.

**Expected behaviour**

The file opens in a new tab in the existing xed window. Instead, a new window is opened.

**Other information**

**Comment by JosephMcc** [comment]
I can't reproduce this on Ubuntu 18.04 with my dev branch. I'll have to retest later on Mint with xed 1.6

**Comment by deadpixi** [comment]
Thank you. As I said in the original comment, it seemed as though it *was* opening documents in a new tab and then suddenly stopped. 

I had been installing and uninstalling various packages around that time, but going back over my package manager's log, I don't see anything that would've caused that to change (and change in such a specific way). 

There is no diagnostic output on stderr with the default debug settings. 

Again, thanks for your help. Please let me know if there's anything I can do to help.

**Comment by deadpixi** [comment]
(When I say that installing/uninstalling things might have affected this, I mean that some gir package or something might have been uninstalled or something of the like, though again I didn't see anything obvious in the logs.)

**Comment by icarter09** [comment]
Linux Mint 19.2
xed v2.2.3

I'm not able to reproduce this issue. Performing the **Steps to reproduce** opened the file up in a new tab.

@deadpixi are you still experiencing this issue?

**Comment by Rudiberto** [comment]
The same here opening a file by clicking on it on Mint XFCE 20.04 two and a half year later.
It's quite annoying because other editors open like expected.
