### ISSUE TITLE
Xed prevents system from suspending

### ISSUE THREAD

**Issue by vlad0337187** [linuxmint/xed#201]
```
 * Xed version - 1.6.3
 * Distribution - Mint 18.3 Cinnamon x64
```

**Issue**
By empiric way I figured out that if to leave xed open and press "suspend" button, in most cases system won't be suspended.
It or: will tell that some tasks refused to freeze, or will act like suspended, but CPU fan will be turned on and monitor will be black.
From such last case I pin kern.log. Here we see, that last suspending was near 40 seconds, what is unreally much.
[kern.log](https://github.com/linuxmint/xed/files/1592456/kern.log)

So in most cases to suspend my system I must close Xed windows. Than in near 95 or more percents system will be suspended.

**Steps to reproduce**
Leave Xed opened after some time working and press "suspend" button. In near 80 percents of cases system will not be suspended.

**Expected behaviour**
System would be suspended in 100% cases.

**Other information**
I'll provide other logs when I'll met first case (when it'll write "tasks refused to freeze).

**Comment by Vahan86** [comment]
@vlad0337187, is this still an issue for you with Cinnamon 4.2 (xed 2.2.3)?

**Comment by vlad0337187** [comment]
@Vahan86 , still using Mint, I didn't see anything similar to this for a long time.

**Comment by icarter09** [comment]
@vlad0337187 thanks for the update.
