### ISSUE TITLE
close search x button too small

### ISSUE THREAD

**Issue by calexil** [linuxmint/xed#203]
```
 * Xed version (xed --version)
1.6.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint MATE 18.3
```

**Issue**
close search x button too small

**Steps to reproduce**
look at it
![screenshot at 2018-01-11 16-13-45](https://user-images.githubusercontent.com/3487071/34847798-8a1eecf4-f6ea-11e7-9c8a-49d9e295254b.png)

**Expected behaviour**
it's so  tiny

**Other information**
please fix this

**Comment by JosephMcc** [comment]
We are unlikely to change this design.

**Comment by calexil** [comment]
well how do i un-fuck it, cause it's too small to click almost a decade later
