### ISSUE TITLE
Add Notepad as Keyword

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/xed#21]
Can we have notepad added to list of keywords to make it appear on Menu search?

Notepad is really a generic phrase so I presume it won't lead to any patent or proprietary issues. :wink: 

`Keywords=text;editor;tabs;highlighting;code;multiple;files;pluggable;`

`Keywords=text;editor;tabs;highlighting;code;multiple;files;pluggable;notepad;`

**Comment by clefebvre** [comment]
https://github.com/linuxmint/xed/commit/817f78204017269e50c99a14fcfdbff14b195bd6

**Comment by anandrkris** [comment]
Thanks a lot, Clem. 
_(My Bro when he uses my Mint Box 2, unconsciously types notepad in menu and expects results, and I thought many users might do the same.)_
