### ISSUE TITLE
Add support for gdscript

### ISSUE THREAD

**Issue by pyropingvin** [linuxmint/xed#212]
Add support for gdscript

**Comment by JosephMcc** [comment]
This isn't very informative. I don't even know what gdscript is :) Does highlighting just need to be supported? If so that is actually handled upstream by GtkSourceView and would need support added there.

**Comment by pyropingvin** [comment]
Sorry I didn't know that, anyway GDScript is scripting language used by free and open source Godot gaming engine.
https://godotengine.org/
https://en.wikipedia.org/wiki/Godot_(game_engine)
Cheers :)
