### ISSUE TITLE
context menu leaves foreground black rectangle

### ISSUE THREAD

**Issue by chrisamow** [linuxmint/xed#215]
```
 * Xed version (xed --version)
1.0.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 18 Sarah
```

**Issue**
Top z-level rect remains where context menu was - no direct way to close it.

**Steps to reproduce**
Not always, but often, on 2nd monitor (not main) - right clicking on selected text to copy it will leave a black rect the shape where the menu was and it will be topmost and not go away.  xkill can't find it, but if i do a screen capture it will alter it (scrambled lines) and capture it.

**Expected behaviour**
Context menu disappears without a trace

**Other information**
I think after exiting all instances of xed the rectangles go away - I was closing things down to logout and they went away.

**Comment by JosephMcc** [comment]
You don't mention what Desktop environment you are running. I run Cinnamon and have never seen this issue.

**Comment by chrisamow** [comment]
sorry - i'm on mate
also, i'm using the nouveau driver 1.0.12-1build2 if that can make any difference

**Comment by icarter09** [comment]
@chrisamow are you still experiencing this issue?

**Comment by c-amow** [comment]
I've not seen this recently - but I've upgraded my OS since then.  Feel free to close and I'll repopen an issue if I see it.  Thanks
