### ISSUE TITLE
Make the preferences dialog window wider & resizable

### ISSUE THREAD

**Issue by ByteHazard** [linuxmint/xed#218]
The names of the color schemes (Fonts & Colors tab) and the descriptions of the plugins (Plugins tab) are only partially readable because the UI widgets in which they are displayed are much too narrow.

This dialog should be much wider by default (by 200% suggested), and ideally be resizable.

I would also suggest to add a hover tooltips, for cases in which the descriptions are still to long to be displayed in their entirety.

**Comment by JosephMcc** [comment]
The preferences dialog will be all new in Xed 1.8. It is now resizable :)
