### ISSUE TITLE
last line visibility

### ISSUE THREAD

**Issue by fotoneex** [linuxmint/xed#219]
```
 * Xed version (xed --version)   1.6.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Mint 18.3 Cinnamon
```
xed 1.6.3
Mint 18.3 Cinnamon

**Issue**
When working with CSV files of > 1,000 lines or so (about 100 char per row), the text of the last line has issues in being displayed.  The top 1/3 or less of that line shows - the cursor can be placed into the last row, but you can only guess at what is there.
My work around is to temporarily add in an empty line or two, edit, and then remember to remove the extra lines. 

**Steps to reproduce**
Any nice chunky CSV dataset - a club membership list, lotto results, attendance records, etc.

**Expected behaviour**
Last line should be fully visible to be edited. (the pluma editor is fine with the same files).

**Other information**
Smaller files behave perfectly.

Update: I found a good example to reproduce this bug:
http://spatialkeydocs.s3.amazonaws.com/FL_insurance_sample.csv.zip 
If you scroll down the the end, the last line you can see is 36634, but line 36635 appears or disappears depending on window size and unknown factors.

**Comment by icarter09** [comment]
Linux Mint 19.2 64bit
xed v2.2.3

@fotoneex thanks for providing a test file. I was not able to reproduce the results. I can see all of line 36635. I resized the window several times and was still able to view all of the last line.
