### ISSUE TITLE
Perl syntax colouration breaking

### ISSUE THREAD

**Issue by ewangi** [linuxmint/xed#222]
```
 * Xed version: 1.6.3
 * Distribution - Mint 18.3 MATE
```
Xed's Perl syntax colouration occasionally breaks. As an example, I loaded up the latest version, 3.0.04, of the Perl application inxi from https://github.com/smxi/inxi into xed. The resulting syntax colouration broke at six places in the script.

After each of the following Perl lines, xed is left thinking that it is still within a string, so that the code afterwards is a light purple colour, denoting string data, with occasional dark green ($/%/@ variables) and black (ordinary text, effectively between strings) colouration. This is using the Tango colour palette.

```
@rows = map {s/^\s+|\s+$//g; $_} @rows if @rows; [twice]

$id =~ s%/sys/class/power_supply/|\/$%%g;

$label =~ s%\\x2f%/%g;

@content = grep {/$search/i && !/^\s*$/} @content if @content;

$distro = (map {s/\\[a-z]|,|\*|\\||\"|[:\47]|^\s+|\s+$|n\/a//ig; $_} @working)[0] if @working;
```

These eventually reset themselves, often after dozens of lines, in various ways:

. a single apostrophe within a comment (e.g. for "don't", t goes back to normal colouration, although it isn't considered to be within a comment).

. grep !$seen{$_}++;

. next if /^\s*$/;

**Comment by JosephMcc** [comment]
Syntax highlighting is provided by the GtkSourceView library xed is built on. That's where this issue probably needs to be reported.
