### ISSUE TITLE
Feature request: add column selection (a la Sublime Text)

### ISSUE THREAD

**Issue by ocafebabe** [linuxmint/xed#223]
```
 * Xed - 1.6.3
 * Distribution - Mint 18.3
```

**Issue**
It would be very neat to get column selection a la Sublime Text (or something like multi-column editing in Geany)! It's definitely a must have nowadays for power users to change big blocks of text!

**Steps to reproduce**
N/A

**Expected behaviour**
N/A

**Other information**

**Comment by JosephMcc** [comment]
Isn't this the same as this: https://github.com/linuxmint/xed/issues/38

**Comment by ocafebabe** [comment]
You're absolutely right! Sorry my bad, I didn't remember that! Even worse, yesterday before creating a new issue, I've read all of them (titles only) to be sure that I wasn't duplicating an existing one ;)
