### ISSUE TITLE
The Xed does not remember Automatic Spell Checker setting, and selected language

### ISSUE THREAD

**Issue by anaconda69** [linuxmint/xed#224]
```
 * Xed 1.6.3
 * Distribution - Mint 18.3 Cinnamon
```

The Xed does not remember Automatic Spell Checker setting, and selected language

**Comment by CottonEaster** [comment]
It doesn't remember its internal themes, i.e. colour schemes either - and [this can be a serious problem](https://github.com/linuxmint/xed/issues/63).

**Comment by JosephMcc** [comment]
Can't reproduce this in Xed 1.8 and Mint 19. The spell check functionality was moved to new libraries in 1.8.
