### ISSUE TITLE
Feature Request: Display Whitespace, Newlines

### ISSUE THREAD

**Issue by Gotolei** [linuxmint/xed#225]
```
 * Xed 1.6.3
 * Xubuntu 17.10
```
Title. It would be nice to have this feature from Mousepad and Gedit. Screenshot of what it looks like in Mousepad, with both whitespace and newlines enabled:
![image](https://user-images.githubusercontent.com/7553595/39790214-f23aef5a-52f1-11e8-9d1d-ecffa9fa038b.png)

**Comment by eli-schwartz** [comment]
This was implemented above by @okaestne but the PR didn't autoclose the ticket.

**Comment by okaestne** [comment]
@mtwebster could close it
