### ISSUE TITLE
Feature Request: increase width of insertion point

### ISSUE THREAD

**Issue by ven-u** [linuxmint/xed#230]
```
 * Xed version (xed --1.6.3)
 * Distribution - (Mint 18.3,)
```

**Issue**
My 73-year-old eyes have a LOT of trouble finding the insertion point. Even zooming the text, it is still hard to find. I have to <Shift-sarrow> move the IP to find it. Or else take my hads off the keyboard and click with the mouse. 

Is there a setting for this? I'd love it to be 2 or 3 pixels, a colored block (other than that for overwrite mode), half-block, etc.

While you're at it, if there's any way to increase the contrast?

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by JosephMcc** [comment]
Hi, thanks for the suggestion. I looked into this but there doesn't seem to be any way to do this with GtkSourceView. I'll keep an eye out for this functionality but currently I think we are a bit out of luck.

As for the contrast, you could try changing the the theme the editor uses under "Edit->Preferences->Theme"
