### ISSUE TITLE
editorconfig plugin missing

### ISSUE THREAD

**Issue by binarymist** [linuxmint/xed#232]
```
 * Xed version (xed --version) All?
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) All?
```

**Issue**
Missing editorconfig plugin

**Steps to reproduce**
Look for editorconfig plugin

**Expected behaviour**
editorconfig plugin to exist

**Other information**
n/a

**Comment by JosephMcc** [comment]
Thanks for the suggestion. Currently there are no plans to create such a plugin but we'll keep it in mind for future consideration.
