### ISSUE TITLE
Modeline plugin in Vim mode doesn't work

### ISSUE THREAD

**Issue by samiel60** [linuxmint/xed#236]
```
 * Xed version 1.8.2
 * Distribution Mint 19.0
```
**Issue**
I installed MODELINE plugins. If I'm not wrong, putting in the first line a known Vim option as `set textwidth=80` the text should have to wrap, but it goes over...

**Steps to reproduce**
Write a text as:
`set textwidth=80`

`Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet.`

**Other information**
I've the doubt if I'm wrong in using that modeline plugin....

**Comment by JosephMcc** [comment]
It doesn't really work that way. If, for example, I add this line at the top of a new .c file
`/* vim: tw=60 ts=2: */`
That will set my tabs to be 2 spaces and move the display of the right margin to column sixty regardless of what I have it set to in the preferences. Xed only wraps lines at the edge of the view. Not at the displayed right margin.

**Comment by samiel60** [comment]
but so, what does it meant to use vim plugin in xed? what does it produce?
no way to obrain a hard wrapping in xed (as, for example, in Vim or Kate)?
