### ISSUE TITLE
Pressing Ctrl key spike up CPU load

### ISSUE THREAD

**Issue by ttjimera** [linuxmint/xed#237]
```
 * Xed version (xed --version)
xed - Version 1.8.2

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19
```

**Issue**
Pressing ctrl key by itself or in combination with other keys (e.g. ctrl+arrow, ctrl+c, ctrl+v, ctrl+z) causes xed to slow down and the CPU to go wild (on all cores). I noticed (through Conky's output) three processes hogging the CPU when this happened (Cinnamon, ibus-daemon, and xed). 

The CPU goes back to normal when I minimize xed to panel. When I maximize the window again I can continue working on the texts as usual. But as soon as I pressed ctrl again the same thing happened again.

**Steps to reproduce**
Press ctrl key by itself or in combination with other keys. Minimize the window and then repeat. 

**Expected behaviour**
That the CPU don't go wild simply when pressing ctrl key.

**Other information**
Tell me if you need other info. But here're the CPU and graphics info

CPU:       Quad core Intel Core i7-6700HQ (-MT-MCP-) cache: 6144 KB
           clock speeds: max: 3500 MHz 1: 2085 MHz 2: 2001 MHz 3: 1805 MHz 4: 1607 MHz 5: 2556 MHz 6: 2623 MHz
           7: 2273 MHz 8: 2067 MHz
Graphics:  Card-1: Intel HD Graphics 530
           Card-2: NVIDIA GM107M [GeForce GTX 960M]
           Display Server: x11 (X.Org 1.19.6 ) drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.10hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2) version: 4.5 Mesa 18.0.0-rc5

***I also noticed that the same issue occur with gedit as well but not with leafpad

**Comment by ttjimera** [comment]
[Issue remains, same system] It's now xed - Version 2.0.2 on LM 19.1. And my graphics info had changed as follows:

Device-1: Intel HD Graphics 530 driver: i915 v: kernel 
Device-2: NVIDIA GM107M [GeForce GTX 960M] driver: nvidia v: 390.77 
Display: x11 server: X.Org 1.19.6 driver: modesetting,nvidia unloaded: fbdev,nouveau,vesa 
resolution: 1920x1080~60Hz 
OpenGL: renderer: GeForce GTX 960M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.77

**Comment by icarter09** [comment]
@ttjimera are you still experiencing this issue?

**Comment by ttjimera** [comment]
I just checked (I have switched to another text editor since) and the same problem is still there.

**Comment by icarter09** [comment]
Linux Mint 19.2 64bit
xed v2.2.3

I'm not able to reproduce this issue. Followed the steps to reproduce, but did not notice the CPU go wild.

**Comment by cnlohr** [comment]
I also have this issue on Mint 19.3, on xed 2.4.2.   It only happens once every several minutes when doing editing.  I've gotta be typing away.

**Comment by Staff-d** [comment]
I also encounted this issue on my machine and can reproduce it by pressing the ctrl key rapidly, as @ttjimera reported. Fromn `inxi -Fz:`

```
System:
  Host: SNIP Kernel: 4.15.0-88-generic x86_64 bits: 64 
  Desktop: MATE 1.20.1 Distro: Linux Mint 19.1 Tessa 
Machine:
  Type: Desktop System: ASUS product: All Series v: N/A serial: <filter> 
  Mobo: ASUSTeK model: H97-PLUS v: Rev X.0x serial: <filter> 
  UEFI [Legacy]: American Megatrends v: 2502 date: 04/08/2015 
CPU:
  Topology: Quad Core model: Intel Core i5-4590 bits: 64 type: MCP 
  L2 cache: 6144 KiB 
  Speed: 798 MHz min/max: 800/3700 MHz Core speeds (MHz): 1: 946 2: 1002 
  3: 843 4: 1009 
Graphics:
  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 435.21 
  Display: x11 server: X.Org 1.19.6 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 435.21 
Info:
  Processes: 210 Uptime: 38m Memory: 11.67 GiB used: 1.80 GiB (15.4%) 
  Shell: zsh inxi: 3.0.27 
```

Xed: 2.0.2

**Comment by tedsmith** [comment]
I have it also on Linux Mint 19.3, for info.

**Comment by cnlohr** [comment]
I am not sure the root cause but it started after installing zoom on Linux and stopped after I removed all packages that were pulled down for it.

**Comment by Staff-d** [comment]
@cnlohr I also recently had to install zoom (thanks to corona), but it isn't running most of the time and the problem can be reproduced when it is turned off. Either way I'll give it a shot and uninstall it to check if that helps.

**Comment by tedsmith** [comment]
I too have just uninstalled Zoom and now is working well. So it seems there is SOMETHING to do with Zoom that causes problems for the text editors.

**Comment by cnlohr** [comment]
IIRC Uninstalling _just_ zoom did not resolve it, which would indicate it was one of the things it relies upon.

**Comment by ttjimera** [comment]
I encountered this problem way back in 2018 when I have not even heard of Zoom yet, much less install it. From what I can see, the process that spikes up CPU activity (as observed via Conky) is ibus-daemon.

**Comment by cnlohr** [comment]
Hmm... ibus was one of the systems that were installed/uninstalled with zoom.

**Comment by ttjimera** [comment]
It is possible that the problem is due to some interaction between the editor and the ibus input system which was triggered when the Ctrl key is pressed.

**Comment by Jadzia2341** [comment]
Same problem here on Linux Mint 19.3 with Xed and Ibus going up in CPU usage.

**Comment by ttjimera** [comment]
Since I installed LM20, running xed 2.6.2, I no longer have this problem.

**Comment by cnlohr** [comment]
I will try this.  I am on LM20 on one system, and I rather like it (except for the janky Chrome support) but other than that it feels better.  It looks like IBUS was reworked so it may very well solve the issue.

**Comment by ttjimera** [comment]
I am closing this issue as I no longer experience this issue since LM20
