### ISSUE TITLE
Xed does not remember window size or position

### ISSUE THREAD

**Issue by calexil** [linuxmint/xed#24]
as the title states: Xed does not remember window size or position, it resets to the primary diaplay and default size every time it is closed and opened

mint 18 MATE 64, compton

edit1: I was able to overcome the dimension issue by forcing the correct dimensions in xed.ini, although it should not need to be fixed in this manner.

**Comment by JosephMcc** [comment]
Under Cinnamon it seems to remember it's size just fine.

**Comment by Vahan86** [comment]
Can't reproduce the issue in Cinnamon 3.0.7. It's working fine for me as well.

**Comment by calexil** [comment]
As previously mentioned... this issue only happens on MATE ed as far as I can tell

**Comment by JosephMcc** [comment]
Does it happen if you switch to one of the other compositors? Like metacity, marco, or compiz? In Cinnamon you have controls for default window placement. I have mine set to center and the window always opens in the center but the previous size is remembered.

**Comment by calexil** [comment]
it happens regardless of compositor and window manager

**Comment by JosephMcc** [comment]
Just did a bit more playing around. In Cinnamon at least, xed respects the placement I set for all windows in Cinnamon. I don't think it does anything to remember it's previous placement. Not sure why the size isn't saved/remembered under Mate.

**Comment by peneus** [comment]
Having the same problem on Linux Mint 18 Mate with compiz.

**Comment by JosephMcc** [comment]
Could one of you having this issue try running xed from the terminal? When you close the window, do you get a warning about writing the state file?

**Comment by calexil** [comment]
@JosephMcc I can give you a more detailed explanation actually. I was able to overcome the dimensions by forcing the config file to include my desired dimensions in xed.ini. but that still leaves the position and last active monitor issue. 

I noticed something interesting, If my mouse is hovered on my primary monitor the xed opens with the right dimensions, but is centered and never remembers its last position...however, if I have my mouse on my secondary monitor(which is where I always have xed open) it opens in the right position every time.

**Comment by calexil** [comment]
also @JosephMcc I ran xed from terminal as you asked, and no errors were thrown regarding a state file

**Comment by JosephMcc** [comment]
I don't think it tries to remember location, only size and state. Placement is often handled by the window manager. In Cinnamon, for example, I have things to set to open in the center of the monitor. This works by opening it in the center of the monitor the mouse is currently on. I'm not sure we should be override the settings set for the WM in specific apps. This leads to inconsistent behavior, IMO.

**Comment by calexil** [comment]
it used to remember it's position, now it does not. thats the point of the bug report, something regressed

**Comment by JosephMcc** [comment]
It remembered its position when? You listed the problem in Mint 18 which was the first shipped with xed.

**Comment by calexil** [comment]
well, before it was xed I suppose, back in 17.3 or mayba when xed was first released, I dont really remember exactly

**Comment by JosephMcc** [comment]
Well pluma was given special treatment in Mate. That isn't going to happen in Xed since it's cross DE and that stuff was removed.

**Comment by calexil** [comment]
dangit

**Comment by calexil** [comment]
okay, my .congig/xed/ folder was ownde by root for some reason.

deleted it and let xed auto create it upon restart, and now the window dimensions are being saved

but the window POSITION is still not saved
