### ISSUE TITLE
unable to mark first char of line with mouse

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/xed#240]
```
 * xed - Version 1.8.3
 * Distribution - (Mint 19 Cinnamon)
```

**Issue**
unable to mark first char of line with mouse

**Steps to reproduce**
Open a textfile an sidepane from xed. Try to mark a line with mouse from the left to the right. Is not possible because the mose catches teh paneborder

**Expected behaviour**
should be possible to get the first char

**Other information**
![menu_20180720_08 49 47](https://user-images.githubusercontent.com/2804301/42987581-09b0ede2-8bfa-11e8-9eb5-519c639ddccd.jpg)

**Comment by JosephMcc** [comment]
Thanks for the report. I'll look into that.

**Comment by stefanoful** [comment]
it's happened also with tilix (terminal) on the partition of the split panels. Mouse don't selection the first characther, but switch  on resize icons

**Comment by JosephMcc** [comment]
As I expected after seeing the comment by @stefanoful this was a theme issue. Fixed in our themes here: https://github.com/linuxmint/mint-themes/commit/25308bcb65f2ce93a740d5d55d6bc71008c41195

There isn't much I can do with other themes. You could also get around this by enabling line numbers.
