### ISSUE TITLE
Pressing "tab" produces four spaces instead of the "tab" character by default.

### ISSUE THREAD

**Issue by gemkibeju** [linuxmint/xed#245]
```
 * Xed version - 1.8.3
 * Distribution - Mint 19 Cinnamon
```
**Issue:**
The default preferences for xed, in the "Editor" tab and under the "Indentation" section, has the following option enabled: "Use spaces instead of tabs".

I don't understand why this option is enabled. I use xed to compose stories, journals, and poetry - all fields which require formatting that work well with rich text editors like Libreoffice. Using spaces as indents don’t work well with Libreoffice, and if I ever want to import my plain-text writings into Libreoffice, there will be unexpected behaviour with that program because of unexpected behaviour with xed.

I don’t have any use for this option in my case, and having it enabled without telling me has caused me much trouble in the past. The same thing happened to me when I installed Mint 18.2 and Mint 18.3. It's been over a month since I installed Mint 19, and I have to go back and look at everything I've written down over the past month to make sure the formatting isn't screwed up.

When I'm trying to update my blog using HTML and CSS, it's actively detrimental to my development there. I ended up mixing tabs and spaces in my indents, and now I have to download my website from my web host to make sure nothing is mixed.

Personally, I would appreciate it if my text editor was honest about what characters its inserting into my text, instead of silently throwing in spaces for a reason it never tells me.

**Steps to reproduce:**
On a default xed configuration, press the tab key on your keyboard.

**Expected behaviour:**
Pressing "tab" on my keyboard produces a tab space: Unicode codepoint U+0009. It should not silently produce four spaces unless the user enables the option.

**Comment by JosephMcc** [comment]
Looking at making the current setting more obvious to the user by displaying if we are currently set tabs or spaces in the statusbar: https://github.com/linuxmint/xed/pull/246
