### ISSUE TITLE
feature request - list of recently opened files - that are removable from the list

### ISSUE THREAD

**Issue by danostg** [linuxmint/xed#247]
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by pgmer6809** [comment]
I strongly support this.

**Comment by icarter09** [comment]
This feature request is to add in the ability to remove files from the recently opened list....that correct?
