### ISSUE TITLE
RFE: support for very large text files

### ISSUE THREAD

**Issue by jsfan3** [linuxmint/xed#248]
Xed, like Gedit, has perfomance issues when handling with very large files, like a MySql database dump. For example, try to do a search/replace on a file with hundreds of thousands of lines... it's very difficult or even impossible.

When I need to open, modify, to search/replace on very large text files, I can use "nano" (on Linux from command line), that can handle text files of any size with performance issues... however I prefer to be able to use Xed, if it's possible, because it's the default text editor of my favorite Linux distribution (Linux Mint, of course).

To compare, the same operation of search/replace on a large MySql database dump requires minutes with Xed and only a fraction of second with "nano". 

Thank you for the support,
Francesco Galgani

**Comment by JosephMcc** [comment]
Thanks for the feedback. Unfortunately most of what you brought up is out of our hands. Xed, like GEdit,  is based on GtkSourceView and these are limitations of that.
