### ISSUE TITLE
xed help file has broken link

### ISSUE THREAD

**Issue by pgmer6809** [linuxmint/xed#251]
```
 * Xed version (xed --version )xed - Version 1.8.3
 * Distribution - Mint19 (Tara)
```

**Issue**
HelpContents  brought up thru the Help menu item under the Working with Plugins section  has a link to:
https://wiki.gnome.org/Xed/Plugins
But this link says it is not implemented yet.

**Steps to reproduce**
Help=>Contents(F1) => Plugins => Working with plugins
Now click on the green link near the top of the text box that says **xed website**

**Expected behaviour**
A web page that will display xed plugins to be downloaded

**Other information**

**Comment by icarter09** [comment]
Linux Mint 19.3
Xed v2.4.2

Was able to reproduce this issue.
