### ISSUE TITLE
Feature request: add source code comments

### ISSUE THREAD

**Issue by GitHubIsToxic** [linuxmint/xed#252]
I'd very much like to contribute to xed or write plugins, but it appears all xed source code is completely devoid of comments explaining what the code does (or is supposed to do).

Even the plugin template has no useful comments, not even a readme.

This greatly raises the bar for anyone willing to contribute, and will likely create a maintenance nightmare years from now when current developers/maintainers retire.

**Comment by JosephMcc** [comment]
Thanks for the input. Maybe when someone has some time they'll get around to this.
