### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by zagalvelozo** [linuxmint/xed#253]
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**

typescript highlighting

**Steps to reproduce**

Open any file .ts

**Expected behaviour**

This text editor should be highlight typescript language

**Other information**

**Comment by JosephMcc** [comment]
Syntax highlighting is provided by GtkSourceView. Not directly by xed. Looks like it's already been requested upstream: https://gitlab.gnome.org/GNOME/gtksourceview/issues/5
