### ISSUE TITLE
Is it possible to build xed in Windows?

### ISSUE THREAD

**Issue by proninyaroslav** [linuxmint/xed#254]
**Issue**

Xed is my favorite editor and so it happened that I need to work on Windows. GEdit releases builds for Windows. Is it possible to compile Xed on Windows (as is possible with GEdit)? I think that it's possible to compile, but how Xed compatible is with other platforms other than GNU/Linux?

**Comment by JosephMcc** [comment]
No it isn't. The ability to build on Windows or Mac was removed long ago and there is no intention to support it. Sorry.

**Comment by invlpg** [comment]
I've been compiling it just fine...?

i use the visual studios console which has a bunch of env variables set. Not exactly sure how mbuild works but i havent had any issues building this on windows.

**Comment by aks2161989** [comment]
> I've been compiling it just fine...?
> 
> i use the visual studios console which has a bunch of env variables set. Not exactly sure how mbuild works but i havent had any issues building this on windows.

Hey, can you share how exactly you build xed on windows? Which VS version, which xed version and build commands? I would really appreciate it
