### ISSUE TITLE
Does libpeas work with python ?

### ISSUE THREAD

**Issue by stuaxo** [linuxmint/xed#257]
Hi,
On Xed 1.8.3 on mint 19.

  I've been trying to rewrite my Gedit plugin to work with Xed.

I assumed I could change my import to something like:

```from gi.repository import Xed```

This didn't seem to work though :(

Is there a package I can install to get libpeas working?

**Comment by JosephMcc** [comment]
You don't really provide enough info to troubleshoot this. Install these two files in either ~/.local/share/xed/plugins or /usr/lib/xed/plugins for a working example

exampleplugin.plugin:
`[Plugin]
Loader=python3
Module=examplepy
IAge=3
Name=Example py
Description=A Python plugin example
Authors=JosephM
Copyright=None
Website=None`

And examplepy.py:
`from gettext import gettext as _
from gi.repository import GObject, Gtk, Xed

# Menu item example, insert a new item in the Tools menu
ui_str = """<ui>
  <menubar name="MenuBar">
    <menu name="ToolsMenu" action="Tools">
      <placeholder name="ToolsOps_2">
        <menuitem name="ExamplePy" action="ExamplePy"/>
      </placeholder>
    </menu>
  </menubar>
</ui>
"""

class ExamplePyPlugin(GObject.Object, Xed.WindowActivatable):
    __gtype_name__ = "ExamplePyPlugin"

    window = GObject.property(type=Xed.Window)

    def __init__(self):
        GObject.Object.__init__(self)

    def do_activate(self):
        # Insert menu items
        self._insert_menu()

    def do_deactivate(self):
        # Remove any installed menu items
        self._remove_menu()

        self._action_group = None

    def _insert_menu(self):
        # Get the Gtk.UIManager
        manager = self.window.get_ui_manager()

        # Create a new action group
        self._action_group = Gtk.ActionGroup("ExamplePyPluginActions")
        self._action_group.add_actions([("ExamplePy", None, _("Clear document"),
                                         None, _("Clear the document"),
                                         self.on_clear_document_activate)])

        # Insert the action group
        manager.insert_action_group(self._action_group, -1)

        # Merge the UI
        self._ui_id = manager.add_ui_from_string(ui_str)

    def _remove_menu(self):
        # Get the Gtk.UIManager
        manager = self.window.get_ui_manager()

        # Remove the ui
        manager.remove_ui(self._ui_id)

        # Remove the action group
        manager.remove_action_group(self._action_group)

        # Make sure the manager updates
        manager.ensure_update()

    def do_update_state(self):
        self._action_group.set_sensitive(self.window.get_active_document() != None)

    # Menu activate handlers
    def on_clear_document_activate(self, action):
        doc = self.window.get_active_document()
        if not doc:
            return

        doc.set_text('')`

**Comment by JosephMcc** [comment]
Put these two files in ~/.local/share/xed/plugins or /usr/lib/xed/plugins
examplepy.plugin: https://pastebin.com/iA7RjSJ6
examplepy.py: https://pastebin.com/BcUkei8h

**Comment by stuaxo** [comment]
Cheers, that's been pretty handy.

When it comes to menus does Xed use Gio (like Gedit after 3.12) or the model in older Gedits.   I'm trying to make something that works in all of these things, and have got quite far, but can't see any Xed python examples that create menus.
