### ISSUE TITLE
[Bug] xed does not show any pages except first one in print preview

### ISSUE THREAD

**Issue by Schallaven** [linuxmint/xed#260]
```
 * Xed 1.8.3
 * Distribution - LM 19 Tara, Mate 1.20.1 (in a VM)
```

**Issue**

A user reported this behaviour in #linuxmint-help and I could reproduce it. With the following minimal settings file xed will simply not show or print any page except the first one.

```
~/.config/xed/xed-print-settings

[Print Settings]
print-pages=ranges
page-ranges=0
```

**Steps to reproduce**
- close any instance of xed, create above print-settings file (the rest of the file does not matter as far as I know and tested, but better to use the minimal one above)
- create a test file with more than 1 page: `base64 /dev/urandom | head -c 10000 > testtext`
- open this test file with xed: `xed testtext`
- open print preview (File->Print Preview)
- try to view the second page: it will be empty. try to show more than 1 page, e.g. 2x2 will result in not showing a page at all

**Expected behaviour**
Show and print all pages, of course.

**Other information**
Actually, only the `ranges` of the `print-pages` setting is the problem. Without the `page-ranges`, however, xed will simply refuse to show the print-preview at all and close with:

```
(xed:22841): Gtk-WARNING **: 13:59:08.701: no pages to print
```

I am not sure why there is a string for `print-pages` in the config file at all. I suspect that a printer-driver/cups-setting might have been just forwarded to this line in the config and then caused this problem (I tried to find the problem in the code, but did not find it).

**Comment by JosephMcc** [comment]
I'm having a problem seeing what the bug is here. The print preview is showing you exactly what you are asking for in your print settings. You are saying you want a range, and that range is zero. Which is only the first page. Go to File->Print and change the settings if you want it to show you something different. If you open the print settings and change the setting for the Range to "All Pages", the print-pages line will then become print-pages=all and it will ignore the page-ranges line.

**Comment by Schallaven** [comment]
It is not logical that xed gives you the option to show you the pages, which are not printed in the print preview at all - and then NOT display them. (And despite that: a page-range of ZERO is not logical either.)

As said, this was reported in #linuxmint-help and I forwarded it after reproducing it. The user was not aware of the setting and the non-display of the pages was confusing apparently.

Here you see that nothing is shown, maybe then include a message at least saying "this page is not in the current page-limit"?
![xed2](https://user-images.githubusercontent.com/6428497/48328503-436fcb80-e612-11e8-8ac7-54b1eea14e66.png)

This is from the 2x2 grid, which makes room for a second page (and you can scroll empty space!), but does not display anything. Confusing and misleading, if you ask me. Maybe again, display a message? Or a greyed out version of the page? Or a page place holder?
![xed3](https://user-images.githubusercontent.com/6428497/48328571-90ec3880-e612-11e8-8ea8-3397e6f460ea.png)
