### ISSUE TITLE
missing ./autogen.sh install script

### ISSUE THREAD

**Issue by lucserre** [linuxmint/xed#262]
Just cloned latest "git clone https://github.com/linuxmint/xed.git" and the installation instructions say to run autogen.sh but it's missing.

**Comment by leigh123linux** [comment]
xed has been ported to meson

```
meson --buildtype=plain --prefix=/usr . builddir
ninja -v -C builddir
ninja install -v  -C  builddir
```

**Comment by leigh123linux** [comment]
@lucserre  Is that better?

https://github.com/linuxmint/xed/pull/263

**Comment by lucserre** [comment]
Looks good to me, but I'm no expert.
Thanks!
