### ISSUE TITLE
Launch Error On Ubuntu 18.10 after successful build 

### ISSUE THREAD

**Issue by MASTERGUY** [linuxmint/xed#265]
```
 * Xed version (Xed Version2.01)
 * Distribution - (Ubuntu 18.10 (Cinnamon Env)
```

**Issue**

(xed:26161): GLib-GIO-ERROR **: 12:06:41.404: Settings schema 'org.x.editor.preferences.editor' is not installed

**Steps to reproduce**

Tried to rebuild after removing old one 
but same

**Expected behaviour**

**Other information**
great to have it working on my system if it is possible

**Comment by chingyinwan123** [comment]
Maybe the settings schema is not compiled?

You could try running the following as root:
`/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/`

Try running xed again after running the command above.

**Comment by leigh123linux** [comment]
Compiles and works fine on mint or fedora, maybe try a forum for your compile issue.

**Comment by MASTERGUY** [comment]
@chingyinwan123 and @leigh123linux  thanks did a clean build with meson --prefix=/usr . build and then after clean build i compiled /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/ with root and it works well :) thanks alot both of you

**Comment by stuaxo** [comment]
Just came here with the same error, fixed by passing the correct path to glib-compile-schemas:
 `$ sudo /usr/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas/`
