### ISSUE TITLE
Bug: increasing tab padding with each new "Unsaved Document" tab

### ISSUE THREAD

**Issue by s44i7h-sam** [linuxmint/xed#268]
```
 * Xed version 2.0.2
 * Distribution - Mint 19.1
```

**Issue**
**The tab button padding** (left and right padding) is for some reason increased with each new "Unsaved Document" tab. This wastes a lot of window space and make very few tabs visible at one time. This padding is increased across all button tabs. At two "Unsaved Document" tabs the padding already becomes huge and very annoying.

The following is a related, but merely subjective issue, and I only mention it for consideration: **the length of the label** "Unsaved Document" itself also wastes a lot of space, hiding other tabs. In my experience it is always by far the longest tab label among others, eating up much more space than other tabs - which is a shame because usually these "Unsaved Document" tabs are of lesser importance, used merely for temporary pasting. If I have two "Unsaved Document" tabs opened then at most only two other tabs fit into the window. I would like to see this label shortened somehow (perhaps to just "Unsaved"?). I wouldn't mind doing it only for my own use if you could tell me which localization file to change, how to compile it correctly, and where to place it.
However if the increasing padding bug is fixed than the length of the "Unsaved Document" label will also be less annoying.

**Steps to reproduce**
Open a few existing text documents, then open some new tabs. If possible, test this on a smaller screen, such as on an small laptop, to see in practice how much usable window space this increasing padding wastes.

**Expected behaviour**
The padding should remain fixed at the initial/minimal size - just the way it already is when you have *only* existing documents opened *without* "Unsaved Document" tabs.
(Possibly the label "Unsaved Document" itself should also be shorter, but I understand that this could introduce translation difficulties for some other languages.)

**Comment by JosephMcc** [comment]
Ok I can reproduce this. It only happens once the number of tabs forces the notebook to show the arrows for scrolling through them.

**Comment by icarter09** [comment]
Disabling the auto expand feature that gives each tab equal space still does not fix this issue. Regardless of the padding set, the tabs will continue to expand. Talked to @collinss about possible solutions. His idea of using ellipsis in the title is the best fix for the initial issue, but that also introduces new issues as well (such as which section of the file name would the ellipsis scheme replace).
