### ISSUE TITLE
gdk window failed

### ISSUE THREAD

**Issue by scrognoid** [linuxmint/xed#272]
```
 * Xed version (2.0.2)
 * Distribution - (Mint 19.2 Mate)
```

Every time is launch xed from the command line I get an error
(xed:23527): Gdk-CRITICAL **: 15:21:29.528: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
It doesn't seem to cause a problem but it annoys. I find nothing related anywhere on the web.

**Steps to reproduce**
launch xed from termimal

**Expected behaviour**
no error message

**Other information**

**Comment by mrdrthom** [comment]
+1 (Mint 19.1 Cinnamon) this wart occurs with a standard out-of-the-box installation 

(warning, soapbox speech incoming) and false error messages make troubleshooting real problems that much harder

**Comment by dino0815** [comment]
+1(Mint 19.1 Mate) out-of-the-box installation with updates

**Comment by MaartenLAB** [comment]
Got the same issue on a fresh install of Linux Mint 19.1 Cinnamon. Didn't use XED before updating. Occurs when starting from terminal. 
Anyone found or can recommend a fix for this?
