### ISSUE TITLE
Tabbed text does not preview, nor print properly

### ISSUE THREAD

**Issue by MrShafer** [linuxmint/xed#273]
Xed version 1.6.3
Distribution - Mint 18.3  64bit
**Issue**
Tabbed text does not preview, nor print properly

**Steps to reproduce**
Type:    abcd <tab> efghi <return>
Appears on screen:  abcd    efghi
Print preview & print paper.

**Other information**
Another issue mentioned that a "TAB" is simply four spaces.

**Comment by icarter09** [comment]
Linux Mint 19.2
xed v2.2.3

@MrShafer are you still experiencing this issue? I'm not seeing any problems with the Print preview.
