### ISSUE TITLE
Little feature request for xed

### ISSUE THREAD

**Issue by efezus** [linuxmint/xed#274]
```
 * Xed version 1.4.6
 * Distribution - Mint 18+
```
Hi! It would be nice if the opened "Highlight mode" window ( it is in the "View" menu) has instant autofocus on the top text field, which allows the text input for the desired programming language. 
![xed_autofocus_request](https://user-images.githubusercontent.com/15627077/51978241-f4576b00-2489-11e9-9ca0-254142fb39b5.png)
I always start typing, when I open this panel, and it is very frustrating to reach for the mouse and make an extra click :) 
Thanks indeed!
Regards: eFeS

**Comment by icarter09** [comment]
Duplicate of #332

**Comment by icarter09** [comment]
#347
