### ISSUE TITLE
Search for: actions search on the first character and delays acknowledging full request

### ISSUE THREAD

**Issue by davidpbrown** [linuxmint/xed#279]
```
 * Xed version (2.0.2)
 * Distribution - (Mint 19.1 Tessa)
```

[Search for:] jumps in too quick to seek all instances of that single character, which is a big easy stumbling point where the user is typing not copying and pasting a term to seek. It actions search on the first character and delays acknowledging full request, which on a large file can be 30secs and more. First or single character seeking should action only after search is prompted by enter or by a longer delay than small fraction of a second.. normal typing speed still stumbles over this. One second delay on the first character and fast live seek on more would work well. Worst example is if you mistakenly put a space as the first part of what you are wanting, a large file just stalls until its found all instances.

**Steps to reproduce**
Search for: single character like "e" or " " on a large file ~2MB.

**Expected behaviour**
Non-sticky acknowledging of more than just the first character.

**Other information**
xed is a great tool otherwise!

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/xed/issues/207
