### ISSUE TITLE
Two windows/tabs being opened with --wait option

### ISSUE THREAD

**Issue by olfek** [linuxmint/xed#284]
```
 * Xed version - 2.0.2
 * Distribution - Fedora 29
```

**Issue**

Xed opens two windows/tabs when using the `--wait` command line argument.

**Steps to reproduce**

1. Open terminal.
1. Enter `xed --wait`
1. Observe that two **tabs** have been opened.

 \+ Enter `xed --wait --new-window` and observe that two **windows** have been opened.

**Expected behaviour**

Only one tab/window should be opened when using the `--wait` option.

**Other information**

Unrelated - Documentation for `--wait` option is missing from command line help docs.

**Comment by icarter09** [comment]
Linux Mint 19.2
xed 2.2.3

Was able to reproduce all the issues mentioned in this ticket.
