### ISSUE TITLE
Gutter and First Line Character Space is too close

### ISSUE THREAD

**Issue by mitchellkrogza** [linuxmint/xed#303]
```
 * Xed version (2.0.2)
 * Distribution - (Linux manjaro-cinnamon 4.20.17-1-MANJARO)
```

**Issue**
Space between gutter and beginning of first character of line is too close

**Steps to reproduce**
Selecting first character on any line takes incredible skill as the cursor does not change until you are halfway over the first character and almost over the second character. Very frustrating behavior. Unsure if this is a XED issue or a Manjaro issue though.

**Expected behaviour**
See screengrab. Where mouse cursor is placed in this screenshot it should already change to normal cursor to be able to select text.
![IMG_20190525_140126](https://user-images.githubusercontent.com/9961541/58369104-1f147600-7ef6-11e9-8cd6-0455715c4ec8.jpg)

**Other information**

**Comment by JosephMcc** [comment]
This is a problem with your theme and how it is handling the the pane separator resize area: https://github.com/linuxmint/xed/issues/240

**Comment by mitchellkrogza** [comment]
Great thanks @JosephMcc for the confirmation, I had a sneaky suspicion it might actually be the theme. I will take it up with Manjaro. I love XED and keep up the good work.

**Comment by JosephMcc** [comment]
No problem. They just need to take a look at how the margins are set on pane separators. Many themes seem to push the margin that creates the grab area way to one side. While it's obvious in Xed in can be an issue in other applications as well.

**Comment by mitchellkrogza** [comment]
It actually explains my inability to select text with ease in a number of applications :smirk:
