### ISSUE TITLE
FR: text indenting?

### ISSUE THREAD

**Issue by digimeas** [linuxmint/xed#309]
```
 * Xed version (xed 2.02)
 * Distribution - (Mint 19, Cinnamon.)
```

Almost done :-)

**Issue**
I keep seeing it in the docs but not in the editor :-)

**Comment by collinss** [comment]
Could you please be more specific? Indenting seems to work for me when I hit tab, so I'm not sure what you're referring to.

**Comment by digimeas** [comment]
Beg pardon.  
I meant in/out-denting a whole block at once.

**Comment by collinss** [comment]
This already works fine for me. Select a block of text, hit tab, the entire block gets indented. Hit shift+tab and it gets un-indented again.

**Comment by digimeas** [comment]
It does indeed!  Thanks.

Perhaps that could be mentioned in the helpfile somewhere?

Thanks again
Doug

**Comment by JosephMcc** [comment]
Going to go ahead and close this.
