### ISSUE TITLE
Bug (I don't know whose): weird xed window-cursor interaction

### ISSUE THREAD

**Issue by digimeas** [linuxmint/xed#310]
```
 * Xed version (xed 2.02)
 * Distribution - (Mint 19, Cinnamon.)
```
Last one for a while :-)

**Issue**
When the editor window is maxed horizontally and then restored, the window winds up about 1-char down and to the right, but the cursor "thinks" the window was restored and inserts about 1 char up and to the left !?

Moving the window restores correct cursor behavior.

Haven't noticed it other than w/xed;  not firefox, nemo, terminal, etc.

**Steps to reproduce**
window to left edge of display (note where it is);
dbl-click right or left border to expand;
do it again to shrink (note that it's not where it was);
click somewhere in the text.

Enjoy!

**Comment by xenopeek** [comment]
Can't reproduce in Xed 2.2.3 on Linux Mint 19.2 Cinnamon.

Edge tiling and then expanding and shrinking leaves keeps the same line of the open file on the first row and the cursor (which I placed some lines down in the middle), while it may go out of view when the window is shrunk, stays on the same character.

**Comment by icarter09** [comment]
@digimeas are you still experiencing this issue?

**Comment by digimeas** [comment]
@icarter09 not any more. I'll close.
