### ISSUE TITLE
Xed randomely crashes while typing Malayalam Language

### ISSUE THREAD

**Issue by praveenp** [linuxmint/xed#32]
After typing some sentence in Malayalam Language using IBus, Xed crashes occasionally. I couldn't find any specific reason like - key sequence, number of characters etc, other than I am typing Malayalam (IBus mim file is a [custom made one](https://sites.google.com/site/mozhim17n/mozhi/ml-mozhi.mim.test.5)).

**Comment by clefebvre** [comment]
Can you produce a core dump or a trace?

**Comment by praveenp** [comment]
I tried `xed &>log.txt`, typed some 40 lines, played a little bit (copy pasting, spacing, tabing), when I tried to open a new tab, xed crashed. But 'log.txt' didn't trace anything. When I checked ~/.xsession-errors, I saw many occurrence of this error:
> (xed:3962): Pango-CRITICAL **: pango_layout_get_cursor_pos: assertion 'index >= 0 && index <= layout->length' failed 

I think it is possible to make xed crash by typing (or typing more :-().  Could you give specific commands.

**Comment by praveenp** [comment]
[output of xed &>log.txt](https://github.com/linuxmint/xed/files/424103/log.txt)
> **
> Gtk:ERROR:/build/gtk+3.0-6ZPWga/gtk+3.0-3.18.9/./gtk/gtktextsegment.c:195:_gtk_char_segment_new: assertion failed: (gtk_text_byte_begins_utf8_char (text))

This is new.

**Comment by JosephMcc** [comment]
Make sure you have the xed-dbg package installed and try running xed with gdb. If you can reproduce the crash it might give enough info to try and fix this. I'm closing this until we can get some more info.
