### ISSUE TITLE
Comment Block

### ISSUE THREAD

**Issue by charlie-ogier** [linuxmint/xed#324]
```
 * Xed version (2.2.3)
 * Distribution - (Mint 19.2)
```

**The Comment Block feature does not work**

**Select text > Ctrl+/ (or use menu option)**

**Highlighted text would be in a Comment block **

**Comment by xenopeek** [comment]
The comment block feature only works if a programming language was set or detected for the currently open file, and that programming language supports comment blocks. If the highlight mode in Xed's status bar shows "Plain Text", the comment block feature won't work. Click on that to set the programming language, if it wasn't detected for your file.

If it still doesn't work for you, please share which programming language you're using and if possible share a code snippet or (made up, just to demonstrate the issue) example file with which you have the issue.

**Comment by icarter09** [comment]
@charlie-ogier did @xenopeek comment help with your issue?
