### ISSUE TITLE
Focus numbering is not properly set up in the search and replace panel

### ISSUE THREAD

**Issue by mdindoffer** [linuxmint/xed#326]
```
 * xed - Version 2.2.3
 * Mint 19.2
```

**Issue**
Focus numbering is not properly set up for search and replace. 

**Steps to reproduce**
Open a document and open a search and replace panel (ctrl+h). Type in a word to `Search for` and press `<tab>`. The focus switches to the buttons next to the textfield. You need to press the `<tab>` key 4 times to move the focus into the `Replace with` textfield.

**Expected behaviour**
Focus would switch to the `Replace with` textfield.

**Comment by icarter09** [comment]
Was able to reproduce this issue.

Also confirmed that both VSC and Sublime Text perform this issue with as the **Expected behaviour** states.

**Comment by icarter09** [comment]
Closing this ticket. Comments for why it's being closed can be found on the closed PR #351.
