### ISSUE TITLE
Not an issue; small improvement!

### ISSUE THREAD

**Issue by skummer101** [linuxmint/xed#328]
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```
Could you add the key command for F5 to throw in the currently selected Date/Time format?

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
@skummer101 can you add an example of what you are looking for from this feature request? Thanks.

**Comment by JosephMcc** [comment]
Closing since the request for more info was never answered.
