### ISSUE TITLE
Allow mousewheel to scroll through open document tabs

### ISSUE THREAD

**Issue by calexil** [linuxmint/xed#33]
Feature Request: Allow mousewheel to scroll through open document tabs

currently drag to reposition works, but not scrolling with mwheel

would be intuitive and useful for managing large amounts of documents at the same time

**Comment by Shmoopty** [comment]
While not mentioned by @calexil , the tab interface becomes very prohibitive if more files are open than the tab widget can display.

Allowing the mousewheel to cycle through document tabs would be a familiar interface paradigm (e.g. see Chromium Browser) and would avoid ugly interface scenarios such as clicking `[>]` potentially dozens of times.

**Comment by calexil** [comment]
@Shmoopty exactly, I regularly have 8+ items open in xed and clicking the > over and over is getting tiresome

**Comment by calexil** [comment]
Bumping this request, the required bits can be found in pluma, as it had this feature from day one

**Comment by calexil** [comment]
any one who can point me in the right direction in pluma, Ill try and get this working

**Comment by JosephMcc** [comment]
It's implemented as part of this PR: https://github.com/linuxmint/xed/pull/68
This is a feature that I think died with the port to gtk3. It used to be a built in ability of GtkNotebook but isn't any longer.

**Comment by lsh-0** [comment]
is this feature impossible in gtk3?
