### ISSUE TITLE
Memory leak : unreleased memory after closing a document

### ISSUE THREAD

**Issue by Alayan-stk-2** [linuxmint/xed#330]
```
 * Xed version : 1.6.3
 * Distribution : Mint 18.3
```

**Issue**

Xed used about 2GB of RAM after I opened a 500MB file with it. Upon closing the file (but not the editor, as I had a few lightweight files still open), the memory usage stayed at 2GB. It is released only by quitting the editor.

**Steps to reproduce**

Open a lightweight text file, a massive text file, and close the massive text file.

I only tested on 1.6.3, but changelog doesn't mention any memory leak fix since 1.4.0

**Expected behaviour**

The memory associated with a file is released upon closing its tab in the editor.

I also wonder if using 2GB to open a 500MB file is normal ? Some kind of memory-heavy indexing is done maybe ?

**Comment by icarter09** [comment]
@Alayan-stk-2 whenever you upgrade Xed, can you re-test this issue? Thanks.

**Comment by JosephMcc** [comment]
Closing this since the response for more testing was never answered.

**Comment by Alayan-stk-2** [comment]
@JosephMcc Yeah, because upgrading Xed is highly unpractical here.

Users that will go through all the hooks to do testing for you are nice, but unless the bug is dependent on specific hardware or software combinations that make it hard/impossible to reproduce on other machines, the active collaboration of the bug reporter is not required. This bug is not dependent on specific hardware or software combination.

I gave "steps to reproduce". That's a nice stuff that allows developers to test themselves if they can confirm the issue on their own end, and that also allow them to test if an intended bugfix is working or not. In this case, the "steps to reproduce" are easy and quick to follow. The proper way to handle this is not to ask the user to test for you if the issue (still) exist, it's to do it yourself. If you can't reproduce the issue anymore, it's fine to close ; but if the issue still happen on your end, then you certainly shouldn't close.

If one user reports a software defect, it's very likely that many more users are affected by it but don't notice it (something like excessive RAM usage can cause performance losses without the defect being obvious to the end user) or don't report it (some are not affected badly enough, others just ditch the software). You shouldn't think of fixing an issue as making the one user who reported it happy (then, if he doesn't seem to care, why not close ?). You should think of it as improving the quality of your software, and you should care very much about its quality.

And I say all this as a contributor to an active open-source code base. If we just closed all the bug reports that can be tested on our end but where the original reporter can't be counted on to test again in the latest dev version, we'd shrink a lot the number of open issues. But this wouldn't help in making our software better, it would be harmful.

**Comment by olyerickson** [comment]
I've experienced similar problems with:
* xed 2.4.2
* Linux Mint 19.3
* MATE 

My problem with runaway memory is trivially easy to replicate: 
* Open new document in xed
* Start typing
* Continue typing without saving
* xed will slow.....down..... and your fan will actually kick on!
* Save out the file and everything is back to normal; normal speed, no fan!

I'm running on a Lenovo P51 with SSD; I'm not use to a text editor with nothing in it being s-l-o-w!
