### ISSUE TITLE
syntax highlighting - jump cursor to search box

### ISSUE THREAD

**Issue by alexanderdd** [linuxmint/xed#332]
```
 * Xed version (xed --version) 2.0.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Linux Mint 19.1 Cinnamon
```

**Issue**

**Steps to reproduce**
click on syntax highlighting button in bottom bar
you need to use the mouse to click into the search field

**Expected behaviour**
click on syntax highlighting button in bottom bar
cursor jumps to search field so you can start typing and hit enter to set the highlighting method, then the search bar closes

**Other information**

**Comment by icarter09** [comment]
Linux Mint 19.2 64bit
xed v2.2.3

Was not able to reproduce this issue. Performed the steps to reproduce and got the expected behaviour. Did not have to use the mouse to click into the search field. The focus was already on the search field.

**Comment by icarter09** [comment]
Just tested this out again. I'm noticing the issue when I first click/select the syntax highlighting, but after that the focus is on the search field. Been able to reproduce it several times now when I open Xed for a new session
