### ISSUE TITLE
Xed segfaults on launch if using a user modified ~/.config/xed/accels

### ISSUE THREAD

**Issue by smurphos** [linuxmint/xed#335]
```
 * Xed version 2.2.3
 * Distribution - Mint 19.2
```

**Issue**
After modifying an entry in `~/.config/xed/accels` xed will segfault on next launch

**Steps to reproduce**
Using a different text editor modify `~/.config/xed/accels` change for example

```
; (gtk_accel_path "<Actions>/XedWindowActions/DocumentsNextDocument" "<Primary><Alt>Page_Down")
```
```  
(gtk_accel_path "<Actions>/XedWindowActions/DocumentsNextDocument" "<Primary>Page_Down")
```
Launch xed - observe crash.

Terminal output

```
steve@steve-Inspiron-5580:~$ xed

(process:17873): GLib-CRITICAL **: 04:47:28.297: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(process:17873): GLib-CRITICAL **: 04:47:28.297: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(process:17873): Gdk-CRITICAL **: 04:47:28.297: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(process:17873): Gdk-CRITICAL **: 04:47:28.297: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(process:17873): Gdk-CRITICAL **: 04:47:28.297: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(process:17873): Gtk-CRITICAL **: 04:47:28.297: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(process:17873): GLib-CRITICAL **: 04:47:28.297: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(process:17873): GLib-CRITICAL **: 04:47:28.297: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(process:17873): GLib-CRITICAL **: 04:47:28.297: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(process:17873): GLib-CRITICAL **: 04:47:28.297: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Segmentation fault (core dumped)
```
Stack trace - https://termbin.com/ej4lx

**Expected behaviour**

Xed to launch with a modified accels file.

**Other information**

**Comment by collinss** [comment]
For one thing, it looks like you're missing a semicolon at the beginning of the line. For another, manually editing config files is something that will usually cause the program to fail one way or another if you get the syntax wrong - there's just too many things that could go wrong to account for them all. Finally, the code that actually reads the file is in Gtk itself, so we have absolutely no control over it, and therefore can't do anything about it. If you really want to see this addressed, you can try reporting it to them, but I doubt they'll do anything about it either for the reasons mentioned above.

**Comment by collinss** [comment]
Oh, and one more thing: closing xed reverts the file to it's previous state, so I don't think that file is intended to be edited manually anyway.

**Comment by smurphos** [comment]
Thanks @collinss - the removal of the semi-colon comes from my experience in modifying nemo's default accelerators. You need to remove the semi-colon to avoid whatever entry has been modified from being overwritten automatically by the application.

The main difference is for nemo the accels file is only accessible if you create the directory ~/.gnome2/accels first. Then nemo will dump it's accels file in there as ~/.gnome2/accels/nemo and editing in the way described works just fine. I guess given the legacy location the ability to to this may also be down to some legacy code still in nemo.

**Comment by collinss** [comment]
Ah, I didn't know that about the semi-colon. But yeah, either way, it's not something we control, and it's something that's likely not well-supported now considering the direction that Gnome has been heading for the last decade or so.
