### ISSUE TITLE
Shift + Ctrl + A and X shortcuts discard zero-padding

### ISSUE THREAD

**Issue by SebiderSushi** [linuxmint/xed#342]
```
 * Xed version (xed --version) 2.4.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3
```

**Issue**
Incrementing or decrementing a zero padded number removes any padding.

**Steps to reproduce**
1. Run xed
2. Enter any zero-padded number, e.g. `0000`, or `00048`
3. The cursor within the number, press `Shift + Ctrl + A` or `Shift + Ctrl + X`
4. Zero-padding is lost, i.e. results are e.g. `1` or `47` instead of `0001` of `00047` respectively

**Expected behaviour**
I think it could be a nifty addition if xed were to automatically detect zero-padding and keep it.
I guess recording the initial number of digits and padding the incremented/decremented number to the same length should be enough to make this happen.
If some use cases still require the zero-padding to be discarded, i think a preference toggle or another shortcut like `Shift + Ctrl + Alt + A/X` could be used. Of course, that would reduce simplicity and add clutter.

**Other information**

**Comment by icarter09** [comment]
Xec v2.4.2
Mint 19.3 
64bit

Was able to reproduce this issue with the steps provided.

**Comment by JosephMcc** [comment]
Doing a bit of digging, this is a bug/limitation of gtksourceview that is the library we use that provides this functionality.
