### ISSUE TITLE
File>Open: Cannot paste full path to file

### ISSUE THREAD

**Issue by bernd-wechner** [linuxmint/xed#35]
Am I blind or is this not possible? Sorry to sound critical but that is a show stopper and I'm back to gedit. Surely there's a standard to open dialog boxes? And the ability to type the full path of a file to paste one in is paramount.

**Comment by JosephMcc** [comment]
Just did a quick test. typed the following path in the terminal `/usr/share/cinnamon/js/ui/windowManager.js`. I highlighted the text, in xed used File->Open to bring up the dialog. Middle click pasted in the file open dialog that popped up and worked fine.

**Comment by bernd-wechner** [comment]
Thanks for the prompt reply. But I'm not following. Where in the File->Open dialog do you paste? 

Middle click doesn't paste here (Mint 18) so not sure how that works at your end. But CTRL+V sure does and I don't see anywhere on the File->Open dialog to paste.

I'll post a screenshot if it helps, but conversely I think it would help me if you posted one of what you were seeing. There is no box to type in on my dialog, it's akin to a type of open dialog rarely seen on Windows that pains me there, where you can only open a file by navigating to it in the dialog box.

**Comment by JosephMcc** [comment]
Ah, you can use Ctrl + L over the pathbar at the top of the file chooser dialog. This will change the pathbar to an input entry, the same as in Nemo. I know not the most intuitive but that is not our doing. That is just the way it works in a GtkFileChooser dialog now. You would see the same in gedit.

**Comment by bernd-wechner** [comment]
Thanks enormously Joseph! Indeed, seems you're right! I was using Mint 17.3 and gedit there used a more customary open dialog where to the left of the navigation breadcrumbs was a button I could click to enter the path. 

Methinks this is a rather nasty bug in the GtkFileChooser alas, but not an issue with xed as you note because indeed I tried gedit and the latest build on Mint 18 that is packaged is the same and it was not the transition from gedit to xed that caused it but an upgrade in GTK it seems. 

So this can close.

**Comment by bernd-wechner** [comment]
Turns out typing / on the breadcrumbs works too and I'm not the first to struggle with this:

https://bugzilla.gnome.org/show_bug.cgi?id=759073

**Comment by JosephMcc** [comment]
> Turns out typing / on the breadcrumbs works too

Learn something new every day.

**Comment by ByteHazard** [comment]
I also ran into this problem, the workaround is not intuitive and not discoverable. Why is this bug marked closed? If this change was the result of an intentional GNOME developer design choice, how can we ever expect this to get fixed? The problem persists after 2 years after first reported...

I request to re-open ticket!

**Comment by JosephMcc** [comment]
It's not going to reopened here. This isn't our doing or under our control. The issue needs to be raised upstream with Gtk.

**Comment by ByteHazard** [comment]
Ok. I would like to suggest adding a label for issues caused by upstream bugs, such as this one, for clarity and guidance. I would suggest "pending upstream", or some such, if a label for this purpose does not yet exist.
