### ISSUE TITLE
No reference to autosave path

### ISSUE THREAD

**Issue by DeafScribe** [linuxmint/xed#353]
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**

Autosave toggle available in preferences, needs human-readable pointer to directory used for autosave.

**Steps to reproduce**
Search preferences, help and Google for info on autosave behavior.

**Expected behaviour**
Info for such a critical backup path should be easily accessible.

**Other information**

**Comment by JosephMcc** [comment]
The behavior is pretty straightforward. If you have previously saved the file, it simply overwrites the existing saved file. If it's a file you have never saved, it does nothing.

**Comment by stefan123t** [comment]
@JosephMcc thanks for mentioning that it does not autosave Unnamed documents to some Temp folder. Along with #226 on restoring tabs people were asking for some auto-save functionality for Unsaved tabs (like in Notepad++ ) too. With system failures in mind, having such a backup of unsaved files would be appreciated. I believe vim and others call it a swap file.
Is that something you would reopen this Issue for or rather have a new issue ?
Kind regards, Stefan
