### ISSUE TITLE
Quick acess to text wrap controls

### ISSUE THREAD

**Issue by JollyWizard** [linuxmint/xed#36]
I would like quick access to the word wrap controls.  The preferences dialog method is too round-about for a task that sets the readability of the document.  

In Window's Notepad, there is a toggle in the menu for text wrap.  This is the only feature the program has, and it nails it. [Image](http://i.technet.microsoft.com/dynimg/IC308403.jpg)

In gedit, they finally added a similar the feature in January 2016 as a hidden pop-up (like with the tab options). I find it oddly placed, but it would do the trick.  They also brought out the toggles for line numbers, which is nice. [Image](http://askubuntu.com/a/764611)

It also think it would be a good candidate for the right-click menu.

**Comment by JosephMcc** [comment]
I would just put it in the "View" menu like some other text editors do. I do like having it in the prefs though so I can set the behavior I typically want. I would only use the menu to override that for a particular file.

**Comment by doredus** [comment]
Toggling text wrapping is a really useful feature that I use a lot and, at the moment, xed has me regressed to Edit > Preferences > Enable text wrapping checked/unchecked > Close, i.e. 4 clicks!

I was previously using the one-click TextWrap py extension in Gedit but, of course, this won't work with xed.

I agree with JosephMcc that we wouldn't want to remove the default behavior from the prefs, however, putting it in the View menu is still 2 clicks and who's got that kind of time?

I'd like a visible icon like TextWrap py (single click for when you're on your pointing device) PLUS a keyboard shortcut for when you're typing (Ctrl+R maybe).
