### ISSUE TITLE
Feature: custom number of recent files  & allow most recent directories

### ISSUE THREAD

**Issue by artofit** [linuxmint/xed#371]
Xed 2.4.2

Currently,

- in Edit>Preferences there is no option to define the number of recent files.
- Xed, has a history of last 5 files.

Wish:

- A parameter to allow a history of 0-10 last files. 
- A parameter to allow a history of 0-10 last directories.

more than last files, one might want the "favourite" directories, defined by the last usage of files.
For example if one used:
/dir1/dir2/dir3/filename
then Xed would retain
/dir1/dir2/dir3/

Thanks

**Comment by JosephMcc** [comment]
There actually is a preference for this. It just isn't exposed in the settings UI. You can use something like dconf-editor to set it. It's org.x.editor.preferences.ui max-recents.

You can also set it with the terminal using `gsettings set org.x.editor.preferences.ui max-recents 10`

**Comment by artofit** [comment]
Indeed, in terminal
`gsettings set org.x.editor.preferences.ui max-recents 10`
does produce the history of the last 10 files.

Since, it's already implemented, it would be nice to add this feature in the UI, or at least mention it in the help the mean time, but I think it's more trouble some than directly adding this to the UI.

What about a parameter to allow a history of 0-10 last directories?

Thanks

**Comment by clefebvre** [comment]
Sorry I'm late to the party.

You can list all settings with `gsettings list-recursively org.x.editor`.

Some settings are there for tuning the app but it's a bit overkill to expose them to the UI.

That said, 5 is very small, especially when we consider that the items are listed in their own Gtk.Menu widget. We've got room to double that default.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/xed/commit/f2f68fc915242a7976288426989b09a4e6a4226f
https://github.com/linuxmint/xed/commit/d59a067668e765f5e19e724192440ee1ce1b8c74
