### ISSUE TITLE
Sudo as root - improper?

### ISSUE THREAD

**Issue by jlj2** [linuxmint/xed#373]
*Xed version 2.4.2
Distribution - Calculate Linux 20.0 (Gentoo derivative)*

Your [README.md](https://github.com/linuxmint/xed) installation instructions for general Linux users currently include:

```
      # sudo ninja install -v -C build
```

1. Isn't the use of sudo in a root shell redundant?

2. Couldn't that mess some environment variables and introduce a vulnerability(-ies)?  

3. If so, please revise your instructions for debian-based systems also, which currently include:-
```
      # sudo dpkg -i *.deb
```
and
```
      # sudo ninja -C debian/build install 

```
Thank you.

**Comment by leigh123linux** [comment]
You need root permissions to install the files

**Comment by jlj2** [comment]
@leigh123linux, when `#` appears as a prompt, don't you think that readers are being expected to act as root?

The instructions are already prompting your readers to take on root permissions, therefore.

My original questions still stand, therefore, including the possibility of vulnerability introductions.  Yet, you have closed the issue.

**Comment by leigh123linux** [comment]
Your question is irreverent unless the user installs to their /home directory.
