### ISSUE TITLE
How to build xed?

### ISSUE THREAD

**Issue by dev-abir** [linuxmint/xed#374]
```
 * Xed version: 2.4.2
 * Distribution: Mint 19.3
```

**Issue**
Please help me to understand [this](https://github.com/linuxmint/xed#installation)(the installation/build steps)

Where is 'configure' script?, I assume you mean the commented line below 'configure' script?(i.e., # meson --prefix=/usr build)

Okay I did so, but it is telling some native dependency not found. At first it asked for `libxml`, I installed that, then `gtksourceview-3.0`. I installed that, then `xapp`.

You should have created 1 line command or a script to install all these dependencies.

Another thing... I noticed that you ported your build system to meson, but the package `linux-mint-dev-tools` doesn't install meson, instead it installs autoconf(you may have used this earlier)......

**Comment by jlj2** [comment]
Hi @dev-abir!
I'm not using Mint, so your build programs may be different;  I'm using Calculate Linux (which is Gentoo but with the desktop setup and with a lot of packages provided as binaries).  In case it could help you, several build packages had to be installed also:-

`libpeas xapp gspell dconf-editor
`
Check whether those are installed, and a package such as `meson` perhaps.  Also, check whether to use sudo or not [as root](https://github.com/linuxmint/xed/issues/373).
I hope this helps.

**Comment by JosephMcc** [comment]
> Where is 'configure' script?, I assume you mean the commented line below 'configure' script?(i.e., # meson --prefix=/usr build)

Yes. That's exactly what it means.

> You should have created 1 line command or a script to install all these dependencies.

We can't really do that since installing these will vary depending on the distribution you are running on and what it uses for package management.
