### ISSUE TITLE
Massive search and replace on same line is slow

### ISSUE THREAD

**Issue by christophra** [linuxmint/xed#376]
```
 * Xed 1.6.3
 * Mint 18.3
```

**Issue**
Doing a "Replace All" which matches many times on the same line seems very slow, over 4 minutes for 3000 replacements.

**Steps to reproduce**
I have a file with ~3000 words separated by spaces. (I swear, there was a real-life reason...)
Open search and replace dialogue.
Type "Search for:" whitespace
Type "Replace with:" anything
Press "Replace All"
=> xed process takes 100% CPU for >4 minutes to complete the operation.

**Expected behaviour**
The operation finishes in <1 second like when I use vim to perform the same action.

**Other information**
I've attached my example file. [xed_replacing.txt](https://github.com/linuxmint/xed/files/4655542/xed_replacing.txt)

**Comment by icarter09** [comment]
Xed v2.6.0
Mint 19.3

I tried used the example file and performed the replace all using the steps listed. While the xed process did take 100% CPU, it only took 20 seconds to complete. 

@christophra can you please test this out again once you have upgraded xed? Thanks.

**Comment by JosephMcc** [comment]
This is a known issue. The problem is in GtkSourceView, the library we use to provide a lot of Xed's functionality. It isn't something we really have control over.
