### ISSUE TITLE
Feature Request: Highlight Mode to be put in the toolbar

### ISSUE THREAD

**Issue by samsaraswheel** [linuxmint/xed#378]
Hello, 

I would like to request the Highlight Mode to be also put as a typable drop down in the toolbar so you can see what mode it currently is in and have quick access to change.

Also would be nice on the realm of distant possibility would be an highlight mode editor as a plugin to be able to customize the configs of each Highlight Mode or add your own. 

Thanks for the good work.
Cheers

**Comment by JosephMcc** [comment]
Thank you for the request. The highlight mode is already shown in the windows statusbar. Not sure there is a need for it to be in the toolbar as well but will keep it in mind for the future.
