### ISSUE TITLE
Feature Request : adding groff syntax to highlight mode

### ISSUE THREAD

**Issue by EmperorUdan** [linuxmint/xed#382]
Hello,

Would it be possible to add the syntax of the [groff](https://en.wikipedia.org/wiki/Groff_(software)) typesetting system in highlight mode ?

Thanks for the good work.
Cheers

**Comment by JosephMcc** [comment]
Someone would need to create the language file for it. And Xed pulls these from gtksourceview. So it would be best to submit this to them.
