### ISSUE TITLE
High CPU utilization and application crash

### ISSUE THREAD

**Issue by rarsa69** [linuxmint/xed#384]
```
 * Xed version : 2.4.2
 * Distribution - : LInux Mint 19.3 fully updated
```

**Issue**
As I start typing, CPU shoots up to over 80%, If I continue typing the application starts responding very slowly until it suddenly closes.

Please note that I have a 6 cores system, so using 80% of CPU is almost a full core.

**Steps to reproduce**
Install Chinese support using fcitx
I used these instructions:
https://forums.linuxmint.com/viewtopic.php?t=264802

Open xed and start typing, the faster you type, the faster you get to the error. I have been typing in English, not even in Chinese
A sure way to get the error fast is to copy a portion of the text and Ctr-V it very fast.

However, I've experienced this problem just editing a small configuration file or taking quick notes

**Expected behaviour**
I expect the processor not to use that much CPU and not to crash

**Other information**
A) I don't see the problem if I uninstall fcitx and Chinese support

B) If I run from the command line, eventually it crashes with the following error

user@my-desktop:~$ xed

(xed:26305): Gdk-ERROR **: 17:07:07.721: The program 'xed' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadLength (poly request too large or internal Xlib length erro'.
  (Details: serial 530656 error_code 16 request_code 18 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
user@my-desktop:~$

**Comment by icarter09** [comment]
@rarsa69 do you get the same issues when using gedit?

**Comment by rarsa69** [comment]
> @rarsa69 do you get the same issues when using gedit?

I haven't tried in gedit. recently I reinstalled fcitx and xed seems to be working well. Maybe there was an update that fixed this. I would suggest closing the issue and reopening if I (or someone else) experience it again.
