### ISSUE TITLE
Feature Request: Editor Panes

### ISSUE THREAD

**Issue by tkitynski** [linuxmint/xed#386]
One can open new editor tab and this is great. But it's is impossible to see content of both tabs at once — unless you undock the tab and make separate window out of it. But as there is already side panel, it would be great to have two (or even more) editor panes in the same window. It would be just great, if one can drag the tab to upper/bottom half of current editor pane to split it vertically or to left/right half of the pane to split it horizontally. Similarly as Atom or Eclipse can do. I miss it very much! 8)
Greetings
TK

**Comment by JosephMcc** [comment]
Thank you for the suggestion. We've discussed this before and decided not to implement it for now. Will keep it in mind for the future though.
