### ISSUE TITLE
Keep the same level of indentation when wrapping lines.

### ISSUE THREAD

**Issue by gilbertohasnofb** [linuxmint/xed#387]
```
 * Xed version: 1.6.3
 * Distribution: Linux Mint 18.3
```

**Issue**

Long lines will wrap without respecting the indentation level. E.g.

![image](https://user-images.githubusercontent.com/5700795/85305690-5660a800-b4a5-11ea-8aff-522600807de5.png)

In many other editors, you have the option (often on by default) of showing wrapped lines with the same level of indentation, something like this (edited image):

![image](https://user-images.githubusercontent.com/5700795/85305861-8c9e2780-b4a5-11ea-9636-1a09e136da4f.png)

This just affects how the text is displayed.

**Comment by JosephMcc** [comment]
I don't really think this is currently possible. The GtkSourceView library we use doesn't seem to support doing this.
