### ISSUE TITLE
Xed is no longer remembering window position

### ISSUE THREAD

**Issue by calexil** [linuxmint/xed#389]
```
 * Xed version (2.6.0)
 * Distribution - (Mint 19.2...)
```

**Issue**
Xed is no longer remembering window position

**Steps to reproduce**
open xed, move it somewhere, close it... open it again... window is always centered

**Expected behaviour**
open xed, move it somewhere, close it... open it again...window opens where it was last

**Other information**

**Comment by JosephMcc** [comment]
I don't remember that ever being the case. What version of xed was this working in?

**Comment by calexil** [comment]
whats the default on 18.3, cause that one works fine

**Comment by JosephMcc** [comment]
Just to make sure I wasn't crazy, I looked back through the changes we've made. Xed never had the code in place to save and restore it's window position. We currently have no plans to implement this functionality either.
