### ISSUE TITLE
No way to turn off comment blocks

### ISSUE THREAD

**Issue by netjerykhet** [linuxmint/xed#391]
```
 * Xed version (2.6.2)
 * Distribution - (Mint 20)
```

**Issue**
Xed doesn't understand different programming languages, yet it has options for programming language-specific comment styles that cannot be turned off. This presents major issues when trying to use it as a plain text editor, for example, to make notes about the command line. If a line is written with a shell globbing asterix, all of the subsequent text appears as if it is commented out.

**Steps to reproduce**
In an empty document, paste a number of paragraphs of lorem ipsum or any other text that is not any kind of program code. Insert a blank line at the top of the document and enter:

`rm -v ~/.local/share/keyrings/*.keyring`

All of the text following '/*' is now displayed as comments in program code.

**Expected behaviour**
Nothing completely unexpected and surprising happens, i.e. the text following '/*' shoulld not be interpreted as a code comment.

**Other information**
Not every user of Xed is a programmer. Since Xed cannot tell if I'm writing notes or coding in C++, R, bash shell, FORTRAN, Algol or COBOL, i.e. it does not understand coding styles, it should not assume I'm programming in Javascript, C or C++. In addition, "quoted text" is displayed in some unknown coding style, as are decimal numbers such as 1.2, and words such as "default" become bold text in a different colour. Xed appears to be a tool for programmers, not a plain text editor suitable for general. use

**Comment by icarter09** [comment]
Looks like when I pasted the one line of text, it defaulted the `Highlight Mode` to C. The default should be `Plain Text`. Once you switch it back over to `Plain Text`, the issue goes away. I'll look into why Xed is taking it upon itself to switch the highlight mode selection.

**Comment by icarter09** [comment]
Xed v2.6.2
Mint 20 Cinnamon

@netjerykhet I believe the reason it defaulted to C for me the first time was due to me having recently been working on a C file in Xed prior to debugging this ticket. Since then, I'm not able to duplicate this issue. Are you still experiencing the issue?

**Comment by JosephMcc** [comment]
This isn't really a bug. There is a menu at the bottom of the window that allows you to set the syntax type. Just make sure it's set to Plain Text.
