### ISSUE TITLE
changing font size with ctrl+/ctrl- no longer works

### ISSUE THREAD

**Issue by waynongithub** [linuxmint/xed#392]
```
 * Xed version (1.6.3)
 * Distribution - (Mint 18.3 mate, US keyboard)
```

**Issue**
Changing font size with ctrl+/ctrl- no longer works. It used to work, but now ctrl-/ctrl+ only prints the characters - or = or + (depending on whether i use ctrl= or ctrl-shft=). Resetting default size with ctrl-0 also stopped working.

**Steps to reproduce**
type some text and change font size with the shortcut keys.

**Expected behaviour**

**Other information**
It doesn't seem to be a problem with my keyboard, because changing font size with ctrl-= and ctrl-- still works in Kate.

**Comment by icarter09** [comment]
Xed v2.6.2
Mint 20 Cinnamon

I'm not able to duplicate this issue. Keys are still mapped to font size increase/decrease. Once you update your version of xed, you shouldn't have the issue. If you do experience, then please reopen this ticket or create a new one. Thanks.
