### ISSUE TITLE
Incomplete JavaScript syntax highlighting

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [linuxmint/xed#395]
* Xed 2.6.2
 * Fedora 32

## Issue

JavaScript syntax highlighting is incomplete; it breaks in some corner cases

## Steps to reproduce

1. Open ~~[this file](https://gitlab.gnome.org/GNOME/gtksourceview/uploads/bf18f1a3a8a303372b44519e89d6e8d6/demo.js)~~ [*this* file](#issuecomment-673838972)
2. Scroll down to line 42
3. View subsequent lines

## Expected behaviour

JavaScript code is highlighted as it's parsed in e.g. a web browser

## Other information

This [is fixed upstream](https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/153#note_886926):

> … I'm not able to reproduce this issue with the current version.

> …\[gtksourceview3\] is in deep freeze. Applications such as `xed` have had ample time to move to GtkSourceView 4.x at this point (especially since it's mostly just a pkg-config name change with only a couple of ABI changes).

> \[upstream Maintainer\] added `Obsolete` label

> \[upstream Maintainer\] closed

**Comment by JamesTheAwesomeDude** [comment]
I'm opening this as a new issue because it seems more expansive than #23 (though, I'm not sure why that one didn't get re-opened in June '17 at the time when it _was_ re-validated)

**Comment by icarter09** [comment]
@JamesTheAwesomeDude can you attach the file or provide one that shows the issue? Looks like the link to the provided file in the "steps to reproduce" is no longer available. Thanks.

**Comment by JamesTheAwesomeDude** [comment]
@icarter09 

ah—I did not expect GitLab to have link-rot!

````js
x=([
8,7,8
]);
y=new Array();

x.forEach(k=>{
	y.push(
`<test>${
navigator.geolocation?` <geo>${navigator.userAgent}</geo>`:''}
</test>
`
	);
});
console.log(y.join('\n'));
````

Try this one—observe how GitHub and the browser parse it (which is, allegedly, how gtksourceview4 parses it)—and compare the highlighting of that last line to Xed's

**Comment by icarter09** [comment]
@JamesTheAwesomeDude appreciate the sample code. Looks like gedit is highlighting it correctly, while xed is not.
