### ISSUE TITLE
Request: Option to open existing documents in new windows by default

### ISSUE THREAD

**Issue by tikajr** [linuxmint/xed#397]
```
 * Xed version (xed --version) 2.4.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.2
```

**Issue**

When I open text files from the file browser, it sends them to Xed and wacks them in a new tab, but I would prefer if it would send them to a new window instead.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by tikajr** [comment]
I have development experience but am new to open source. If i can find time I'll have a stab at doing this myself

**Comment by JosephMcc** [comment]
This is the same as https://github.com/linuxmint/xed/issues/375
