### ISSUE TITLE
Goto line (Ctrl+I)

### ISSUE THREAD

**Issue by ReleaseStandard** [linuxmint/xed#408]
```
xed - Version 2.4.2
LinuxMint 19.3 (tricia)
```

**Issue**
Issue is on "goto line function"

**Steps to reproduce**
Open xed on a file (ex: empty file)
Input Ctrl+I
Input a big number of lines like
  1000000000000
  1000000000000000

**Expected behaviour**
The goto line function will go to line number 1

**Other information**

**Comment by JosephMcc** [comment]
Thank you for the suggestion but I think the current behavior is correct. It shows the error color in the situation you show.

**Comment by ReleaseStandard** [comment]
I have miss-explained, the behaviour that I have is below :
A : goto line 1, box is normal color
B : goto last line, box is red
            ... only As ...
- ctrl + I 1000000000000            -> A
- ctrl + I 10000000000000          -> B
- ctrl + I 100000000000000        -> B
- ctrl + I 1000000000000000      -> B
- ctrl + I 10000000000000000    -> A
- ctrl + I 100000000000000000  -> B
- ctrl + I 1000000000000000000 -> A
                ... then only As ...

So as you see some time it tooks to the first line some time to the last line.

**Comment by JosephMcc** [comment]
Ah ok. Thanks for the follow up. I'll try to investigate some more at some point.
