### ISSUE TITLE
mint cinnamon 18 19 20 64 bit TAB key doesn't work by default on Text editor

### ISSUE THREAD

**Issue by drhazamakuroo** [linuxmint/xed#411]
```
 * Xed version (xed --version)
 * Distribution - (Mint 20)
```

**Issue**

TAB key doesn't work by default on Text editor

**Steps to reproduce**

**Expected behaviour**
I digit TAB key and the corrispondent tabulation is written.

**Other information**
from linux cinnamon 17.1 onwards, I have noticed that if you use the text editor and type the TAB key, it is considered as 4 consecutive empty spaces as those that result after pressing the space bar 4 times, while it should be considered as a single long blank. It is possible to click in the preferences on the Edit menu and turn OFF "use spaces instead of tabs".
Up to cinnamon 17.1 Xed - it is possible to check the box in front of the phrase "insert spaces instead of tabs", otherwise the TAB key remains functional. In my opinion it would have been correct - from a purely logical point of view - to leave this setting also in subsequent versions of xed as the TAB key is part of the normal keyboard and therefore should be enabled by default instead of being disabled by default.

**Comment by simounn** [comment]
This is a user configurable setting. The default setting is probably fine for most users, and if not, it's only a few clicks to customize. You can't please everyone all the time. :-)

**Comment by JosephMcc** [comment]
The only thing that changed was the default setting. As noted above it's still easily changed by the user to their preference.

**Comment by drhazamakuroo** [comment]
I still believe it is more correct that a key on the keyboard (like the TAB in this specific case) should be enabled by default. And if you use linux with pendrive you are forced to change the setting every single time you turn on the PC.

    Il lunedì 2 novembre 2020, 04:21:34 UTC, JosephMcc <notifications@github.com> ha scritto:  
 
 


The only thing that changed was the default setting. As noted above it's still easily changed by the user to their preference.
