### ISSUE TITLE
Feature request : Add syntax highlighting for groff

### ISSUE THREAD

**Issue by EmperorUdan** [linuxmint/xed#413]
Would it be possible to add syntax highlighting for the groff typesetting system ? Xed supports a lot of languages, including Latex, but not groff. It would be really appreciated because I like xed and use groff on a daily basis.

**Comment by JosephMcc** [comment]
Xed uses other libraries to provide syntax highlighting. Requests to add a language should go here: https://gitlab.gnome.org/GNOME/gtksourceview
