### ISSUE TITLE
Syntax highlighting not working for case statement

### ISSUE THREAD

**Issue by simounn** [linuxmint/xed#415]
```
 * Xed version 2.2.3
 * Distribution - Mint 19.2
```

**Issue**
It seems a bracket is breaking the syntax highlighting.

**Steps to reproduce**
Put this code into xed with highlight mode as "sh"
```
value=1
var=$value")"
echo "Above is fine"
case $value in
  1)
    var=$value")"
    echo "Highlighting breaks by same line in the case statement"
  ;;
esac
# Example comment not colored right
```

**Expected behaviour**
Replace the ")" with any character and syntax highlighting works

**Other information**
I tried to compile latest xed but failed. Sorry if this is fixed in the latest version.

**Comment by simounn** [comment]
![error](https://user-images.githubusercontent.com/72730470/95721633-9ea70e80-0cbe-11eb-8053-436bd625998a.png)

Screenshot added

**Comment by JosephMcc** [comment]
Tested this with git master and it seems to be fixed by using the newer GtkSourceView version. This fix should come in the next Xed release.
