### ISSUE TITLE
Xed 2.6.2 does not remember the Autocheck Spelling setting on Linux Mint 20 Cinnamon.

### ISSUE THREAD

**Issue by Ne2hpmbw** [linuxmint/xed#416]
```
 * Xed version (xed --version): Xed 2.6.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint 20 Cinnamon
```

**Issue**
Xed 2.6.2 does not remember the Autocheck Spelling setting on Linux Mint 20 Cinnamon.

**Steps to reproduce**
Set the option (Tools and check Autocheck Spelling). Use the editor in any way then close the editor.

Re-open the editor and the option will be UNchecked.

**Expected behaviour**
The setting selection should be retained after closing and reopening the application.

**Other information**

**Comment by JosephMcc** [comment]
Go to Edit->Preferences and on the Plugins page select the Spell Checker plugin. In the Preferences choose Always.
