### ISSUE TITLE
overview map is not correct

### ISSUE THREAD

**Issue by xiriloj-installlinux** [linuxmint/xed#418]
```
 * Xed version 1.8.3
 * Distribution - Linux Mint 19 Cinnamon
```

**Issue**
![image](https://user-images.githubusercontent.com/56113470/97788041-15487500-1bb6-11eb-8e2a-823ccd536186.png)
The overview map is not correct. Im viewing the end of the file. Line 7777 is the last one.
In this screenshot the editor is just half of my screen. If its fullscreen, its just one line incorrect.
However in this screengif it doesnt matter if the editor is fullscreen or not.
![Peek 2020-10-31 20-22](https://user-images.githubusercontent.com/56113470/97788136-d961df80-1bb6-11eb-8ecb-a9bbd51becaf.gif)

![Peek 2020-10-31 20-30](https://user-images.githubusercontent.com/56113470/97788273-111d5700-1bb8-11eb-9d1c-e61dd7daf40c.gif)

![image](https://user-images.githubusercontent.com/56113470/97788477-8c333d00-1bb9-11eb-9f8d-7dba639b3104.png)
If I open [test.txt](https://github.com/linuxmint/xed/files/5469715/test.txt) , its correct, after I scroll.

**Expected behaviour**
It should be at the bottom in screenshot 1
It should move with the cursor in screengif 2

**Steps to reproduce**
First Screenshot:
I used https://en.wikipedia.org/wiki/Lorem_ipsum but the problem is not with any text, as you can see in screengif 3. The problem also occurs with other wiki articels and my personal todo.md file.

Second & 3 Screengif:
72 lines with a + 1 empty line
Here is the file I used: [test.txt](https://github.com/linuxmint/xed/files/5469705/test.txt)

**Comment by JosephMcc** [comment]
Do you have the overlay scrollbars turned off?

**Comment by John-Rodriguez-Git** [comment]
I tested something with xed 2.8.4 on NixOS:

https://user-images.githubusercontent.com/87267596/125209066-a53ad480-e296-11eb-8c45-2760d4038628.mp4

What do you mean with overlay scrollbars?

**Comment by JosephMcc** [comment]
I can see in your video that you don't have them disabled. There are some known issues upstream with the Overview Map. This is something we don't really control.
