### ISSUE TITLE
Wordwrap wraps closes tags with 'split words over two lines' disabled

### ISSUE THREAD

**Issue by myfirstnameispaul** [linuxmint/xed#421]
```
 * Xed version (xed --2.6.2)
 * Distribution - (Mint 20)
```

**Issue**
Wordwrap wraps tags with 'split words over two lines' disabled.

**Steps to reproduce**
Open xed
Type text string and move window to size that places `</tagged>` close enough to right margin to wrap it.

Original text string:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, \<tagged>sed\</tagged> do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Actual output:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, \<tagged>sed</-
> tagged> do eiusmod tempor incididunt ut labore et dolore magna aliqua.

**Expected behaviour**
Expected output:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, \<tagged>sed
> \</tagged> do eiusmod tempor incididunt ut labore et dolore magna aliqua.

**Other information**
The preferences option 'Split words over two lines' is not enabled.

**Comment by JosephMcc** [comment]
This problem needs to be reported upstream if it's not already: https://gitlab.gnome.org/GNOME/gtksourceview
