### ISSUE TITLE
Option to disable dash to indicate intra-'word' wrapping

### ISSUE THREAD

**Issue by jslater89** [linuxmint/xed#422]
```
 * Xed version 2.6.2
 * Distribution - Mint 20
```

**Issue**
The dash indicating a break in the middle of a word shows up in contexts where it's less than ideal, like long paths:

![Selection_005](https://user-images.githubusercontent.com/7966632/99138083-25bc0f00-25fc-11eb-98b4-71927c864676.png)

It would be nice to have a way to turn the marker off, or at the very least to select a different character for it (such as ↲).

**Steps to reproduce**
Enter the text above into a sufficiently narrow xed window.

**Expected behaviour**
n/a.

**Other information**
It only seems to happen when a long string of text is broken up by certain characters, including /, -, |, and — (emdash). (I didn't test others.)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/xed/issues/421

**Comment by ronspain** [comment]
This is dumb. I need to find a new editor.
