### ISSUE TITLE
Regex-Replace: Does not work with (double)backslash

### ISSUE THREAD

**Issue by Semnodime** [linuxmint/xed#423]
```
 * xed - Version 2.6.2
 * Linux Mint 20
```

**Issue**
Bug 1:
Replace with regex does not work with (double)backslash

Bug 2:
Instead, bug_1 will sometimes trigger an error message, "<searchtext> not found" but I currently cannot reproduce this second bug)

**Steps to reproduce**
1. Create a new file
1. Write text that will match the regular expression (e.g. see screenshot)
1. Search for your match and replace it with `\\`

**Expected behaviour**
Replace your match with a single backslash `\`

**Other information**
![image](https://user-images.githubusercontent.com/19511852/99159795-537a8400-26e0-11eb-826f-28a7f4814693.png)

**Comment by JosephMcc** [comment]
We rely on GtkSourceView for this. Please open the issue here: https://gitlab.gnome.org/GNOME/gtksourceview/-/issues
We are currently using version 4.6.0 in Mint20

**Comment by rondevous** [comment]
This issue was opened at https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/169.

> [ Christian Hergert @chergert]
> If you're going to re-open this, you must absolutely provide me a test case in C that I can use in GSV to ensure correctness.

If anyone can, please do. I want this fixed as well, but I don't know C programming.

**Comment by rondevous** [comment]
This issue was re-opened at https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/169.

The maintainer said to give a test case.
> [ Christian Hergert @chergert]:
> If you're going to re-open this, you must absolutely provide me a test case in C that I can use in GSV to ensure correctness.

I want this fixed, but I lack the know-how.
