### ISSUE TITLE
Where xed stores configuration ?

### ISSUE THREAD

**Issue by killajoe** [linuxmint/xed#425]
* Xed version 2.6.2
 * Distribution - Archbased (EndeavourOS)
**Issue**
* I can not find a way to store backup and restore setting for xed, may my question is dump, but I do not see any config under `~/.config/xed` or elsewhere under home directory.
I do want to ship xed preinstalled with some setting presetted, and I do not get how to save the config.

So how are configurations stored?

i see I need dconf to dump them and then restore from that...

```
[org/x/editor/plugins]
active-plugins=['filebrowser', 'joinlines', 'wordcompletion', 'taglist', 'open-uri-context-menu', 'docinfo', 'time', 'modelines', 'sort', 'spell', 'textsize']

[org/x/editor/preferences/editor]
bracket-matching=false
display-line-numbers=true
prefer-dark-theme=true
scheme='cobalt'
wrap-mode='none'
```

**Comment by JosephMcc** [comment]
Yes. The settings are all stored as gsettings keys. I'm going to close this since it seems you figured it out.

**Comment by FaramosCZ** [comment]
I want the exact same thing as @killajoe  and I found out it's quite hard to find out this answer.
Would it be possible to add this information somewhere xed-related, e.g. it's man-page, so it's easier to find ? @JosephMcc 

Note for future searchers:
```
# Backup
dconf dump /org/x/editor/preferences/ > ./xed_configuration_backup
# Restore
dconf load /org/x/editor/preferences/ < ./xed_configuration_backup
```
