### ISSUE TITLE
Cursor's opacity is so low, that it's barely visible

### ISSUE THREAD

**Issue by ibrag474** [linuxmint/xed#429]
```
 * Xed version 2.6.2
 * Distribution - Mint 20
```

**Issue**
Cursor's opacity is too low, it's barely visible.

**Steps to reproduce**
Go to preferences -> theme and set style scheme to Kate, open txt file and try to edit it.

**Expected behaviour**
Higher opacity of the cursor.

**Other information**

**Comment by JosephMcc** [comment]
I can only assume you are using a dark gtk theme. That's the only way I could reproduce this issue. It would be nice to have this info up front. That being said there isn't much we can do here. The themes like Kate are included as part of the GtkSourceView library that xed is built with and we don't have any control over those themes.
