### ISSUE TITLE
Search overrides primary selection

### ISSUE THREAD

**Issue by haarp** [linuxmint/xed#435]
Hello!

```
 * Xed version: 2.8.4
 * Distribution: Gentoo Linux
```
**Issue**
When a search term is found, the first occurence is automatically selected, overriding the contents of the primary selection ("middle click paste" buffer)

**Steps to reproduce**
- Open search panel
- Enter string that exists in file -> String will be selected
- Press mouse middle click -> It'll be the search term instead of what was previously in it

**Expected behaviour**
Only explicit manual selections should interfere with the primary selection.

Thanks!

**Comment by JosephMcc** [comment]
As far as I know there is no way for us to tell whether the selection came from a user mouse action or done by the code. Given that I don't see there is much that can be done about this.
