### ISSUE TITLE
Twig highlight mode would be nice to have

### ISSUE THREAD

**Issue by cptX** [linuxmint/xed#437]
```
 * Xed version (2.4.2)
 * Distribution - (Mint 19.3)
```

Hi, it would be nice to have twig syntax highlight available. I can't find any other similar syntax to make highlight on twig more useful. The closest I can find is javascript....

**Comment by Silveriomrs** [comment]
Much better, 
Could be possible to add our own sintax highlight?
I have also XLM format sintax for Notepad++ for CLIPS, and I have not any tool to add it or to rewrite it for XED.

**Comment by JosephMcc** [comment]
Syntax highlighting is provided by the gtksourceview libraries that Xed is built on. Requests for new language support should go here: https://gitlab.gnome.org/GNOME/gtksourceview

**Comment by cptX** [comment]
Created new issue here https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/174
