### ISSUE TITLE
Where did the auto-hyphenation "feature" come from, and how to disable it?

### ISSUE THREAD

**Issue by racooper** [linuxmint/xed#438]
```
 * Xed version (xed --version) 2.8.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Mint 20.1
```

**Issue**
a seemingly new auto-hyphenation feature has appeared that I don't recall from Mint 19's version of xed.  It's causing confusion when working with code.  There does not seem to be any setting to disable this feature.

**Steps to reproduce**
Open Xed, turn on "Word Wrap" in preferences.
Create a very long line with possible breakpoints (such as slashes).  At the edge of the Xed window, the line will break at a logical point such as a slash and insert a soft hyphen.

**Expected behaviour**
No hyphen gets inserted.

**Other information**
If you're going to add new 'features', at least give an option to turn them off.  I can't even find a reference to this behavior in the logs, or a changelog indicating a behavior change.  Bad form!

**Comment by JosephMcc** [comment]
>  Bad form!

Whatever form you might think it takes, it wasn't up to us. Most of these features, including word wrap, are provided by GtkSourceView. The only way to get around this is to turn off "Split words over two lines"
