### ISSUE TITLE
Hilight Syntax Module

### ISSUE THREAD

**Issue by Silveriomrs** [linuxmint/xed#439]
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**
There is not a way to introduce our own Syntax Hilight for some languages that XED doesn't have, ex. CLIPS.
I have gotten the syntax for Notepad++ but would be lovely a way to import in XML o export (to share) a syntax.

**Steps to reproduce**
Try to find some hilight for CLIPS

**Expected behaviour**
none

**Other information**

**Comment by JosephMcc** [comment]
Syntax highlighting is provided by the gtksourceview libraries that Xed is built on. Requests for new language support should go here: https://gitlab.gnome.org/GNOME/gtksourceview

**Comment by artofit** [comment]
https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/191
