### ISSUE TITLE
 How to delete the history of searches ?

### ISSUE THREAD

**Issue by SylvainParise** [linuxmint/xed#445]
```
 * Xed version (xed --version) 2.8.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint LMDE v4
```

**Issue**
Hello,
I would like to know how to delete the history of searches made with xed?
Where is the file containing this history?
cordially

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by mtwebster** [comment]
Try running these in a terminal:

```
> gsettings reset org.x.editor.state.history-entry history-search-for
> gsettings reset org.x.editor.state.history-entry history-replace-with
```

**Comment by SylvainParise** [comment]
Thanks ! It works.

**Comment by JosephMcc** [comment]
I'm going to go ahead and close this since it's been answered and isn't really a bug report.
