### ISSUE TITLE
Xed crashes when you open the overview map while there is no file open.

### ISSUE THREAD

**Issue by SuperDragonXD** [linuxmint/xed#450]
```
 * Xed version - Version 2.8.4
 * Distribution - Mint 20.1 Cinnamon
```

**Issue**
Xed crashes when you open the overview map while there is no file open.

**Steps to reproduce**

1. Open Xed
2. Close all tabs/files
3. Open the overview map by pressing View > Overview Map
4. Xed crashes

**Expected behaviour**
 A warning should pop up when you try to open the overview map while there is no file open / The Overview Map should be disabled.

**Other information**
Stack trace: https://termbin.com/h5cu9
[crash.tar.gz](https://github.com/linuxmint/xed/files/6160341/crash.tar.gz)

**Comment by SuperDragonXD** [comment]
Well, @okaestne fixed the issue, but the PR wasn't accepted yet. Should I close this?

**Comment by okaestne** [comment]
I tagged this issue in the PR, so it will be closed automatically when the PR is merged

**Comment by SuperDragonXD** [comment]
Ok
