### ISSUE TITLE
Add hightlighting for Ziglang

### ISSUE THREAD

**Issue by InfRandomness** [linuxmint/xed#451]
```
 * Xed version (xed --version):
xed - Version 2.8.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Fedora 33
```

**Issue**
<No issue>

**Steps to reproduce**
<No steps to reproduce>

**Expected behaviour**
<No expected behavior>

Hi, I would like to know if it is possible to add syntax highlighting to the editor for Ziglang (I can contribute to the implementation process).

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/xed/issues/437
