### ISSUE TITLE
Xed 2.8.4 FEATURE request: display long path's file - in title or as some file property

### ISSUE THREAD

**Issue by artofit** [linuxmint/xed#452]
```
 * Xed 2.8.4
 * Manjaro XFCE 21.0.1
```

**Issue**
tabs display file names
window's title displays: active file name + truncated path to active file name

Issue, sometimes you do no need to know more than the currently "truncated" file's path, because you're in a doubt about the actual location.

In the lateral pane (F9), it's not possible to right-click and have file details such as path.
The truncated path to active file name in window's title displays: displays the path beginning and the the path end.
However with "long" folder's name, it may not help

**Proposed solutions**
* In the lateral pane (F9), if one right clicks on a file, one has has a new contextual menu "path" or "properties" displaying full path details
* Instead of current behaviour for window's title displays as
**active file name (** + truncated path to active file name + **)**
have
truncated path to active file name; by doing so you gain 49 characters

Thanks

**Comment by JosephMcc** [comment]
You do know that if you hover the file name in the sidebar (F9), the tooltip shows the full path?

**Comment by artofit** [comment]
>You do know that if you hover the file name in the sidebar (F9), the tooltip shows the full path?
No didn't notice that I needed to hover more than 1sec on the file name in the sidebar (F9), for a tooltip to show up.
Apparently, each time I was quicker and had time to right-click for contextual menu and never have a tooltip show

**Comment by JosephMcc** [comment]
Does it give you the information you are looking for?

**Comment by artofit** [comment]
Yes.
The question is it whether or not to close the issue.
As one side the feature is there, but I fail to notice it

**Comment by JosephMcc** [comment]
I'm going to go ahead and close it since it is there. But it's something we can keep in mind if we ever do any redesign around this.
