### ISSUE TITLE
[Discussion] Change View > Overview Map to toggle preference for all tabs and permanently

### ISSUE THREAD

**Issue by okaestne** [linuxmint/xed#453]
```
 * Xed version -  2.8.4
 * Distribution - Mint 20.1
```

Currently the action "View" > "Overview Map" toggles the minimap only for the current tab, which is the chosen behavior of its initial PR #175. But at least for me this is unexpected behavior as I would at least expect it to toggle the map for all open tabs.
Also IMO the state should be permanently saved when closing xed and opening it again, like the other options in the action group (toolbar, statusbar, side pane).

What do you think? I would also try implement it if this is desired.

**Comment by JosephMcc** [comment]
You can already set it permanently from the Preferences. It exists in the "View" menu only so that it can be turned on and off per tab.

**Comment by okaestne** [comment]
Yeah I know that :) But I wanted to discuss whether this option in the View menu behaves like users expect it to behave, because I personally did expect it to behave like I wrote in the issue description.

**Comment by mrbesen** [comment]
Its pretty confusing, that you have the same option two times.
* In the Settings you seem to be setting the default
* and in the "View" > "Overview Map" seems to only set a temporary override.

That is pretty weird behaviour. I do not understand, why there is a need for those both options.
I think the "View" > "Overview Map" should be removed or mapped to the same value in the settings dialog. 
Or The name of the "View" option should be changed to something like "Disable Overview map for this Tab"
