### ISSUE TITLE
Cannot get out of fullscreen mode

### ISSUE THREAD

**Issue by Tehgg** [linuxmint/xed#460]
* xed - Version 2.8.4
 * Arch Linux

I use the window manager xmonad. If I press F11 in xed, the window enters "fullscreen mode", the only visible effect being that the top menu bar disappears (this is what I want). But xed doesn't detect it is in "fullscreen mode" and there is no way to make this bar reappear. F11 does nothing.

It seems that in the file `xed/xed-window.c`, the function `_xed_window_is_fullscreen` always returns that the window is not fullscreen because the variable `window->priv->window_state` never changes. In order to patch the bug, I added the line `window->priv->window_state |= GDK_WINDOW_STATE_FULLSCREEN;` at the end of `_xed_window_fullscreen` and the line `window->priv->window_state ^= window->priv->window_state & GDK_WINDOW_STATE_FULLSCREEN;` at the end of `_xed_window_unfullscreen`.

I suppose this is not the correct way to do it, but it works for my personal usage. Maybe the problem is caused by the fact that the window doesn't really go in "fullscreen mode" when I hit F11, so that it believes it is not. If so, there is a problem in the logic somewhere because I cannot access the menu bar anymore after hitting F11. I don't know what "fullscreen" is supposed to mean, but I would prefer if the functionalities of hiding the top bar and taking the entirety of the screen were distinct.

**Comment by leigh123linux** [comment]
Cinnamon already has a window manager, it's called muffin.
I can't reproduce the issue using muffin.


https://user-images.githubusercontent.com/1299302/119302904-c438c500-bc5c-11eb-8fae-fc68ab052977.mp4




xmonad isn't supported see https://wiki.haskell.org/Xmonad/Using_xmonad_in_Gnome#Gnome3

**Comment by Tehgg** [comment]
True, the issue can only be reproduced if the window manager doesn't actually allow fullscreen windows.

The link you provided says that "Gnome 3.8 and later only support gnome-shell as a window manager" (in particular not xmonad), but they don't speak about xed... I am sorry but I was not aware that xed was not compatible with xmonad, since I read that xed is an [XApp](https://linuxmint-developer-guide.readthedocs.io/en/latest/xapps.html) and that "The core ideas for X-Apps are: [...] To work everywhere (to be generic, desktop-agnostic and distro-agnostic) etc.". I don't know how one could know with what xed is supposed to be compatible with, sorry. But it is not my application, you make the rules, issue closed as you say.

Bye.

**Comment by leigh123linux** [comment]
Report the issue against xmonad, it seems to have trouble doing full screen on a lot of apps.

https://www.google.com/search?q=xmonad+full+screen+iisue&client=firefox-b-d&ei=w3GrYJqcN7mSwPAPy_Wl6AY&oq=xmonad+full+screen+issue

**Comment by Tehgg** [comment]
Ok, thanks. But let me try to explain what I mean a little bit more, if you wish. Let's forget xmonad. "Fullscreen" is composed of two distinct components: (1) the visibility of some components in the window (the top bar) and (2) the fact that the window takes the totality of the screen. (1) is dealt with by the application while (2) is dealt with by the window manager.

In applications such as xviewer, pix, vlc or chromium, there is (or seems to be) a separate internal variable storing if the application is in fullscreen mode or not and controlling (1), but independent from (2). One can test such a behaviour, in cinnamon with X11 by toggling fullscreenness of the applications with the command `wmctrl -r "<title>" -b "toggle,fullscreen"`. When the aforementioned applications recieve internally a fullscreen or unfullscreen command, they also activate or deactivate (2) accordingly, but not conversely when they recieve the command from wmctrl.

In applications such as xreader, xplayer, gedit, firefox... (1) and (2) are totally correlated: the wmctrl command also toggles (1).

But xed enters in none of these two categories. Instead, the internal representation of (1) is decorrelated from its true value and relies on the *external* invariant (2), so that the behavior is less robust than what it could be. All the other applications have coherent behaviours under the "extreme" circumstance that the WM refuses to give fullscreen mode, but not xed.

Moreover, one can read [here](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-fullscreen) that one shouldn't assume that the gtk_window_fullscreen method really puts the window in fullscreen mode. Yes, xed doesn't crash but still. I can understand that there are other priorities or contestations of what I said, but this is not about xmonad.

(Note: I personally prefer (2) to be a layout and not some property of a window.)
