### ISSUE TITLE
(Bug) Text not color coded correctly when comments are at the beginning of a file (C#)

### ISSUE THREAD

**Issue by forever-and-a-day** [linuxmint/xed#461]
```
 * Xed Version 2.8.4
 * Distribution - Linux Mint 20.1 x86_64 Cinnamon
```

**Issue**
Unsure if this is strictly a C# issue, but Xed does not color code anything after the comments in a C# file, other than using grey for the comment block

**Steps to reproduce**
Open a C# file in xed with many "//" lines of comments at the beginning. Text is all white. Remove the entire comment block, save and reopen the file, and xed color codes it. 

**Expected behaviour**
xed color codes C#

**Other information**
Screenshots: 
w/comment block:
![beforecommentremovedxed](https://user-images.githubusercontent.com/10383240/119421426-81560c00-bcb3-11eb-8bcd-41335720a371.png)
after comment block removed:
![aftercommentremovedxed](https://user-images.githubusercontent.com/10383240/119421444-8b780a80-bcb3-11eb-8374-ad439a2fa2d3.png)

- I'm using the official "Mint-Y Dark" theme provided by LM Cinnamon
- I'm using the "Oblivion"  style scheme 
Direct link to the file I'm working on, if it's useful: https://github.com/icsharpcode/AvaloniaILSpy/blob/a465d9fb6e8f786546a6db051664048a0703075c/ILSpy.Core/Commands/GeneratePdbContextMenuEntry.cs

**Comment by okaestne** [comment]
Can you check if this is caused by a BOM? See issue #390

**Comment by JosephMcc** [comment]
This issue is outside of our control. I believe this issue is already reported upstream on Gnome's Gitlab.
