### ISSUE TITLE
Small "LODs" (if that is how xed works) of the letter Ã look identical to the letter Ā

### ISSUE THREAD

**Issue by Wallby** [linuxmint/xed#463]
```
 * Xed version 2.8.4
 * Distribution - Linux Mint 20.1
```

**Issue**
The letter Ã looks identical to the letter Ā when zoomed out "too far".

**Step~~s~~ to reproduce**
In xed, type or paste the letter Ã

**Expected behaviour**
The tilde is recognizable as it is here.
![image](https://user-images.githubusercontent.com/13614975/120046988-c19aee80-c013-11eb-88b0-bc58ad96b7b7.png)

~~**Other information**~~

**Comment by Wallby** [comment]
Proof 
![image](https://user-images.githubusercontent.com/13614975/120047131-16d70000-c014-11eb-9f20-39704f0235c2.png)

**Comment by Wallby** [comment]
Same with the letter Ĩ
![image](https://user-images.githubusercontent.com/13614975/120047320-9238b180-c014-11eb-9769-cd49d26bcfcf.png)

**Comment by Wallby** [comment]
And the letter Ũ

**Comment by JosephMcc** [comment]
When you zoom you are temporarily changing the font size of the text. When you get below a certain size, you simply don't have enough pixels available to draw a curved a line. The font must adapt at a certain size to be able to draw a line at all. Their is nothing we can do to change that.

**Comment by Wallby** [comment]
@JosephMcc Well..
This..
![image](https://user-images.githubusercontent.com/13614975/127746205-6894cc79-8471-4a3d-bcf2-42c2e4703c9f.png)
Is zoomed in less than..
![image](https://user-images.githubusercontent.com/13614975/127746224-84a8359d-0062-43c2-b67d-af4aeebac4ab.png)
So it is not a lack of pixels here.

**Comment by Wallby** [comment]
Also, as is visible in these posts..

> Same with the letter Ĩ
> ![image](https://user-images.githubusercontent.com/13614975/120047320-9238b180-c014-11eb-9769-cd49d26bcfcf.png)

> Proof
> ![image](https://user-images.githubusercontent.com/13614975/120047131-16d70000-c014-11eb-9f20-39704f0235c2.png)

.. the tilde appears fine for the small letter A/I, while for the capital version not (while the size of the tilde is about identical in both cases).

**Comment by JosephMcc** [comment]
You are missing the point here. The font is doing this. This is how the font is drawing that at those sizes. There is nothing we can do about it in Xed, which is the reason I closed the issue.

**Comment by mtwebster** [comment]
Have you tried simply using a different font? You've got to deal with resolution and I imagine you have anti-aliasing at play here also.

You can change it in xed's preferences:
![image](https://user-images.githubusercontent.com/262776/127747174-af59b8c9-fc82-4e6b-b287-5e0f9b5f86b2.png)

Either way, this is not a xed issue. Have you tried this in other editors (many of them use the same libs for displaying text in this manner).

**Comment by Wallby** [comment]
@mtwebster Ah that is helpful. It seems to be an issue with the "system monospace font" for linux mint 20.1. It only happens for font sizes 10 and 11 (whereas 9 and 12 are fine).
