### ISSUE TITLE
Kate theme: "Highlight matching brackets"  hides cursor

### ISSUE THREAD

**Issue by haarp** [linuxmint/xed#469]
Xed 3.0.0 on Gentoo Linux

When using the Kate theme, enabling "Highlight matching brackets" effectively hides the cursor. It's pretty much impossible to tell if the cursor is on the left or the right of the bracket. See the screenshot:

![Screenshot_2021-07-14_22-49-05](https://user-images.githubusercontent.com/781030/125691126-a306a0c2-4233-4d38-9f89-d7b3fc3c71a3.png)

The Solarized Light theme also makes it kinda hard to tell.

Thanks!

**Comment by leigh123linux** [comment]
gtksourceview-4  provides the theme.
