### ISSUE TITLE
New style tabs for Xed Preferences window.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/xed#47]
The Xed Preferences window uses old style tabs, whereas Nemo's Preferences and Properties windows, as well as System Settings sections use new style tabs which are more elegant. It would be nice to have the new style tabs for Xed Preferences window as well.

Thank you.

**Comment by JosephMcc** [comment]
This is seeing a redesign for xed 1.8. It won't be the same style as cinnamon settings but a new style we are going to use among the xapps.
