### ISSUE TITLE
Blinking cursor leaves a pixel when disappears

### ISSUE THREAD

**Issue by Namerif** [linuxmint/xed#474]
```
 * Xed version - 2.8.4
 * Distribution - Mint 20.1 Cinnamon
```

**Issue**
Text cursor leaves a pixel after disappearing on an empty line.
https://user-images.githubusercontent.com/43481731/125772021-830f4429-2d2c-4eb2-8d11-e562aa2e6a41.mp4

**Expected behaviour**
I expect that the cursor should disappear completely, without leaving any pixels, as it does if the line is not empty.

**Comment by JosephMcc** [comment]
I've seen this before as well with some GtkSourceView themes. I don't know if the problem is the actual themes or something in GtkTextView. This isn't something that we control though. Those things are provided by the Gtk libraries we use.
