### ISSUE TITLE
Cannot Change Accels to "<Primary>Page_Up" or "<Primary>Page_Down"

### ISSUE THREAD

**Issue by tedstoychev** [linuxmint/xed#48]
I'm trying to reassign the
`<Actions>/XedWindowActions/DocumentsPreviousDocument` and
`<Actions>/XedWindowActions/DocumentsNextDocument` accels in `~/.config/xed/accels` respectively

from `<Primary><Alt>Page_Up` to `<Primary>Page_Up` and
from `<Primary><Alt>Page_Down` to `<Primary>Page_Down`

but the new key combos do not seem to trigger them. Other key combos (e.g. `<Primary>g` and `<Primary>h`) work, though.

Could somebody provide an explanation why this is happening?

**Comment by Laurencio** [comment]
I was trying to do the same, with no success-
