### ISSUE TITLE
Remove 'Revert' or ask for confirmation

### ISSUE THREAD

**Issue by PQCraft** [linuxmint/xed#480]
```
 * Xed version - xed - Version 3.0.2
 * Distribution - Arch BTW
```

**Issue**
Revert does not ask for confirmation

**Steps to reproduce**
1. Go to press 'Save As'
2. Misclick by a few pixels
3. Press 'Revert'
4. Lose 4 hours of work

**Expected behaviour**
1. Go to press 'Save As'
2. Misclick by a few pixels
3. Press 'Revert'
4. "Are you sure?" dialog appears with a Yes/No option
5. Press 'No'
6. Don't lose 4 hours of work

**Other information**
This is highly annoying as 4 hours of work on my personal project is quite a bit of work and now I'm considering using something besides xed after 3 years of using nothing but xed.
There are a few things that I think could fix this:
1. Remove the revert option
or any combination except 'none' of these:
1. Ask for confirmation after pressing revert
2. Keep the undo stack after pressing revert (so you can undo the revert)
3. Don't save the file after pressing revert (allow the user to do that)

**Comment by JosephMcc** [comment]
I do get a confirmation dialog here. I'm assuming that's why you closed it?

**Comment by PQCraft** [comment]
@JosephMcc 
> I do get a confirmation dialog here. I'm assuming that's why you closed it?

Yes it turns out I had 4 hours of sleep and was programming for quite a long while so I "did a stupid"
Sorry for the trouble just ignore this lol

**Comment by PQCraft** [comment]
I do know now that it undoes everything since last save. What I will suggest though is disabling the option until a change was made since last save, or don't move the cursor to the beginning if no changes were made since last save.
