### ISSUE TITLE
Beginner questions about building

### ISSUE THREAD

**Issue by clinton-r** [linuxmint/xed#497]
```
 * Xed version (xed --version)
3.0.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 20.2/XFCE
```

**Issue**
Hi I have some beginner questions about building xed, and I have no experience building software on Linux.  I am following the steps from README.md.  Sorry if this is not the best place to ask questions - if so could you please tell me where I should ask?

So far I've got as far as running 'dpkg-buildpackage' and getting this error:
```
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9) gobject-introspection gtk-doc-tools intltool libgirepository1.0-dev libglib2.0-dev libgspell-1-dev libgtk-3-dev libgtksourceview-4-dev libpeas-dev libxapp-dev (>= 1.9) libsm-dev libx11-dev libxml2-dev gnome-common yelp-tools
```
1. It looks like all of these are packages I can install using apt.  Is that what is expected, or is there some way to get the build system to fetch them all automatically?
2. Once I get the build working, I would like to install the newly-built xed somewhere under my home directory so that I can experiment with changes to the code without affecting the "real" version of xed that was installed with Mint/XFCE.  How would I do that?
2b. From README.md: "4. From then, any new changes can be applied by running # sudo ninja -C debian/build install" - will that still work if my new version of xed wasn't installed in the default location?
3. When I have more questions, should I post them here?
Thanks

**Steps to reproduce**

**Expected behaviour**

**Other information**

I have the build-essential package installed.

**Comment by clinton-r** [comment]
Hi okaestne, thanks for your help!  I'm making progress...

As you instructed, I used
`mk-build-deps -i -s sudo`
to install the dependencies.  Then I did:
```
meson --prefix=/usr/local build
ninja -v -C build
sudo ninja install -v -C build
```
So now it is built and installed, but I get an error when running it:
```
$ /usr/local/bin/xed 

(xed:24742): GLib-GIO-ERROR **: 15:14:41.801: Settings schema 'org.x.editor.preferences.ui' does not contain a key named 'menubar-visible'
Trace/breakpoint trap (core dumped)
```
The `menubar-visible` key appears to have been added to github after the 3.0.2 version tag.  I guess that the xed version I compiled is reading the settings from the 3.0.2 version.
I tried both the `gsettings` command and dconf-editor, but couldn't figure out how to create a new key with either of them.

1. Can you suggest a way to fix or work around this problem?
2. What is the usual way to get set up to develop xed?  Is it unusual to install in non-default location and keep the OS-provided version installed as well?  If it will make things easier I'm happy to replace the OS version temporarily while I experiment.
3. Is it possible to develop plug-ins without changing the xed code at all?  Maybe I should start with that instead...

**Comment by okaestne** [comment]
I would build the .deb packages once and install them to have the gschema installed and then continue installing into /usr/local using meson/ninja to save the time for building and installing the packages. Can't tell what's really the best practice here.
And sure, plugins should by definition be able to be created without touching the xed source code at all.

**Comment by andy9a9** [comment]
Maybe a small side-note, the error what you have is, that schema is not compiled.
```sh
sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas
```
Then then message should be gone.

**Comment by clinton-r** [comment]
Compiling the schema seems to have done the trick.  Thank you both for your help.

**Comment by gitgt** [comment]
Please close the issue.
