### ISSUE TITLE
Name "xedit" is still dominant in the translation strings (should be: "xed").

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/xed#5]
In the translation strings for xed, it's still called "xedit". That should of course be "xed".

Furthermore, in the translation strings the first letter of its name isn't capitalized. It would be nicer if the first letter of its name would be a capital, as is customary for GUI apps.

So my proposal would be, to replace "xedit" in all relevant translation strings by "Xed".

**Comment by Fred-Barclay** [comment]
G'day Pjotr123. :smile: Are you referring to files like po/mi.po ?

**Comment by clefebvre** [comment]
It's gone from all msgids now. Still present in a couple of msgstr, but that's fixable on Launchpad.
