### ISSUE TITLE
xed traps in LXDE

### ISSUE THREAD

**Issue by kanehekili** [linuxmint/xed#515]
```
 * Xed version - 3.0.2
 * Distribution -  Arch
```

**Issue**
Tested on arch linux with LXDE/Openbox WM.   
The program does not start (X11) and traps after the following message:
GLIB-GIO Error: Settings schema 'org.x.editor.preferences.editor' does not contain a key named 'draw-whitespace'
Then:
"Trace/breakpoint trap -core dumped"
dmesg shows:

`xed[3266] trap int3 ip:7f5d7dff9250 sp:7fffd4b3e3d0 error:0 in libglib-2.0.so.0.7000.2[7f5d7dfbb000+8d000]`

**Steps to reproduce**
Open xed

**Expected behaviour**
xed opens

**Other information**

**Comment by okaestne** [comment]
Running `glib-compile-schemas /usr/share/glib-2.0/schemas/` (or wherever the schemas are installed in) should fix this
