### ISSUE TITLE
can't change theme in elevated mode

### ISSUE THREAD

**Issue by k2s** [linuxmint/xed#517]
```
 * Xed version (3.0.2)
 * Distribution - Arch Linux
```

**Issue**

It is not possible to change nor save Preferences when xed is running in Elevated Privileges mode.

**Steps to reproduce**

* run `xed`
* set theme in preferences and quit xed
* run `sudo xed`
* you will not see the changed theme
* in Preferences you will be able to change theme, but it will not apply and it is not possible to save it.

**Expected behaviour**

Xed should store settings in elevated mode.
I would prefer to have additional tab `Elevated mode` in Preferences dialog and be able to select different them and also to disable the `Elevated Privileges` toolbar which takes space on screen.

**Other information**

what works is to manually copy the `~/.config/dconf/user` to `/root/.config/dconf/user`

**Comment by the-saddest-clown** [comment]
In my case (Linux Mint 20.3 Xfce) : 

- Open Xed as sudo
- Set the wanted theme
- Close Xed

Next time I run Xed with elevated privileges, the chosen theme is still applied.

**Comment by StLeoX** [comment]
Anyone knows how to turn off the "elevated privileges" bar?

**Comment by mtwebster** [comment]
Programs running elevated don't share the same settings as those that don't.  This is a system limitation and really can't be fixed.

If I set the same theme in xed for sudo and non-sudo it works fine for me, the settings persist from session to session for both modes.

> what works is to manually copy the ~/.config/dconf/user to /root/.config/dconf/user

This is really, really, really not a good idea.
