### ISSUE TITLE
New search function searches jumps

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/xed#52]
Everytime you type in a letter the search function jumps to the next found word. Even if the new word is the same as the old one.

**Comment by erdoking** [comment]
same here, really bad

**Comment by NikoKrause** [comment]
When you delete your search pattern, the last deleted letter is still highlighted.
E.g. when you search for "Action" in a text with a lot of a's and you delete your search pattern, the text shines bright like a diamond in the sky. Or like a Christmas tree. I'll post a screenshot later.

**Comment by NikoKrause** [comment]
![christmassearchtree](https://cloud.githubusercontent.com/assets/8415124/20640788/09c28e48-b3e9-11e6-954a-528d943ba4a8.png)

**Comment by JosephMcc** [comment]
Both of these issues should be fixed now in git.
