### ISSUE TITLE
highlight of current line theme issue

### ISSUE THREAD

**Issue by sidmint** [linuxmint/xed#520]
```
 * Xed version 2.4.2
 * Distribution - Mint 19.3
```

**Issue**
highlight of current line in "classic" and "tango" renders text unreadable as colour is too strong unlike other themes where colour is a very light shade.

**Steps to reproduce**
Toggle to highlight of current line from settings, select theme  "classic" or "tango", read the current highlighted line where the cursor is.

**Expected behaviour**
Like rest of the themes, highlight colour should be a very light shade.

**Other information**
demo of classic theme
![2022-01-16-07:36:53](https://user-images.githubusercontent.com/43943312/149644708-ac3312c3-a482-4ae7-adfb-1a506af4d07c.png)

**Comment by JosephMcc** [comment]
Those GtkSourceView themes are part of the library itself. We don't actually control them. Unfortunately some just do not work well with dark themes. The best solution in those cases is just to choose a different theme for the editor.

**Comment by dtki7** [comment]
It's possible to tweak some colors by editing the files `/usr/share/gtksourceview-4/styles/classic.xml` and/or `/usr/share/gtksourceview-4/styles/tango.xml` and restarting the application. 

Issue tracking: <https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/29>.
