### ISSUE TITLE
No language in spell check

### ISSUE THREAD

**Issue by mahdi-ln** [linuxmint/xed#529]
* Xed version 3.2.2
 * I'm using Arch Linux because of pacman-bintrans. Although it uses log transparency for packages delivery. I think only effective method for "binary transparency" is PoW blockchian. In PoW blockchian method software checksum index is written on a PoW blockchain which has reach a hard difficulty e.g. Ethereum. The client put a time-limit on how long it takes for blockchain nodes to solves hash values and this way it finds out if it is seeing an international powerful blockchain

**Issue**
![image](https://user-images.githubusercontent.com/27496531/158075181-63aa0b1b-cd6b-4b94-9bfe-235fc7766a43.png)

**Comment by Giraffaman** [comment]
Using xed v3.2.3 on Manjaro and I also cannot see any languages to select for spell-checking. I checked the help function and searched in there, but cannot find any instructions about how to add a language.

How can we add languages so they can be selected for spell-checking?
