### ISSUE TITLE
Can't close search bar

### ISSUE THREAD

**Issue by erdoking** [linuxmint/xed#53]
I can't find a way to close the search/replace bar.

System:
OpenSuse Leap 42.1
Cinnamon 3.2.1-3.1
xed 1.2.0

I checked your commits for 1.2.1 but didn't find a new button like 'close' ...

------------------------------
Feature request:
Choose between search windows and searchbar ...

**Comment by JosephMcc** [comment]
A close button would probably be a good idea. Currently you can close it with "Esc".

**Comment by erdoking** [comment]
really nice info. thank you! 
I have test everything else ... Really did not think of it
