### ISSUE TITLE
missing feature open in a specific folder

### ISSUE THREAD

**Issue by ineuw** [linuxmint/xed#537]
```
 * xed - Version 3.2.2
 * Linux Mint Cinnamon 20.3 
```

**Issue**
It's not possible to set a default folder where xed starts. 

**Steps to reproduce**
Not possible

**Expected behaviour**
Ignore "last" folder and open in a pre-assigned folder.

**Comment by tudo75** [comment]
I think it's due to the file browser plugin which set a key to open root folder in hte las opened file
you can disable it using dconf-editor and setting the key `open-at-first-doc` to false in `/org/x/editor/plugins/filebrowser/`

**Comment by ineuw** [comment]
@tudo75 Thanks for the help. I made the change but Xed always opens in the user's home folder. I can specify a file, including the path, but a folder by itself. Can you please explain your statement below? 
```
Or you can make a folder the default one right clicking on it and choosing mark it as root
```

**Comment by tudo75** [comment]
@ineuw Set file path as root is what I suggested.
You can try my `Restore Tabs plugin` which reload last tabs opened and also the last file browser root folder
[https://github.com/tudo75/xed-restore-tabs-plugin](https://github.com/tudo75/xed-restore-tabs-plugin)

**Comment by ineuw** [comment]
Thanks for the suggestion about the path, and I installed the plugin. It satisfies my need.
