### ISSUE TITLE
Bug: Mouse wheel allways close last open tab

### ISSUE THREAD

**Issue by erdoking** [linuxmint/xed#54]
In firefox/nemo i always use the mouse wheel to close single tabs.
If i try this in xed it always close the last tab not the selected or open ...

System:
OpenSuse Leap 42.1
Cinnamon 3.2.1-3.1
xed 1.2.0

**Comment by JosephMcc** [comment]
I can't reproduce this. Middle mouse click closes the tab I'm hovering over as expected.

**Comment by Vahan86** [comment]
I can't reproduce this issue in Cinnamon 4.2 (xed 2.2.3) as well.

@icarter09, can we close this issue?

**Comment by erdoking** [comment]
Yes it seem to be fixed in xed 2.2.3
