### ISSUE TITLE
Overview map - Change size?

### ISSUE THREAD

**Issue by BlueMax** [linuxmint/xed#545]
```
 * xed - Version 3.2.7
 * Arch Linux 5.19.2
```
I like the 'overview map' feature but its somewhat too large stealing some valuable space on screen.
Would it be possible to allow setting its size or at least a second/smaller mode?

**Comment by okaestne** [comment]
I just checked that and it is actually possible to define a font size for the overview map via the `font-desc` property of the `GtkSourceMap`. Some quick findings:

* Currently the font is 2pt large and *could* be reduced to 1pt, even if it isn't much helpful then.
* The minimum size of the overview map seems to be limited by the font size. It seems to be at 80px at 1pt font size and 160px at 2pt. However, it is possible to freely increase the width.
* The font could be set to Monospace Bold, which helps to recognize things in general IMHO.
