### ISSUE TITLE
What is bottom pane? (Ctrl + F9)

### ISSUE THREAD

**Issue by bdh1993** [linuxmint/xed#548]
```
 * Xed version 3.0.2
 * Distribution - (Mint 20.2)
```

**Issue**
The bottom pane view is not active.
How to activate or use.

**Steps to reproduce**
1) Open Xed
2) View > Show bottom pane (Ctrl+F9)

**Comment by JosephMcc** [comment]
It's there as available space for external plugins. I don't think any included with Xed use it currently. Nor does Xed use it for any of it's built in tools. If you install a plugin that uses it, then you will be able to activate it.

**Comment by bdh1993** [comment]
Thank you JosephMcc.
