### ISSUE TITLE
Open recent documents

### ISSUE THREAD

**Issue by pellesimon** [linuxmint/xed#55]
I like xed, but being used to gedit I am missing the feature to open recent documents. It would be very much appreciated if this could be implemented.

**Comment by JosephMcc** [comment]
What do you mean? Recent documents show up in the "File" menu between "Print" and "Close". Also, if you do "File->Open" the dialog that opens has a recent entry at the top in the sidebar.

**Comment by pellesimon** [comment]
Hello Josheph, 
It's a bit embarrassing, but you are right. It seemed like the first time after using the editor this was not working, but it works fine now!

**Comment by aaime** [comment]
I'm actually in the same situation, the recent files are not showing up... I open a file, close xed, start it again, there are no files in the recent files list.
This is xed 1.2.2 on a Mint 18.1

**Comment by gordon-morehouse** [comment]
I can confirm that this is a problem in 1.2.2.

**Comment by denzel100** [comment]
@aaime, @deutrino, check the "privacy" system settings and make sure "Remember recently accessed files" is "ON".

**Comment by aaime** [comment]
@denzel100 indeed that fixed it for me. However, I never modified that setting before, upgrading and having to search for a (possibly new?) setting to get the previous behavior is not good.

**Comment by denzel100** [comment]
@aaime, I tend to agree, but it would appear the changed default is a workaround for a memory leak issue (see https://github.com/linuxmint/Cinnamon/issues/6089). The new default was introduced in https://github.com/linuxmint/cinnamon-desktop/commit/2015cc0f8a8fe46384225b0cf10df45f7d3d9315. 

Perhaps @clefebvre can offer an update on the issue?

**Comment by ByteHazard** [comment]
I found this privacy feature to be rather non-intuitive. Personally I would like xed to be able to remember recent files (as gedit did), yet Nemo *not* show a "Recent files" folder (which I personally rarely use).

IMO it is best to provide per application (xed) these setting options:
* use system settings (i.e. enforce Cinnamon privacy setting in this application)
* remember recent files
* don't remember recent files
The last two would allow one to override the Cinnamon privacy setting.
This would allow finer grained privacy settings.

**Comment by dodona2** [comment]
there is a recent file list between print an close in 1.6.2. Note that it only appears after visiting some files. what is pretty normal.
