### ISSUE TITLE
When find search term is cleared, highlighting persists. 

### ISSUE THREAD

**Issue by calexil** [linuxmint/xed#56]
Find function leaves text highlighted with no way to undo the search and un-highlight everything, this is very annoying on a dark theme where the highlighting colors make the found text impossible to read. and generally irritating that the find highlight persists for no reason.

![screenshot at 2016-11-28 14-44-06](https://cloud.githubusercontent.com/assets/3487071/20683311/7b371e18-b579-11e6-8ac5-e7416b32c0ad.png)

**Comment by JosephMcc** [comment]
Xed no longer even uses that same search dialog. There is a similar issue under the new version here: https://github.com/linuxmint/Cinnamon/issues/2301

**Comment by calexil** [comment]
wat? @JosephMcc this is not related to wallpapers at all....

**Comment by calexil** [comment]
do you mean 18.1 ships with a fix for this?

**Comment by calexil** [comment]
gotcha, thats the one that does a real time search amirite?

**Comment by JosephMcc** [comment]
Yes. It's new and still seems to have a couple small issues but hopefully we can continue to improve it.
