### ISSUE TITLE
xed is relying on uninstallable package `python3.9`

### ISSUE THREAD

**Issue by Stehlampe2020** [linuxmint/xed#563]
```
 * Xed version: GitHub Release master.lmde5
 * Distribution: Ubuntu Unity 22.04
```

**Issue**
Installation fails with following error message: 
```none
Följande paket har beroenden som inte kan tillfredsställas:
 xed : Beroende av: python3.9 men det kan inte installeras
```
Sorry for it being in Swedish, that's my system language because I moved here from Germany. Below is a rough translation: 
```none
The following packages have dependencies that can not be met:
 xed : Depends on: python3.9 but that can not be installed
```

**Steps to reproduce**
Download xed from GitHub Releases page, unpack it and run `sudo apt install -f ./*.deb` in the unpacked folder to simply install all `.deb` packages found in that directory. 

**Expected behaviour**
APT running a while, after that xed should be installed.

**Other information**
I think that the dependency is too strict, or is there any Python3.9 feature xed uses that's not available in Python3.10 and later?

**Comment by Stehlampe2020** [comment]
As far as I can see I just fixed the issue myself: I don't necessarily need to use APT, I can use DPKG directly instead. It still showed some errors: 
```none
Fel uppstod vid hantering:
 xed
 xed-dbg
 xed-dev
```
(Translation of the first line: `Errors occurred when handling:`)   

...but when I tried to run xed it popped up without any further error message and it correctly appeared in the application menu.

**Comment by Stehlampe2020** [comment]
@mtwebster Where do I get `*.deb`s that work on Ubuntu 22.04?   
And if the configuration only wants `python3` why does it require exactly `python3.9` when trying to install it?

**Comment by mtwebster** [comment]
During the packaging phase of the build the actual python version gets resolved into the one for the current build target.

The 'python3' package is a psuedo-package that points to 3.9, 3.10, etc.. whatever your system currently uses. It's to keep this exact issue from occurring when packaging for multiple distributions.
