### ISSUE TITLE
Alt+F / Alt+S should save the file but it is not working

### ISSUE THREAD

**Issue by DanRRRR** [linuxmint/xed#578]
```
 * Xed version (xed --version)  3.2.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 21.3
```

**Issue**
Can not save file with the combination Alt+F and  then  Alt+S.

**Steps to reproduce**
Alt+F highlights Menu File and the Alt+S should employ default behavior of invoking Save file because highlighted letter S in the word Save implies exactly this behavior. But you have to do one more movement - remove finger from Alt and then hit S. Things are that not all software keeps File menu available if you lift the finger from Alt. And to save this way you need to do 3 hits instead of 2. Due to that many software developers allow Alt+F / Alt+S combination to work

**Expected behaviour**
After you see Menu  File when pressing Alt+F  the second combination ( Alt+S ) should save the file same way as Ctrl+S is doing

**Other information**

**Comment by mtwebster** [comment]
This isn't behavior controlled by xed, it's at the toolkit level (every other program using it behaves the same way, not just xed).

https://gitlab.gnome.org/GNOME/gtk/-/issues

Do you have an example of a program that closes the menu when you release Alt? I would consider *that* to be incorrect behavior. The only time I observe that is when clicking a menu to open it, and either keeping the button depressed for a slightly longer time, or selecting a menu item then releasing (which till typically activate that menu item).

**Comment by DanRRRR** [comment]
This is why people who came from much more crowded Windows world when they meet different tactile behavior of editors in Linux chose those editors which do not try to bend that de-facto default habits. ALL popular editors for Windows have what i am talking about. 

Can you at least add Alt+S to be synonymous to Ctrl+S ? Or even better - add user defined shortcuts?
