### ISSUE TITLE
[xed-file-browser-widget.c] GTK_STOCK_HOME is deprecated

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/xed#58]
**xed-file-browser-widget** triggers errors about icon ``GTK_STOCK_HOME`` not found.
Indeed, according to [GNOME Developer Center](https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html):
>>GTK_STOCK_HOME has been deprecated since version 3.10 and should not be used in newly-written code.
Use named icon &quot;go-home&quot;.

**Comment by JosephMcc** [comment]
What do you mean errors? Does is it prevent it from working? These deprecation warnings shouldn't actually affect the functionality.

**Comment by oberon2007** [comment]
You are right, it's probably trivial. :)
