### ISSUE TITLE
Disable 2 double quotes

### ISSUE THREAD

**Issue by ineuw** [linuxmint/xed#588]
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```
Linux Mint Cinnamon 21.1  - xed 3.2.8

**Issue**

I need to disable the 2 double quotes since I use xed as a text editor, not a code editor. 

**Steps to reproduce**

Tap the " key

**Expected behavior**

a single Chr(0034)

**Other information**

**Comment by trikaphundo** [comment]
Hello. You may have a highlight mode activated; make sure you it is set to `plain text`: View -> Highlight mode -> Plain Text.
The highlight mode for each document is accessible from the status bar as well, at the bottom of the window.

**Comment by leigh123linux** [comment]
Disable "bracket completion"

![image](https://github.com/linuxmint/xed/assets/1299302/4a351686-171c-4ee6-bbe6-362af7723afc)
