### ISSUE TITLE
Ctrl+N (new document) only works when files are open

### ISSUE THREAD

**Issue by spike200a** [linuxmint/xed#598]
```
 * Xed version (xed --version) 3.4.3
 * Distribution - (Linux Mint 21.2 Cinnamon)
```

**Issue**
See issue title

**Steps to reproduce**
Press Ctrl+N when no files are opened

**Expected behaviour**
Open a new empty document

**Other information**

**Comment by BanceDev** [comment]
Followed steps to reproduce and Ctrl+N does in fact open a new file when no files are opened, this issue can be closed.

**Comment by JosephMcc** [comment]
> Followed steps to reproduce and Ctrl+N does in fact open a new file when no files are opened, this issue can be closed.

Just tried and it works for me as well. So closing.
