### ISSUE TITLE
Many Gtk-2.0 dependencies when building.

### ISSUE THREAD

**Issue by ali1234** [linuxmint/xed#6]
For example:

configure: error: Package requirements (
	libxml-2.0 >= 2.5.0
	glib-2.0 >= 2.36.0
	gmodule-2.0
	gthread-2.0 >= 2.13.0
	gio-2.0 >= 2.26.0
	gtk+-2.0 >= 2.24.0
	gtksourceview-2.0 >= 2.9.7
) were not met:

No package 'gtksourceview-2.0' found

And after fixing that:

configure: WARNING: No package 'pygobject-2.0' found
No package 'pygtk-2.0' found
No package 'pygtksourceview-2.0' found

Isn't this wrong if the Gtk2 version is dropped?

**Comment by vladimir-didenko** [comment]
@ali1234  You can pass "--with-gtk=3.0" to configure. But configure script should be definitely cleaned since it can't be compiled with gtk2.

**Comment by dvergeylen** [comment]
```bash
./autogen.sh --with-gtk=3.0
```
will indeed do the trick:
```bash
dv@daniel-zenbook /tmp/xed $ ./autogen.sh --with-gtk=3.0
[...]
Running ./configure --enable-maintainer-mode --with-gtk=3.0 ...
[...]
checking which gtk+ version to compile against... 3.0
[...]
Configuration:

	Source code location:	.
	Compiler:		gcc
	GTK API version:	3.0
	Python Plugins Support: no
	Spell Plugin enabled:	yes
	Gvfs metadata enabled:	yes
	Tests enabled:		yes

Now type `make' to compile xed
dv@daniel-zenbook /tmp/xed $
```
