### ISSUE TITLE
Fractional font size rounded down

### ISSUE THREAD

**Issue by haarp** [linuxmint/xed#601]
```
 * Xed version: 3.4.3
 * Distribution: Gentoo Linux
```

**Issue**

When selecting font size that are not integers (e.g. `5.75`), they are rounded down (to 5 in this example). This makes getting the size just right hard. It's also confusing, as the font selector **does allow** setting fractional sizes, they just won't have an effect.

**Steps to reproduce**

- Select fractional font sizes in settings
- Observe that 5.00 to 5.99 all result in the same font size in the editor

**Expected behaviour**

Fine-tunable font size

**Other information**

Thanks!

**Comment by JosephMcc** [comment]
The dialog that pops up to choose a font is provided by Gtk. I don't really know why it even allows entering a fractional size.

**Comment by haarp** [comment]
So fractional font sizes are not intended to be supported? Why is that?
