### ISSUE TITLE
xed doesn't close right away after closing large text files, the program takes a lot of time

### ISSUE THREAD

**Issue by ylevental** [linuxmint/xed#605]
```
 * Xed version 3.4.2
 * Distribution - Fedora 38 cinnamon
```

**Issue**
xed doesn't close right away after closing large text files, the program takes a lot of time

**Steps to reproduce**
1. Open a large text file with xed (I would estimate at least 1 GB)
2. Close the file right away as it is loading
3. Check the system monitor, xed will still be running for at least 10 minutes

**Expected behaviour**
Xed should exit right away.  This happens for pluma and gedit.

**Other information**

**Comment by BanceDev** [comment]
This issue was resolved in my PR a few weeks back. Can be closed.
