### ISSUE TITLE
Allow /usr/local/share/gtksourceview-3.0/styles to be used for themes

### ISSUE THREAD

**Issue by zilexa** [linuxmint/xed#609]
```
 * Xed version (xed --version) 3.4.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Fedora Silverblue 39
```

**Issue**
Immutable OS like Fedora will have an read-only image as OS, meaning /usr/local/ cannot be modified by user or root. 
Xed Text Editor themes files cannot be placed in `/usr/share/gtksourceview-3.0/styles`.

**Steps to reproduce**
OS limitation.

**Expected behaviour**
Feature request: besides looking in the /usr/share folder, also check /usr/local/share: `/usr/local/share/gtksourceview-3.0/styles`.

**Other information**
Alternative user-only location works `$HOME/.local/share/xed/styles` but does not allow for global installation of themes.

**Comment by leigh123linux** [comment]
xed uses gtksourceview-4 only, adding styles to /usr/local/share/gtksourceview-4/styles/ works ok here.
