### ISSUE TITLE
Feature request: Nix language highlighting support

### ISSUE THREAD

**Issue by turbotimon** [linuxmint/xed#618]
```
 * Xed version: 3.4.3
 * Distribution: NixOs (with Cinnamon Desktop Environment)
```

**Issue**
- No syntax highlighting for the [Nix language](https://nix.dev/tutorials/nix-language) (files ending with .nix)
- Is there a way to manually adding it?

**Comment by bobby285271** [comment]
This will be fixed when one of the following happened:

- xed is ported to gtk4 + gtksourceview5
- https://github.com/NixOS/nixpkgs/pull/278038 get accepted

---

![](https://github.com/linuxmint/xed/assets/20080233/b2abb657-b2bd-49a3-9885-6ec09d8c4fd5)

**Comment by leigh123linux** [comment]
Close as not planned.
