### ISSUE TITLE
Black lines at the bottom of a file after refreshing document

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/xed#62]
I observed the black rectangle a few times in the past.
Now I can reproduce it a lot.
![bildschirmfoto vom 2016-12-13 11-31-57](https://cloud.githubusercontent.com/assets/8415124/21136951/0e8d72f2-c128-11e6-903d-22802cecf7d4.png)

Open the file `~/.local/share/recentyl-used.xbel`
When you minimize and maximize the file, you get a red bar with the option to `Reload`.
After reloading, scroll to the bottom. The black rectangle at the bottom should appear.

**Comment by NikoKrause** [comment]
I still can reproduce it wiht xed 1.2.2. It basically happens, when you have a scrollable file and reload it.
The above mentioned file was only an example. Do reproduce this with this file you have to activate the "show recently used files" in the privacy settings and you need a decent list of recently used files, so that the file is long enough to be scrollable.

**Comment by JosephMcc** [comment]
I can't reproduce this. I have both .xsesssion-errors and recently-used.xbel open which both need constant reloading. Does it matter how you scroll? Hotkey, mouse wheel, scrollbar? I wondering if this is a graphics issue. Not sure it would have any effect but can you reproduce it all themes as well?

**Comment by NikoKrause** [comment]
I haven't seen the black line lately and I'm no longer able to reproduce it.
So I think it has been fixed sometime.
