### ISSUE TITLE
White text with Mint-Y-Dark theme for controls

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/xed#63]
- choose Mint-Y-Dark (I have it set for window, icons, controls and panel)
- activate xed setting "highlight current line"
- write some text
-> white text on white background.

Workaround: choose any color scheme but Classic or Tango.

Should the text color in the highlighted line change automatically to get a high contrast or does this work as intended?

**Comment by JosephMcc** [comment]
The GtkSourceView theme you choose in the preferences is separate from the gtk theme. Since you can set any combination of gtk and source view theme there isn't much that can be done.

**Comment by CottonEaster** [comment]
I find that changing theme from within root xed makes no difference in any way to the appeance of the editor.

**Comment by CottonEaster** [comment]
Actually, I have, now, found an Xed theme that allows all text to be readable when using the Mint-Y dark global theme. However, _since Xed seems to save nothing when run as root_, this means that, whenever one runs Xed as root, and uses one of the default global themes, some text is unreadable. That is not good.
