### ISSUE TITLE
Adding number of match amount

### ISSUE THREAD

**Issue by vlad1777d** [linuxmint/xed#64]
Hello.
When you open search window (CTRL + F), and write something to search and press ENTER, the number of match amount is not displayed: 
![2016-12-23 15-17-17](https://cloud.githubusercontent.com/assets/12682937/21454715/4fee3026-c923-11e6-8656-545abac3225e.png)
In Gedit it's present:
![2016-12-23 15-21-43](https://cloud.githubusercontent.com/assets/12682937/21454759/c2ffbf62-c923-11e6-8948-f765fab2aa74.png)
Xed version: 1.0.6
System: Linux Mint 18

I think, that it's very important to know amount of matches with search keyword, not to scroll every time over all document.

Best regards,
Vladislav

**Comment by gsiou** [comment]
![image](https://cloud.githubusercontent.com/assets/827278/21472903/6405d732-caf7-11e6-8a74-8e17166db46d.png)

The search interface has changed a bit in 1.2.2 but the amount of matches is still missing.
