### ISSUE TITLE
Sort lines requieres a new shortcut.

### ISSUE THREAD

**Issue by darkshram** [linuxmint/xed#645]
```
 * xed - Version 3.6.1
 * ALDOS 1.4
```

**Issue**

Before version 3.6, `Sort lines` used the F10 shortcut. Since version 3.6, F10 now assigned to `Show overview map`, as consequence `Sort lines` does not work with F10 shortcut.

![xed-shortcuts](https://github.com/linuxmint/xed/assets/10327500/ef4a77ed-af83-4140-9803-b5c4a25655f1)

**Steps to reproduce**

Update to 3.6.x then try to sort lines using F10 key.

**Expected behaviour**

`Sort lines` should have a new updated shortcut.

**Other information**

Interface and source code still shows F10 as shortcut for `Sort lines`, but F10 is now assigned to `Show overview map`.

![xed-sort-lines](https://github.com/linuxmint/xed/assets/10327500/48003b14-677c-4f26-8119-b6e1b3be78c4)

```
static const GtkActionEntry action_entries[] =
{
    { "Sort",
      NULL,
      N_("S_ort lines"),
      "F10",
      N_("Sort the current document or selection"),
      G_CALLBACK (sort_cb)
    }
};
```

**Comment by JosephMcc** [comment]
This is a consequence of https://github.com/linuxmint/xed/commit/0ecca7db974b87447cc98f847c298b53daad7243
