### ISSUE TITLE
Feature Request: Lack Of Information About Color Schemes for Xed

### ISSUE THREAD

**Issue by LWFlouisa** [linuxmint/xed#651]
```
Previous current version on Linux Mint 21
```

**Issue**
There seems to be a lack of tutorials for how Color Scheme XML works and lack of clarity on why things are named how they are. I ended up figuring this out by reverse engineering a public available XML color scheme.

**Steps to reproduce**
Comes with the default packaging on Xed, such as a lack of a specific themes folder.

**Expected behaviour**
I was expecting a default themes folder, or at least some way to inspect how the gui works. And maybe a way to export default XML color schemes to learn how they work.

**Other information**
The ability to learn how these works involves inspect secondary information like publicly available Color Scheme XML, which isn't exactly optimal.

The good news is I did manage to figure out my own scheme.

**Comment by JosephMcc** [comment]
These color schemes are provided by GtkSourceView. A search online will probably turn up more information. You can find Xed's built in color schemes in /usr/share/gtksourceview-4/styles/
