### ISSUE TITLE
Feature Request: Bookmarks option in the File browser pane

### ISSUE THREAD

**Issue by drbogi** [linuxmint/xed#66]
Hi,
It would be nice if there was a possibility that under the File option in the Side Pane browser plug-in, add arbitrary bookmarks folder. This would quickly locate the desired files, instead of navigating step by step through the file system.

In Sublime Text, there is a good example plugin entitled Folder, where this problem is solved smart.
It is interesting that when you use the File>Open dialog, Xed recognizes Bookmark option from the Caja.

I apologize if I'm looking for something that may already exist, the requirements relating to Xed ver. 1.2.2,  LMDE2, with Mate at my computer. 

Regards to all

**Comment by JosephMcc** [comment]
In the side pane, you can select "Bookmarks" from the combobox at the top of the view and it shows any bookmarks that I've added in Nemo. I'm not sure we'd implement anything beyond this.
