### ISSUE TITLE
configure still has MATE references

### ISSUE THREAD

**Issue by ali1234** [linuxmint/xed#7]
After installing all the Gtk-2.0 stuff to make configure happy, it still doesn't work due to a syntax error:

checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/dist-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
checking for headers required to compile python extensions... found
sed: can't read ${exec_prefix}/lib/python2.7/config/Makefile: No such file or directory
sed: can't read ${exec_prefix}/lib/python2.7/config/Makefile: No such file or directory
checking for PYGTK... no
configure: WARNING: No package 'pygobject-2.0' found
No package 'pygtk-2.0' found
configure: WARNING: Disabling python support
checking for glib-genmarshal... /usr/bin/glib-genmarshal
checking for glib-mkenums... /usr/bin/glib-mkenums
./configure: line 15288: syntax error near unexpected token `yes'
./configure: line 15288: `MATE_COMPILE_WARNINGS(yes)'

**Comment by itzexor** [comment]
I created a pull request https://github.com/linuxmint/xed/pull/8 to fix this. Also, you can pass --with-gtk=3.0 to autogen.sh to build with gtk3

**Comment by itzexor** [comment]
This should be fixed now by pull request https://github.com/linuxmint/xed/pull/9 which has been merged.
