### ISSUE TITLE
Add function to set default save location. 

### ISSUE THREAD

**Issue by calexil** [linuxmint/xed#71]
Having to set the save location every time you save a file for the first time is annoying and tedious. 

please add a line or two, for allowing setting the default save location

**Comment by clefebvre** [comment]
That sounds overkill to me.

Assuming you needed to often create new files in some location, you could do so with nemo bookmarks pretty fast, either by accessing them in the filechooser dialog or by creating the file in Nemo directly.

**Comment by calexil** [comment]
k... nvm ;_;

**Comment by drbogi** [comment]
I have simple and efficiency solutions: Custom bookmark in File_browser_Pane plugins, make just one more click to any desired hdd locations.

Described here: https://github.com/linuxmint/xed/issues/66
