### ISSUE TITLE
Feature Request: File Differences in side by side panes

### ISSUE THREAD

**Issue by dozor** [linuxmint/xed#72]
# File differences feature request

It would be very useful to be able to open up two text files side by side and view the differences between them.  (Similar to Notepad++)

Ideally, there would be configurable color high lighting to see line modifications, removals, and additions.

It would also be useful to have a "view only the differences" option to hide all the lines that are the same.

**Comment by JosephMcc** [comment]
Meld is already a great tool for that. Not sure that we need to try and reinvent the wheel.

**Comment by JosephMcc** [comment]
We discussed this and it isn't something we're really interested in implementing. It would be a significant amount of work to provide functionality that is already provided by Meld, which does the job extremely well.
