### ISSUE TITLE
Searchbar icons are not loaded

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/xed#76]
![_2017-02-02_13-17-03](https://cloud.githubusercontent.com/assets/7345761/22545931/df690a6c-e94b-11e6-836a-1408ca24ee0d.png)
I've installed xed on Xubuntu 16.04 alongside with xed-common, mint-themes,  mint-themes-gtk3, mint-x-icons, mint-y-icons all form Mint 18.1 repo

**Comment by JosephMcc** [comment]
You need to build and install xapps as well: https://github.com/linuxmint/xapps
We need to add a proper dependency on this.

**Comment by Yanpas** [comment]
Yes, that helped
