### ISSUE TITLE
I get the following error message when running Xed from command line

### ISSUE THREAD

**Issue by s7jones** [linuxmint/xed#77]
When opening some files in Xed from the command line I get the following message:

(xed:5660): Gtk-CRITICAL **: gtk_accel_label_set_accel_closure: assertion 'gtk_accel_group_from_accel_closure (accel_closure) != NULL' failed 

I am running Linux Mint 18.1 Cinnamon 64-bit.

**Comment by JosephMcc** [comment]
Yeah, I'll try to track this down. It's coming from the file browser plugin.

**Comment by JosephMcc** [comment]
This is fixed in git master.
