### ISSUE TITLE
The sidebar an the tab titles contain redundant info, option to disable tab titles

### ISSUE THREAD

**Issue by maxheise** [linuxmint/xed#78]
Hello,

I like to use the sidebar when I have multiple files open in xed.

However when using the sidebar the tab titles are redundant and are taking up valuable screen real estate. The displayed file names are just redundant.

I'd like to request an option to disable tab titles when using a sidebar. I hope the screenshot with the areas marked in red do illustrate what I mean.

Ty
BR

![xed_redundant info in sidebar and tabs titles](https://cloud.githubusercontent.com/assets/7600641/22708348/35eeb02a-ed76-11e6-8744-b8baf2408b24.png)

**Comment by JosephMcc** [comment]
I really don't understand how the titles in the tab are taking up valuable screen real estate. You want to hide the tabs completely when the sidebar is open? I'm not sure it's worth adding an option for a very minimal gain.

**Comment by maxheise** [comment]
Hello JosephMcc,

yes, I do want to hide the tab titles completely when using the sidebar, i.e. I am suggesting an option to hide the tab titles completely when using the sidebar.

I already have the file's names in the sidebar, no need to put them twice on the screen.

Also with a screen with 16:10 or 16:9 aspect ratio I do have lots of width when editing source code, but what I do not have enough is enough height, so the tab titles are taking up screen real estate that I would rather have to view more source code at once.

And working out of the office on a laptop just makes the issue more apparent, because then the overall screen is smaller.

I hope that clarifies what I meant earlier.

**Comment by JosephMcc** [comment]
After discussion this isn't something we really want to implement. There are already methods for gaining the additional vertical space such as hiding the toolbar or running fullscreen.
