### ISSUE TITLE
Highlight current row in wrapped line

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/xed#79]
If you have documents with very long lines which wrap into blocks of text, the "Highlight current line" preference doesn't help you keep your place. It does highlight the "line" in the text file like it's supposed to, but it doesn't highlight only the row of text on the screen.

So I would like a new additional option to _highlight the current row_.

You could also have both options enabled, so for example the document background would be white, the long highlighted line which is wrapped into 10 rows would be a big highlighted block with a light grey background, and the current _row_ would be highlighted yellow for example.

Or if you only had "Highlight current row" enabled and "Highlight current line" was not enabled, then only the current row would be highlighted.

**Comment by JosephMcc** [comment]
Thanks for the request but after discussing this it isn't something we really want to implement. The line highlighting is functionality is provided by GtkSourceView and to implement this would require more work than it would likely be worth.
