### ISSUE TITLE
How to Set Scroll Bars to Display All the Time in XED..?

### ISSUE THREAD

**Issue by FizWork** [linuxmint/xed#85]
Hi all,

I want to know how to display the scroll-bar... Very annoying (all the time) when I click any long code I write with this editor... I don't want to install another Text / Code Editor because I love to use simple Editor like XED...

Hope someone can help me with this...

**Comment by JosephMcc** [comment]
This is globally controlled in gtk3. It's not currently handled by xed itself. If Cinnamon you can disable the overlay scrollbars globally under Cinnamon Settings->General.

**Comment by zorbama** [comment]
@JosephMcc Looking at the general settings menu in Cinnamon, I can't find that option, nor can I find it anywhere else in Cinnamon settings. Is there any other way to modify this setting?

**Comment by JosephMcc** [comment]
In Cinnamon 3.2 it is the System Settings->Effects->Overlay scroll bars setting.

**Comment by zorbama** [comment]
Thanks, found it. :)
