### ISSUE TITLE
"sudo xed" did chown root.root on config files - catastrophic results

### ISSUE THREAD

**Issue by jeisner** [linuxmint/xed#87]
I edited a systemwide config file using sudo xed.

Much later, when I restarted X, the window manager was unable to read any settings, and lots of things were mysteriously missing (taskbar, keyboard remappings, desktop background, compiz, ...).

Why?  As a side effect, my use of sudo xed had updated my personal config files ~/.config/duser/user and ~/.config/xed/xed.ini, silently changing them to have user root and group root.  My umask is 022, so this made them unreadable by normal users.

**Comment by jeisner** [comment]
It's not clear what the best solution is, but here is a simple one: 
If the effective user isn't the same as the real user, then don't change any config files.

**Comment by JosephMcc** [comment]
Not really sure how this is a xed bug. You probably shouldn't use sudo like that: https://forums.linuxmint.com/viewtopic.php?f=42&t=228412

**Comment by jeisner** [comment]
Thanks.  I think this is an issue because my error is easy to make -- "sudo xed" gets more hits on Google than "gksudo xed" -- and leads to wide-ranging consequences whose cause is hard to identify.  

(This tracker is an issue tracker, not a bug tracker.  I agree that xed doesn't have a bug, but I am nonetheless suggesting that it could deal better with this issue.  Arguably the design bug was in the original design of sudo, which had to be preserved for legacy reasons, with gksudo being the patched version.)

Mint aims to be easy to use for novice users.  So perhaps tools such as xed should pop up a warning when they are mistakenly run under sudo rather than gksudo.  My guess is that novice users are more likely to use xed as root than other MATE tools, because they have to edit config files.
