### ISSUE TITLE
Add option to block xed till opened file is closed

### ISSUE THREAD

**Issue by xenopeek** [linuxmint/xed#90]
The safest way to edit files as root is to use sudoedit (see https://blog.martin-graesslin.com/blog/2017/02/editing-files-as-root/). sudoedit creates a user-writable copy of a root-owned file, runs the user's preferred editor to edit that temporary file and after closing the editor copies the file (if changed) back as root. Only the file copy actions are run as root; the editor is run as the user. Currently it is not possible to use xed with sudoedit because xed doesn't block but immediately returns.

gedit and kate both have an option to open the editor and block till it is closed again (or if the editor was already open, block till the tab with the file to edit is closed). I suggest a similar option be added to xed so xed can be used with sudoedit.

gedit:
-w, --wait : Open files and block the gedit process

kate:
-b, --block : If using an already running Kate instance, block until it exits, if URLs given to open.

**Comment by JosephMcc** [comment]
I'll take a look at making this work.
