### ISSUE TITLE
Increase number of recent files

### ISSUE THREAD

**Issue by rebelxt** [linuxmint/xed#96]
I would like to see 10 files in the list of recent files shown when the File menu button is clicked. The preferable way to achieve this would be to have a user preference for the number of files.

**Comment by JosephMcc** [comment]
There should be a gsettings key to change this. I think on 1.2.2 it's org.x.editor max-recents. I know it works on git master, I just tried setting it 10 and it's fine.

**Comment by danilobatistaqueiroz** [comment]
Linux Mint 19, xed 1.8.3: You can find on: org/x/editor/preferences/ui/max-recents
