### ISSUE TITLE
Scrollbar goes over text in RTL mode

### ISSUE THREAD

**Issue by zorbama** [linuxmint/xed#98]
To reproduce:

1. Write some text in Hebrew (or another right-to-left language).
1. Create enough lines of text to make the document scrollable.
1. try to use the mouse to place the cursor at the start of a line.

Expected result: there should be no interference when trying to move about the document.

Actual result: the scroll bar hides the start of the line, preventing the user from placing the cursor there using the mouse.

**Comment by zorbama** [comment]
A fix for this is possible when disabling overlay scroll bars via the Cinnamon effects settings menu, so it's not as troublesome, however to have this happening out of the box has left me confused and I had to search for the solution for a while.

**Comment by JosephMcc** [comment]
I'll try to troubleshoot this as best I can as someone who doesn't speak/write a RTL language. 

One solution is to display line numbers as a workaround.

**Comment by JosephMcc** [comment]
I've got a follow up question. Are you trying to use a RTL language while launching xed in a LTR layout? For example if I run `LC_ALL=he_IL.utf8 xed` with my language set to Hebrew everything seems to work fine. The entire interface is flipped.

If you are trying to mix the two I'm not really sure that it is a bug. Everything is behaving as you are asking it to. In that case disabling overlay scrollbars is probably the best workaround you can get.

**Comment by zorbama** [comment]
My operating system language and the application's UI language is in English, for convenience. The text itself is Hebrew. Unfortunately, line numbers appear on the left side for me, I suppose that it is a matter of the UI's direction.
Perhaps this problem will not occur to many people, and the solution is acceptable as far as I'm concerned, however, finding it took a while. Perhaps that too is unavoidable. :)

**Comment by JosephMcc** [comment]
Yeah, the line numbers appearing on the left are due to the application being launched with a LTR language. I'm going to close this issue. We have https://github.com/linuxmint/xed/issues/85 which covers the overlay scrollbars issue.
